### ISSUE TITLE
Can't successfully transfer audio when join an existing room for the first time after app open (iPhone)

### ISSUE THREAD

**Issue by acgacgacgacg** [livekit/client-sdk-flutter#103]
### Describe bug

When app is opened and the client joins an existing room for the first time, 
the client can't transfer audio.
The track is published and the client **can receive** and hear other participants' tracks,
but the client's track **can't be received** by other participants and `localParticipant.isSpeaking` is always `false`.

And if the client disconnect and then connect again, 
the above problem won't occur.
Also, if the client creates a room, the above problem won't occur either.

### Version

client: flutter, 0.5.8
server: k8s, 0.15.5

### How to reproduce

Use flutter example app.
Create a room on a device or emulator.
On an iphone 13 mini emulator, join the same room and publish audio.

This problem won't occur on Android.
It seems to be that the microphone won't get activated for the first time.

#### open app for the first time and joins an existing room
<img width="318" alt="image" src="https://user-images.githubusercontent.com/10584507/161979269-39949ae3-e3a5-4bab-b487-7bb9274534f8.png">

#### disconnect once and joins the same room again
<img width="313" alt="image" src="https://user-images.githubusercontent.com/10584507/161979530-a8a9a711-2bd8-45e4-a506-81250c3470b4.png">

**Comment by davidzhao** [comment]
Can you reproduce this on an actual iPhone device? iPhone simulator has some weird behaviors at times and we want to ensure that's not the issue.

**Comment by acgacgacgacg** [comment]
@davidzhao 
Yes, it occurs on iphone device.
I'm trying Hiroshi's audio-fix solution as mentioned here
https://livekit-users.slack.com/archives/C01KVTJH6BX/p1649258806863449?thread_ts=1649249928.495409&cid=C01KVTJH6BX

**Comment by davidzhao** [comment]
fixed in 0.5.9

**Comment by hiroshihorie** [comment]
@acgacgacgacg Thanks for the report, let me know if you have any other issues.
