### ISSUE TITLE
VideoParameters not exported

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/client-sdk-flutter#112]
There are no VideoParameters (or VideoParametersPresets) available in the package.

It's missing an `export 'src/types/video_parameters.dart';` on livekit_client.dart
note there are other src/types files not being exported, but I'm not sure if they all need to

tested on v0.5.9 (main doesn't seem to have it either)

**Comment by hiroshihorie** [comment]
Nice find !, advanced uses would need these types.
