### ISSUE TITLE
publishData results in TimeoutException on mobile platforms

### ISSUE THREAD

**Issue by Parfyonator** [livekit/client-sdk-flutter#114]
## Problem

For some reason `publishData` method of `LocalParticipant` class fails to send message on mobile platforms (iOS/Android), although it works fine on web: during the connection to the same room participants receive messages sent by users connected with web versions of the app, while messages sent by mobile clients never received by any participant. 

During the debug stage on mobile devices the clicking on **send demo data** button results in `TimeoutException` after some delay:

```
E/flutter (17084): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LiveKit Exception TimeoutException Timeout
```

## Reproduce

This behaviour can be reproduced with the example from this package.

## Additional

I checked LiveKit deployment with LiveKit Tester (https://livekit.io/connection-test). Everything seems to work fine (all tests passed).

Flutter version: `2.10.5`

Dart version: `2.16.2`

**Comment by Parfyonator** [comment]
I didn't have much time to dig into this problem but turns out that omitting [this check](https://github.com/livekit/client-sdk-flutter/blob/377e0c5209b51c89d2c1d5a6dc38ef72e0313a86/lib/src/core/engine.dart#L214) "solves" the problem: it doesn't crash the application but eventually lets me send messages via the data channel. It means that the data channel is actually opened and ready to send data but for some reason [this check](https://github.com/livekit/client-sdk-flutter/blob/377e0c5209b51c89d2c1d5a6dc38ef72e0313a86/lib/src/core/engine.dart#L234) evaluates to `true` and starts the process of waiting for the channel to open, which results in `TimeoutException `.

**Comment by hiroshihorie** [comment]
interestingly, I can't reproduce this. What is your server version ?

**Comment by Parfyonator** [comment]
Hi. `v0.15.6` I assume.
Is there a straightforward way to check the version of the currently running livekit server? Docker says that it is running the latest version of the `livekit/livekit-server` image. Command `docker image inspect` gives me version `v0.15.6` (`"org.opencontainers.image.version":"v0.15.6"`).

**Comment by davidliu** [comment]
@hiroshihorie not sure if it's related at all, but looks like there's an issue where the dataChannel id gets changed and the underlying flutter-webrtc can't locate the datachannel any more. I'll look into fixing that.

**Comment by davidzhao** [comment]
This issue had been fixed. please reopen if this continues to be a problem.
