### ISSUE TITLE
Windows 11 - Crash on Connect in Example Project, Version 1.0.1

### ISSUE THREAD

**Issue by design2be** [livekit/client-sdk-flutter#129]
On the example project the app crashes directly on connect with Windows 11 (Version 21H2) using the Live Kit Version 1.0.1.

The persmissions for video & microphone have been granted according to the flutter permission handler. (https://pub.dev/packages/permission_handler) 

Version of WebRTC is already 0.8.9.

```
flutter: 03:49:29: RemoteTrackPublication.updateTrack track: null
flutter: 03:49:29: Room Connect completed
flutter: 03:49:29: [ParticipantEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_seL6mvs4JCnG, identity: 5), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
flutter: 03:49:29: [RoomEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_seL6mvs4JCnG, identity: 5), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
flutter: 03:49:29: [PCTransport] creating {sdpSemantics: unified-plan, iceServers: [{urls: [turn:3.121.184.220:443?transport=udp], username: drunkenunping-72248, credential: drunkenunping-72248}]}
flutter: 03:49:29: [SignalEvent] Instance of 'SignalTokenUpdatedEvent'
flutter: 03:49:29: [SignalEvent] Instance of 'SignalOfferEvent'
3
flutter: 03:49:29: [SignalEvent] Instance of 'SignalTrickleEvent'
flutter: 03:49:29: [SignalEvent] Instance of 'SignalParticipantUpdateEvent'
flutter: 03:49:29: [ParticipantEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_seL6mvs4JCnG, identity: 5), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
flutter: 03:49:29: [RoomEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_seL6mvs4JCnG, identity: 5), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
Lost connection to device.
```

**Comment by cloudwebrtc** [comment]
Does the crash happen after publishing local tracks?

**Comment by design2be** [comment]
It crashes on connect: connect.dart line 89. 

The server is a remote server and it works under OSX. 

Settings are default like shown in the graphic below. 

Thanks!

![Crash](https://user-images.githubusercontent.com/4869339/175051729-e5cbb5d6-82c3-4651-adaa-0f84856041ba.png)

![Crash_Settings](https://user-images.githubusercontent.com/4869339/175051697-c00a0aef-d9bf-489c-a9a4-a64045f5f832.png)

**Comment by cloudwebrtc** [comment]
@design2be  There is some info that might help me, is the type of windows CPU you are using AMD or Intel, what is the version of livekit-server and is the current encoding h264?

**Comment by design2be** [comment]
@cloudwebrtc Here the collected infos:
PC:
Processor	Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz   3.00 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor

Live Kit Server Version: 0.15.6

Lets see if a server update will solve things.

Thanks already!

**Comment by design2be** [comment]
Update:

We updated the live kit server to 1.1.0 and the demo app crashes in the same way.

**Comment by cloudwebrtc** [comment]
Okay, I will try to make a test in the same environment.

**Comment by vjeson** [comment]
I meet the same problem， and I found that it cause by invalid iceServers fomat on windows 
the iceserver return from livekit-server and was formated as
`
{sdpSemantics: unified-plan, iceServers: [{urls: [turn:xxxxxx:xxx?transport=udp], username: xxxx, credential: xxxx, password: xxxx}, {urls: [stun:xxxxx:3478]}]}
`
It cannot be parsed correctly ,I tested with debug version libwebrtc and got the error message
(ice_server_parsing.cc:240): TURN server with empty username or password
(peer_connection.cc:476): PeerConnection initialization failed
(rtc_peerconnection_impl.cc:427): CreatePeerConnection failed
(rtc_peerconnection_impl.cc:607): Close

the iceserver was set from here
`
  Future<void> _configurePeerConnections() async {
    if (publisher != null || subscriber != null) {
      logger.warning('Already configured');
      return;
    }

    // RTCConfiguration? config;
    // use server-provided iceServers if not provided by user
    var serverIceServers =
        _serverProvidedIceServers.map((e) => e.toSDKType()).toList();
`

**Comment by cloudwebrtc** [comment]
@vjeson  I submitted a fix https://github.com/flutter-webrtc/flutter-webrtc/commit/9ea1e85af1ae8dec58d441ee8b9ede01611fea7e and the test passed the configuration below, can you give me feedback after testing it? 

```
    final config = <String, dynamic>{
      'sdpSemantics': 'unified-plan',
      'iceServers': [
        {
          'urls': ['turn:127.0.0.1:3478?transport=udp'],
          'username': 'xxxx',
          'credential': 'xxxx',
          'password': 'xxxx'
        },
        {
          'urls': ['stun:127.0.0.1:3478']
        }
      ]
    };
```

**Comment by vjeson** [comment]
I tested it .It works perfectly. thanks very much

**Comment by cloudwebrtc** [comment]
@vjeson Thanks for your feedback, I will release a new version soon to fix this issue

**Comment by design2be** [comment]
Thanks so much for this fix! Its no longer crashing and the fix work now on windows :-)

Shall we close this issue then?

**Comment by cloudwebrtc** [comment]
@design2be I made a PR to fix it.
