### ISSUE TITLE
Failed to run ios simulator: No such module 'WebRTC'

### ISSUE THREAD

**Issue by hrxiang** [livekit/client-sdk-flutter#132]
Swift Compiler Error (Xcode): No such module 'WebRTC'
/Users/xxxxx/Development/flutter/.pub-cache/hosted/pub.flutter-io.cn/livekit_client-1.0.0/ios/Classes/LiveKitPlugin.swift:0:7

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 11.3.1 20E241 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] Proxy Configuration
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by zionnite** [comment]
according to the documentation its not expected to run on ios simulator but on real device

**Comment by daniloapr** [comment]
As commented [here](https://github.com/flutter/flutter/issues/64502#issuecomment-699523589), you can add this line in your Podspec file. That worked for me:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|

      # Workaround for https://github.com/flutter/flutter/issues/64502
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' # <= this line

    end
  end
end
```

**Comment by jascodes** [comment]
@daniloapr But that for using m1 machine for complilation. Simulator still don't work as per docs. you would need to test on real device.

**Comment by cloudwebrtc** [comment]
@jascodes thanks, I'll look into m1 simulator next week

**Comment by cloudwebrtc** [comment]
Please upgrade to the latest version of Xcode/Flutter SDK, the example can already work correctly in the simulator (M1)
<img width="392" alt="image" src="https://user-images.githubusercontent.com/17733746/196188496-c4488e2c-4b81-476e-9a46-c5646ee55cf2.png">
