### ISSUE TITLE
How to change the audio output from speaker_phone to earpiece speaker?

### ISSUE THREAD

**Issue by jdwxp** [livekit/client-sdk-flutter#137]

**Comment by jdwxp** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 3.0.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.69.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

livekit:1.0.0
ios 14.4

ediaStreamTrack.enableSpeakerphone(enable)

i found that iOS phones don't work，android is ok

**Comment by Biswajit1729** [comment]
not working in android 
please help

**Comment by Biswajit1729** [comment]
solution of audio out put is here

https://github.com/livekit/client-sdk-flutter/blob/main/lib/src/hardware/hardware.dart

**Comment by BenCherif** [comment]
@Biswajit1729  how to use this in the code ?

**Comment by Biswajit1729** [comment]
Yes 
Thank you
