### ISSUE TITLE
VideoDimensions backwards? (iOS)

### ISSUE THREAD

**Issue by mwk24** [livekit/client-sdk-flutter#148]
https://github.com/livekit/client-sdk-flutter/blob/7c16d2f3ecd5180fe95c8db9b3c578bc6c457482/lib/src/types/video_dimensions.dart#L7

Will delete if false alarm, but seems on iPhone height and width are backwards.

**Comment by cloudwebrtc** [comment]
On the mobile side, height and width are sometimes confusing, and the actual parameters are determined by rotation.
