### ISSUE TITLE
Failed to build for iOS with version 1.1.0

### ISSUE THREAD

**Issue by FreddyKaiser** [livekit/client-sdk-flutter#150]
After updating from livekit_client: 1.0.1 to livekit_client: 1.1., building for iOS generates this error:
```
[!] CocoaPods could not find compatible versions for pod "WebRTC-SDK":
      In snapshot (Podfile.lock):
        WebRTC-SDK (= 97.4692.05, ~> 97.4692)

      In Podfile:
        flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`) was resolved to 0.9.2, which depends on
          WebRTC-SDK (= 104.5112.02)

        livekit_client (from `.symlinks/plugins/livekit_client/ios`) was resolved to 1.0.0, which depends on
          WebRTC-SDK (~> 97.4692)

```

**Comment by cloudwebrtc** [comment]
I think you need to delete the `ios/Podfile.lock`,  and then run `pod update`

**Comment by FreddyKaiser** [comment]
> I think you need to delete the `ios/Podfile.lock`, and then run `pod update`

Tried this and other cleanup commands like `flutter clean`but no success. Does it work on your side?

**Comment by chauvansang1997** [comment]
convert your podfile to ios 10

**Comment by FreddyKaiser** [comment]
> convert your podfile to ios 10
How?

**Comment by xor22h** [comment]
I think the issue is in https://github.com/livekit/client-sdk-flutter/blob/v1.1.0/ios/livekit_client.podspec#L3 where, one in v1.1.0 resolves has name of 1.0.0

**Comment by cloudwebrtc** [comment]
okay, I'm confirming where the issue is.

**Comment by cloudwebrtc** [comment]
@FreddyKaiser @xor22h  I created a hotfix (seems ok in my local test), can you add this dependency to your project,  help me confirm this fix.

```yaml
livekit_client:
   git:
     url: https://github.com/livekit/client-sdk-flutter.git
     ref: fix/hotfix-for-darwin-build-errros
```

**Comment by FreddyKaiser** [comment]
@cloudwebrtc with your fix it is successfully built again:
```
Installing WebRTC-SDK (104.5112.02)
Installing livekit_client (1.1.0)
```
