### ISSUE TITLE
setSpeakerphoneOn is not working.

### ISSUE THREAD

**Issue by BenCherif** [livekit/client-sdk-flutter#167]
even i'm run the app on android it show me this error .
Unhandled Exception: UnimplementedError: setSpeakerphoneOn only support on iOS/Android

what i figure out is that the condition you put in Hardware class 
```
 if (!rtc.WebRTC.platformIsAndroid || !rtc.WebRTC.platformIsIOS) {
      throw UnimplementedError('setSpeakerphoneOn only support on iOS/Android');
 }
```

i got this error because you use || operator so at least on condition is true , i'm run the app on  android so the !rtc.WebRTC.platformIsIOS condition is true :/   one thing you can set this conditon as this  .
 

```
 if (rtc.WebRTC.platformIsAndroid || rtc.WebRTC.platformIsIOS) {
      await rtc.Helper.setSpeakerphoneOn(enable);
 }else{
      throw UnimplementedError('setSpeakerphoneOn only support on iOS/Android');
}
```
 Or use && operator instead of ||

**Comment by cloudwebrtc** [comment]
okay, It's an obvious bug, I'll fix it now
