### ISSUE TITLE
WS connection keeps dropping

### ISSUE THREAD

**Issue by msackman** [livekit/client-sdk-flutter#171]
Somewhere between version 1.1.1 and 1.1.2, a change was introduced which causes the ws connection from the client to the server to drop about once every 20 seconds.
This may only manifest for android, not sure.

Looking through the commits, I think there's something maybe not quite right with the ping-pong that's been added.
On the server I'm using:

```
	github.com/livekit/livekit-server v1.2.2-0.20220914044935-779a67985257
	github.com/livekit/protocol v1.0.2-0.20220909090645-6ec04e9ca47e
	github.com/livekit/server-sdk-go v0.10.5
```

With 1.1.1, the ws stays connected to the room and all is well - logs are quiet. With 1.1.2 (or greater), on the client side I get log entries which suggest something is happening about every 20 seconds. And on the server side, I get entries like this:

```
11:00AM DBG exit ws read loop for closed connection connID=CO_taUUt5itcjTs logger=livekit participant=28y3uhzufIXUf92DKhh8mVGmyUB remote=false room=2EkpnlScz3SincEc3ElLvEMCvae roomID=RM_g3bfrjZRupuc v=1
11:00AM INF finishing WS connection connID=CO_taUUt5itcjTs logger=livekit participant=28y3uhzufIXUf92DKhh8mVGmyUB remote=false room=2EkpnlScz3SincEc3ElLvEMCvae roomID=RM_g3bfrjZRupuc v=0
11:00AM INF RTC session finishing logger=livekit pID=PA_2pwRWXnL3i73 participant=28y3uhzufIXUf92DKhh8mVGmyUB room=2EkpnlScz3SincEc3ElLvEMCvae roomID=RM_g3bfrjZRupuc v=0
11:00AM INF source closed connection connID=CO_taUUt5itcjTs logger=livekit participant=28y3uhzufIXUf92DKhh8mVGmyUB remote=false room=2EkpnlScz3SincEc3ElLvEMCvae roomID=RM_g3bfrjZRupuc v=0
```

**Comment by jascodes** [comment]
I am facing this on flutter web client

**Comment by cloudwebrtc** [comment]
It looks like ping/pong doesn't work very well, I'm checking
