### ISSUE TITLE
Allow configuration of timeouts

### ISSUE THREAD

**Issue by janoskranczler** [livekit/client-sdk-flutter#182]
Sometimes the room join times out if the connection is slow. Currently, the timeouts are hard-coded for Engine.connect:
https://github.com/livekit/client-sdk-flutter/blob/b231fda5216bdf532dd64ca52d95ac7150834c38/lib/src/core/engine.dart#L136
https://github.com/livekit/client-sdk-flutter/blob/b231fda5216bdf532dd64ca52d95ac7150834c38/lib/src/core/engine.dart#L145
It would be better if the timeouts were configurable.

**Comment by Sang-Nguyen-Sunny** [comment]
I'm also experiencing a constant timeout and can't reconnect
