### ISSUE TITLE
After refreshing LiveKit server to 1.2.3  SDK can't connect to server

### ISSUE THREAD

**Issue by janoskranczler** [livekit/client-sdk-flutter#184]
After refreshing LiveKit server to 1.2.3  SDK can't connect to server. Neither Android or iOS.

Flutter version:
[✓] Flutter (Channel stable, 3.3.3, on macOS 12.6 21G115 darwin-arm, locale en-HU)
    • Flutter version 3.3.3 on channel stable at /Users/janoskranczler/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (7 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

Plugin version: 1.1.4

**Comment by davidzhao** [comment]
How is your server configured? Is it using a single port or a wider port range?

**Comment by janoskranczler** [comment]
Using a wider port range: 50000-60000.

**Comment by cloudwebrtc** [comment]
After testing for half an hour, there was an occasional failure to connect. It seems to be a deadlock of server signaling. The client must be killed and restarted before the client can connect.

**Comment by cloudwebrtc** [comment]
but I found another issue when I turned on Ethernet and WIFI on mac at the same time, the Android client connection timed out (the ICE connection could not be established, maybe it is related to the default route on the mac),

**Comment by janoskranczler** [comment]
Thank you for your help in advance. We are using Redis. We can't connect with a client when we update the server to 1.2.3 (from 1.2.2).
```2022-10-12T13:06:35.097Z	INFO	livekit	rtc/participant_signal.go:181	could not send message to participant	{"room": "1pnjef2fic4r6p0m", "roomID": "RM_W2iS8TVzCFm8", "participant": "8smj8i2w44cf2h53", "pID": "PA_FTJt286V4KQg", "remote": false, "message": "*livekit.SignalResponse_Leave", "error": "no response sink"}```
Our RTC configuration:
```  rtc:
    allow_tcp_fallback: true
    use_ice_lite: false
    use_external_ip: false
    port_range_start: 50000
    port_range_end: 60000
    tcp_port: 7801```

**Comment by cloudwebrtc** [comment]
I looked at this error and it seems to be related to the `response_sink` not being found, can you try turning off redis and testing again?

https://github.com/livekit/livekit/blob/v1.2.3/pkg/rtc/participant_signal.go#L181
https://github.com/livekit/livekit/blob/v1.2.3/pkg/rtc/participant_signal.go#L13-L22

**Comment by janoskranczler** [comment]
I didn't mention it, but we tested it locally (docker) without Redis and it works without it.

**Comment by cloudwebrtc** [comment]
I tested it locally, with or without `redis` it can connect normally, so I can't reproduce the error, have you checked whether the TOKEN is expired?

**Comment by janoskranczler** [comment]
@cloudwebrtc The token isn't expired. Could you help me what kind of log I should send to you?

**Comment by cloudwebrtc** [comment]
If you can provide me with the logs of the flutter client and server logs when the issue occurs, it should help me find the issue.

**Comment by janoskranczler** [comment]
[issue_184_client.log](https://github.com/livekit/client-sdk-flutter/files/9800972/issue_184_client.log)
[issue_184_server.log](https://github.com/livekit/client-sdk-flutter/files/9800973/issue_184_server.log)
I've added the client-server logs. The client logs are newer but regarding to the same issue.

**Comment by cloudwebrtc** [comment]
I read the client log and it looks like the wss signaling client is connected, but the ICE connection is not successful.
Can you send me a test token and your server url in Slack? If I can reproduce the problem in my local example, the bug should be easier to locate.

**Comment by cloudwebrtc** [comment]
You can add breakpoints in these two places
https://github.com/livekit/client-sdk-flutter/blob/eaacbf77c542121f733aba514f3400252d5ee72c/lib/src/core/engine.dart#L377
https://github.com/livekit/client-sdk-flutter/blob/eaacbf77c542121f733aba514f3400252d5ee72c/lib/src/core/engine.dart#L390

**Comment by davidzhao** [comment]
@janoskranczler are you able to reproduce this issue with our [example web app](https://example.livekit.io) when not using `localhost`? which environment are you running your server in?

This might not be a flutter specific issue, but rather configuration / connectivity

**Comment by cloudwebrtc** [comment]
@davidzhao Last night I tested with @janoskranczler's server and reproduced the error in our example, I found two clues
1. The server only sends the host candidate of a private address to the flutter app
2. The client receives and loads the turn server to livekit-sdk, but it seems that there is no relay canidate and no reflx candidate, only 4 host cands are seen in pc.onIceCandidate

There are two possibilities here:
1) The client did not successfully load the turn server information, and the relay channel could not be created
2) The turn/stun server of the service is invalid,

**Comment by davidzhao** [comment]
This sounds like an issue with the server setup. The server should not be giving it private IPs.. @janoskranczler please ensure `use_external_ip` is set to true in your server configuration. See [deployment docs](https://docs.livekit.io/deploy/#configuration).

**Comment by janoskranczler** [comment]
@davidzhao We didn't change the server and everything worked on server version 1.2.1.
On 1.2.3 only the Flutter client doesn't work. The JS client works well.
The reason we are not publishing public IP addresses is to be able to transfer TURN traffic to private peering connections so that the TURN servers can act as an edge proxy to our network. And this worked well with 1.2.1 and before since we have manually overridden ICE server URLs for each client (mobile and web).

**Comment by janoskranczler** [comment]
@davidzhao @cloudwebrtc I debugged today and found a few issues that cause the problem. 

### ICE servers
According to the comment the user-provided ICE servers should take priority over the server-provided ones:
https://github.com/livekit/client-sdk-flutter/blob/eaacbf77c542121f733aba514f3400252d5ee72c/lib/src/core/engine.dart#L348-L347
But that's not the case:
https://github.com/livekit/client-sdk-flutter/blob/eaacbf77c542121f733aba514f3400252d5ee72c/lib/src/core/engine.dart#L353-L357
Therefore I couldn't provide turn servers in the client code despite the fact I can provide ConnectOptions with turn servers to the Room instance and also to the Room.connect() method:
https://github.com/livekit/client-sdk-flutter/blob/3d8bf966516294fd475ab1b9960b4ef7246d3401/lib/src/options.dart#L29

### force relay
The same is true for the `forceRelay` switch. The user-provided setting is not used because it is overridden:
https://github.com/livekit/client-sdk-flutter/blob/eaacbf77c542121f733aba514f3400252d5ee72c/lib/src/core/engine.dart#L637-L639
https://github.com/livekit/client-sdk-flutter/blob/3d8bf966516294fd475ab1b9960b4ef7246d3401/lib/src/types/other.dart#L88

### ICE server credential
Instead of the credential the usename is used:
https://github.com/livekit/client-sdk-flutter/blob/3d8bf966516294fd475ab1b9960b4ef7246d3401/lib/src/extensions.dart#L27

**Comment by cloudwebrtc** [comment]
hey @janoskranczler, I think you found useful info, let me try to create a fix branch.

**Comment by janoskranczler** [comment]
@cloudwebrtc Thank you! I've tested it and it works because the credentials are fixed, but in this way, we still don't have the opportunity to configure the ICE servers and forceRelay on the client side, because the server-provided settings take priority over the user-provided ones. Now it works only because we use the LiveKit-provided (embedded) TURN servers but if we would use external TURN servers we couldn't configure them in LiveKit.

**Comment by cloudwebrtc** [comment]
hey @davidzhao, do you have any idea about the priority of `iceServers/forceRelay` for(`server side/client side`)?

**Comment by cloudwebrtc** [comment]
@janoskranczler yeah, I think the correct fix is to have high priority setting iceServers/forceRelay on the client side, I will update the PR later.

**Comment by davidzhao** [comment]
@janoskranczler thank you for digging into the weeds. The typo of credentials -> username is quite embarrassing on our side. I really appreciate it!

**Comment by janoskranczler** [comment]
@cloudwebrtc Thanks for the quick resolution!
