### ISSUE TITLE
Black screen on broadcaster's widget

### ISSUE THREAD

**Issue by fpasalioglu** [livekit/client-sdk-flutter#186]
Hi, 
While there is a broadcaster in a room in my app, when a new broadcaster arrives, the image of both broadcasters appears correctly, but when the new broadcaster exits, the old broadcaster sees himself on a black screen. His voice is heard, but he and the audience see a black screen.
**When you put the application in the background and open it again, the camera works.**

@davidzhao @cloudwebrtc

**Comment by fpasalioglu** [comment]
I am using directly github repo, not pub dev.

**Comment by fpasalioglu** [comment]
Maybe these error logs will help.

```
Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client API Level 2
E/CameraCaptureSession(23321): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(23321): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:652: Camera 1: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession(23321): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1599)
E/CameraCaptureSession(23321): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession(23321): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1315)
E/CameraCaptureSession(23321): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(23321): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:790)
E/CameraCaptureSession(23321): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:259)
E/CameraCaptureSession(23321): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(23321): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(23321): 	at android.os.Looper.loopOnce(Looper.java:226)
E/CameraCaptureSession(23321): 	at android.os.Looper.loop(Looper.java:313)
E/CameraCaptureSession(23321): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/CameraCaptureSession(23321): Caused by: android.os.ServiceSpecificException: cancelRequest:652: Camera 1: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession(23321): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2451)
E/CameraCaptureSession(23321): 	at android.os.Parcel.createException(Parcel.java:2421)
E/CameraCaptureSession(23321): 	at android.os.Parcel.readException(Parcel.java:2404)
E/CameraCaptureSession(23321): 	at android.os.Parcel.readException(Parcel.java:2346)
E/CameraCaptureSession(23321): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:767)
E/CameraCaptureSession(23321): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession(23321): 	... 9 more
I/org.webrtc.Logging(23321): Camera2Session: Stop internal
I/org.webrtc.Logging(23321): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging(23321): Camera2Session: Stop done
```

```
AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging(23321): AndroidVideoDecoder: java.lang.IllegalStateException
E/org.webrtc.Logging(23321): 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/org.webrtc.Logging(23321): 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3535)
E/org.webrtc.Logging(23321): 	at org.webrtc.MediaCodecWrapperFactoryImpl$MediaCodecWrapperImpl.dequeueOutputBuffer(MediaCodecWrapperFactoryImpl.java:72)
E/org.webrtc.Logging(23321): 	at org.webrtc.AndroidVideoDecoder.deliverDecodedFrame(AndroidVideoDecoder.java:380)
E/org.webrtc.Logging(23321): 	at org.webrtc.AndroidVideoDecoder$1.run(AndroidVideoDecoder.java:364)
E/org.webrtc.Logging(23321): AndroidVideoDecoder: deliverDecodedFrame failed
```

**Comment by fpasalioglu** [comment]
I am not using the sample app. I integrated the library into my own application.

The script is as follows:
A broadcaster is in the room and a new broadcaster is joining the room. The video of the participating broadcaster is visible to all. there is no problem.
But there is a problem with the camera connection of the broadcaster who is already in the room (log recordings in my comment above). The broadcaster can't get his own image and the viewers can't get the broadcaster's image. When this publisher puts the app in the background and brings it back to the foreground, everything is fine.

The video is like this:
The publisher on the left is having trouble.
https://youtube.com/shorts/RLwSLknjixY
https://youtube.com/shorts/lKULvYFQPG4

**Comment by fpasalioglu** [comment]
the left broadcaster and the right broadcaster have their own separate rooms. They join each other's rooms to create the structure in the video. In other words, when the broadcaster on the right joins the room of the broadcaster on the left, he does not see his own image on the left and errors occur in the log.

@cloudwebrtc

**Comment by cloudwebrtc** [comment]
I watched your video, but I'm out of ideas (perhaps related to flutter state update), can this issue be reproduced in client-sdk-flutter/example?

**Comment by fpasalioglu** [comment]
I found the error. 
The left broadcaster is broadcasting in a room of his own. The publisher on the right also has a room of his own. They connect to each other's room so that the two broadcasters can see each other. While the camera is used in the broadcaster's own room at the time of connection, when it is connected to the opposite room, the camera access in his own room is cut off and it starts to be used in the other broadcaster's room. That's why the publisher can't see their own image in the local participant widget. we need to make both room objects use the camera. how can we do this?

@cloudwebrtc

**Comment by cloudwebrtc** [comment]
@fpasalioglu Wait, did you publish a localVideoTrack to a different room?

**Comment by fpasalioglu** [comment]
yes. Each broadcaster broadcasts in his own room. I thought that for it to appear in the other broadcaster's room, it should broadcast in the other room as well. The error started here.

I would have to connect to the other room as a viewer and get the broadcaster's video.

**Comment by cloudwebrtc** [comment]
okay, I can probably locate the issue, the videoTrack cannot be held by multiple publishTracks, because the video track getting by flutter-webrtc through getUserMedia is not cloned to each room, so after being released by the first room, it will be invalid in another room

**Comment by fpasalioglu** [comment]
That's exactly the problem. I solved the problem by joining the other room as a viewer and receiving the broadcast of the owner of that room.
Thanks for your help.
