### ISSUE TITLE
[bug][iOS] Microphone indicator won't turn off after microphone is muted

### ISSUE THREAD

**Issue by janoskranczler** [livekit/client-sdk-flutter#196]
**Describe the bug**
After the microphone is muted the microphone indicator (orange dot) won't turn off
**To Reproduce**
1. Install LiveKit example app on a physical iPhone.
2. Join to a LiveKit room. After joining the microphone indicator will be turned on.
3. Mute (turn off) the microphone
4. The indicator will still be turned on.

**Expected behavior**
The microphone indicator turns off after the microphone is muted.
**Platform information**

* **Flutter version**: 
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-arm, locale en-HU)
    • Flutter version 3.3.5 on channel stable at /Users/janoskranczler/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (7 days ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

* **Plugin version**: 1.1.7 - https://github.com/livekit/client-sdk-flutter/commit/22a18d3e9cff352c56870aa723567777855bbf2b
* **Flutter target OS**: iOS
* **Flutter target OS version**: 16.1

**Comment by cloudwebrtc** [comment]
I debugged the libwebrtc code, when executing `track.mute`, we just did `track.enabled = false`, and did not turn off the microphone capture, so we need to use `unpublish` to really terminate the local track, and the microphone indicator should not be shown.

**Comment by davidzhao** [comment]
@cloudwebrtc we handle this in the JS SDK by stopping the underlying track when muted:

https://github.com/livekit/client-sdk-js/blob/main/src/room/track/LocalAudioTrack.ts#L44

I wonder if we can perform a similar operation for Flutter.

**Comment by cloudwebrtc** [comment]
@davidzhao thanks, I have fixed this issue with your prompt,  Tested it on iPhone.
