### ISSUE TITLE
Unable to getDisplayMedia: source not found!

### ISSUE THREAD

**Issue by iooc** [livekit/client-sdk-flutter#198]
Windows 平台调用 函数 LocalVideoTrack.createScreenShareTrack() 提示 Unable to getDisplayMedia: source not found，
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to getDisplayMedia: source not found!
#0      MediaDeviceNative.getDisplayMedia (package:flutter_webrtc/src/native/mediadevices_impl.dart:68:7)
<asynchronous suspension>
#1      LocalTrack.createStream (package:livekit_client/src/track/local/local.dart:132:16)
<asynchronous suspension>
#2      LocalVideoTrack.createScreenShareTrack (package:livekit_client/src/track/local/video.dart:58:20)
<asynchronous suspension>
#3      MutimediaState._shareScreen (package:edapp/teachroom/teachroom.dart:217:22)
<asynchronous suspension>

**Comment by cloudwebrtc** [comment]
Please try this code snippet to enable screen sharing on windows
https://github.com/livekit/client-sdk-flutter/blob/main/example/lib/widgets/controls.dart#L132-L153

**Comment by iooc** [comment]
非常感谢

**Comment by cloudwebrtc** [comment]
Added some notice to README.
https://github.com/livekit/client-sdk-flutter#desktopwindowsmacos
