### ISSUE TITLE
Change mirror settings

### ISSUE THREAD

**Issue by fpasalioglu** [livekit/client-sdk-flutter#199]
How can broadcaster change his video's mirror setting? 
When the broadcaster changes the mirror setting, the video that appears to the viewers should also be mirrored.

**Comment by cloudwebrtc** [comment]
Currently, we can only use mirror rendering when displaying the local front camera, but we cannot mirror the captured video and send it to the far end, which is a video processing feature.

**Comment by fpasalioglu** [comment]
Will there be a work around for this? Mirroring feature is important to us.

**Comment by jdde** [comment]
@fpasalioglu try sending a custom event via data channel to all participants, fetch it and render the received video mirror'd on UI level ;)

**Comment by fpasalioglu** [comment]
@jdde It's a sensible solution. Thanks.
How can I mirror the image? I am using ParticipantWidget.widgetFor()

**Comment by fpasalioglu** [comment]
I solved mirroring with Transform. Thanks for your opinion.

**Comment by jdde** [comment]
@fpasalioglu Awesome!
That's definitely a possible solution.

I just checked our implementation - and I can definitely recommend to not use .widgetFor() for such flexible cases.
In our case, we just grab published video tracks from the participant via participant.getTrackPublicationBySource - with that track object, you can simply use the livekit_client-1.1.7/lib/src/widgets/video_track_renderer.dart and render a VideoTrackRenderer by yourself.
Like this:
VideoTrackRenderer(cameraTrack as VideoTrack,
                    fit: RTCVideoViewObjectFit.RTCVideoViewObjectFitCover, mirrorMode: VideoViewMirrorMode.mirror)

I just realized, that you can provide the mirrorMode on that level ;) 
With that solution, no need to transform it by yourself. And you can handle it like showing an image in your UI. Way more flexible 👍

**Comment by fpasalioglu** [comment]
Thank you for your recommendation. I changed it as you said. This is a more efficient way.
