### ISSUE TITLE
[feature] upgrading packages

### ISSUE THREAD

**Issue by appcapsergen** [livekit/client-sdk-flutter#200]
**Is your feature request related to a problem? Please describe.**
To use livekit_client, one must downgrade connectivity_plus and device_info_plus to use it.

**Describe the solution you'd like**
Upgrading connectivity_plus and device_info_plus packages.

**Comment by jdde** [comment]
@appcapsergen did you tried a dependency_overrides in your pubspec?
Is livekit really not working with that newer version or is it jus pointing to a differen patch version?

Could be a temporary solution for your problem

**Comment by appcapsergen** [comment]
@jdde There is a dependency mismatch, yes.
My project uses the newest version of device_info_plus (8.0.0) for example, while livekit_client uses version 6.0.0 of device_info_plus. This made me have to downgrade to 6.0.0 as well.

**Comment by BenCherif** [comment]
any updates ?

**Comment by appcapsergen** [comment]
@BenCherif you can safely override them. to the versions I mentioned, as I've been doing that since it's been suggested and no casualties have occurred. That's the only update I can give you!

**Comment by BenCherif** [comment]
@appcapsergen  check the latest version the upgrade connectivity_plus .Kind regards
