### ISSUE TITLE
[Question] How can I check if the livekit is still connected or not?

### ISSUE THREAD

**Issue by Sang-Nguyen-Sunny** [livekit/client-sdk-flutter#202]
Is there a way to check if the socket is still running?
Is there a way to check if the room in the livekit is disconnected, remove it completely to open a new connection?

I am having 1 problem, when opening livekit connection, the call works normally. But there are cases, when closing the connection fails without disconnecting, it runs in the background. When opening a new connection, the new connection overrides the old connection. livekit keeps saying "Failed connect to server". Unless the app is uninstalled and reinstalled, the livekit will reconnect normally.

**Comment by cloudwebrtc** [comment]
you can check `room.connectionState`

```dart
var isConnected = room.connectionState == ConnectionState.connected;
```

**Comment by cloudwebrtc** [comment]
> How can I check if the livekit is still connected or not?
> Is there a way to check if the socket is still running?

You can check `room.connectionState == connectionState `

> Is there a way to check if the room in the livekit is disconnected, remove it completely to open a new connection?

You can listen to the RoomDisconnectedEvent/RoomReconnectedEvent in the event

> I am having 1 problem, when opening livekit connection, the call works normally. But there are cases, when closing the connection fails without disconnecting, it runs in the background. When opening a new connection, the new connection overrides the old connection. livekit keeps saying "Failed connect to server". Unless the app is uninstalled and reinstalled, the livekit will reconnect normally.

This is a should resume-connect/full-reconnect issue, which will be fixed in this PR https://github.com/livekit/client-sdk-flutter/pull/194
