### ISSUE TITLE
[bug][android] Hardware.audioOutputs not listing any bluetooth device

### ISSUE THREAD

**Issue by janoskranczler** [livekit/client-sdk-flutter#208]
Using `Hardware.instance.audioOutputs()` not listing connected bluetooth devices on Android. I've tested it on two different bluetooth headsets without success.

**To Reproduce**
1. Use a physical android device
2. Connect a bluetooth headset (audio output)
3. Check the result of  `Hardware.instance.audioOutputs()` method

**Expected behavior**
The returned device list contains the connected bluetooth device as an audio output. 

**Platform information**

* **Flutter version**:
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0 22A380 darwin-arm, locale en-HU)
    • Flutter version 3.3.8 on channel stable at /Users/janoskranczler/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (3 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
* **Plugin version**: 1.1.7 - https://github.com/livekit/client-sdk-flutter/commit/22a18d3e9cff352c56870aa723567777855bbf2b
* **Flutter target OS**: Android
* **Flutter target OS version**: 12

**Comment by echo-LuGuang** [comment]
Permission is OK
![image](https://user-images.githubusercontent.com/50095011/201611059-10f1d3b6-bad8-4dcf-b71e-66f736081168.png)

The code is as follows
![image](https://user-images.githubusercontent.com/50095011/201611261-9699ee2b-5bfb-4b15-8706-b6f9020f3cdc.png)

log
![image](https://user-images.githubusercontent.com/50095011/201611472-0daa19fe-c87b-408b-ba45-5e5f421b9eef.png)

**Comment by cloudwebrtc** [comment]
hey @janoskranczler.
did some research, and the Bluetooth devices can be listed using the following steps

1，Add the necessary permission tags
```xml
     <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30"/>
     <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
     <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
```

2，add permission_handler to your project
`flutter pub add permission_handler`

3，Request permissions after your app starts for the first time
``` dart
    var status = await Permission.bluetooth.request();
    if (status.isPermanentlyDenied) {
      print('BLEpermdisabled');
    }

    status = await Permission.bluetoothConnect.request();
    if (status.isPermanentlyDenied) {
      print('ConnectPermdisabled');
    }
```

You should then see the bluetooth device
