### ISSUE TITLE
Broadcast a processed video

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#210]
Can the broadcaster broadcast a processed video instead of the video from the camera?

For example, if we want to broadcast an video from the Broadcaster's camera with a logo on one corner, how can we send this resource to the livekit?

**Comment by cloudwebrtc** [comment]
It sounds like it needs to be implemented through insertable streams. This depends on the implementation of flutter-webrtc. This is in the roadmap, and it may be before early 2023. 
another way is using https://github.com/livekit/ingress, you can use Live broadcast software like OBS, preprocess the stream and then use rtmp to publish it to the livekit server.

**Comment by cloudwebrtc** [comment]
If you are on PC, the easiest way is to use OBS virtual camera, mix the camera and text logo and then publish from livekit app.

If it is handled in the livekit SDK, this still depends on the implementation of #201, so close this issue, please track it from another issue
