### ISSUE TITLE
Report reason for signaling connection failure.

### ISSUE THREAD

**Issue by cloudwebrtc** [livekit/client-sdk-flutter#212]
The cloud user reports that the connection failed, but the reason cannot be located from the log, for example, the token expired or invalid. However, the client SDK did not return for these reasons, making it difficult to locate the issues.

**Comment by davidzhao** [comment]
We should call the /rtc/validate HTTP function and return errors from there. JS client does it [here](https://github.com/livekit/client-sdk-js/blob/main/src/api/SignalClient.ts#L213)

**Comment by cloudwebrtc** [comment]
fixed https://github.com/livekit/client-sdk-flutter/pull/214
