### ISSUE TITLE
[bug] ScreenSharing on iOS is not starting (lack of documentation)

### ISSUE THREAD

**Issue by papmodern** [livekit/client-sdk-flutter#216]
I've implemented the code exactly as the documentation and example project. I've also configured flutter_webRTC broadcast extension.

I can successfully share screen without extension and only share the app itself. But nothing happens when I run `publishVideoTrack` based on the example project. 

It seems I need to run some other functions to open screen capture modal in ios, but I have no clue where is it

**Comment by papmodern** [comment]
UPDATE:

So I've tested the example app. It successfully opens ios screen capture modal. But among the options I can't see my extension!

I triple checked all these setups [https://github.com/flutter-webrtc/flutter-webrtc/wiki/iOS-Screen-Sharing](url)

**Comment by papmodern** [comment]
UPDATE:
I fixed the lack of extension among screen capture options. What is not mentioned is that app group should be exactly the same with app bundle identifier with a group at the beginning. Example: 
bundle name: `app.bundle.name`
app group: `group.app.bundle.name`

**Comment by cloudwebrtc** [comment]
thanks, we should add this note to README.

**Comment by papmodern** [comment]
However, I still can't get the shared screen.
It brings screen capture modal, extension is available, I press start recording, after some seconds it resets to start recording again and nothing happens in livekit side!

**Comment by papmodern** [comment]
I tested the example project on other iphone. It seems the problem is only happens on iOS 16.2 Beta

**Comment by mohd-afid** [comment]
@papmodern how to stop screen share from app any idea
