### ISSUE TITLE
flutter web - false positive error message when calling room?.localParticipant?.setMicrophoneEnabled(false)

### ISSUE THREAD

**Issue by WillComesBack** [livekit/client-sdk-flutter#224]
I get this error message in the debug logs everytime i setMicrophoneEnabled(false).
The function works, but the error message is a false positive. We should still handle it though. My suggestion could be to put a try/catch on this part, but you can choose to close this and leave it alone if you think it's wrong
\pub.dartlang.org\livekit_client-1.1.11\lib\src\participant\local.dart
await track.sender?.setTrack(null);

TypeError: o[method] is not a function
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_shared/lib/js_util_patch.dart 105:57       _callMethodUnchecked1
packages/dart_webrtc/src/rtc_rtp_sender_impl.dart 43:16                                                           setTrack
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54   runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5   _async
packages/dart_webrtc/src/rtc_rtp_sender_impl.dart 36:24                                                           setTrack
packages/livekit_client/src/participant/local.dart 330:33                                                         setSourceEnabled
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50   <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1653:54                                 runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 147:18                           handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 766:44                           handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 795:13                           _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 566:5                            [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 639:7                            callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                     _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                      _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15  <fn>

**Comment by davidzhao** [comment]
Which browser are you seeing this with?

**Comment by WillComesBack** [comment]
Chrome Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by davidzhao** [comment]
I'm not seeing this with the latest version on Chrome. I think this is likely a bug that's already been fixed. Are you able to repro with 1.1.12?

**Comment by WillComesBack** [comment]
It says I have the most up to date. It's fine though, I can just surround
the error with a try/catch to bypass it. It's not a real big issue
[image: image.png]

-Will

**Comment by cloudwebrtc** [comment]
It has been fixed in the latest version, and there are no new reports of the same issue.

If the issue reappears, feel free to re-open it.
