### ISSUE TITLE
[bug]运行在Android12上会出现无法找到蓝牙权限导致崩溃

### ISSUE THREAD

**Issue by Poker-J** [livekit/client-sdk-flutter#229]
**Describe the bug**
I/LogContext(19681): [main] uploadCoreByStartService: start upload service, logCategory: mPaaSCrashAndroid, success: true, process: main, disableTools: false, event: maxLogCount
E/MonitorLogger(19681): [main] crash: java.lang.SecurityException: Need BLUETOOTH permission
E/MonitorLogger(19681): 	at android.bluetooth.BluetoothHeadset.<init>(BluetoothHeadset.java:426)
E/MonitorLogger(19681): 	at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java:3144)
E/MonitorLogger(19681): 	at com.twilio.audioswitch.bluetooth.BluetoothHeadsetManager.start(BluetoothHeadsetManager.kt:156)
E/MonitorLogger(19681): 	at com.twilio.audioswitch.AudioSwitch.start(AudioSwitch.kt:160)
E/MonitorLogger(19681): 	at com.cloudwebrtc.webrtc.audio.AudioSwitchManager.lambda$start$2$com-cloudwebrtc-webrtc-audio-AudioSwitchManager(AudioSwitchManager.java:70)
E/MonitorLogger(19681): 	at com.cloudwebrtc.webrtc.audio.AudioSwitchManager<2$>ExternalSyntheticLambda1.run(Unknown Source:2)
E/MonitorLogger(19681): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MonitorLogger(19681): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MonitorLogger(19681): 	at android.os.Looper.loopOnce(Looper.java:210)
E/MonitorLogger(19681): 	at android.os.Looper.loop(Looper.java:299)
E/MonitorLogger(19681): 	at android.app.ActivityThread.main(ActivityThread.java:8118)
E/MonitorLogger(19681): 	at java.lang.reflect.Method.invoke(Native Method)
E/MonitorLogger(19681): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/MonitorLogger(19681): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **Flutter target OS**: 
* **Flutter target OS version**:
* **Flutter console log**:

**Comment by Poker-J** [comment]
@noahlt

**Comment by cloudwebrtc** [comment]
You can try adding the following permission labels

```xml
<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```

**Comment by Poker-J** [comment]
这些权限都是添加到了我的配置清单 问题依然出现 @noahlt

**Comment by Poker-J** [comment]
![image](https://user-images.githubusercontent.com/26270525/210030197-882ba2c3-19b3-4a25-91ff-57a33d05e6dd.png)

**Comment by cloudwebrtc** [comment]
@Poker-J 你截图中的权限可以解决你所遇到的崩溃吗？
我在Android 开发者网站看到类似解决方案.
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher

**Comment by Poker-J** [comment]
问题依旧存在 他只会在Android12的手机上出现

**Comment by cloudwebrtc** [comment]
好的，晚一点我会试试重现问题，另外，你是直接用client-sdk-flutter/example 还是自己创建的 app？这样我可以帮助我复现问题.

**Comment by Poker-J** [comment]
自己的app 但是代码和demo保持一致 我是运行在小米11手机上

**Comment by Poker-J** [comment]
请问有没有沟通交流群提供呢

**Comment by cloudwebrtc** [comment]
你可以加入 slack 频道交流 https://livekit-users.slack.com/join/shared_invite/zt-19nswkhip-4Y56hpIHM94EyWUpRH1GGQ#/shared-invite/email

**Comment by davidzhao** [comment]
this will be resolved with the next release.
