### ISSUE TITLE
(Mac Desktop Bug) EXC_BAD_ACCESS (SIGSEGV) on M1 Mac Studio

### ISSUE THREAD

**Issue by jascodes** [livekit/client-sdk-flutter#230]
Hey @cloudwebrtc 

I am getting crash on my M1 mac studio on the example app.

Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0.1 22A400 darwin-arm, locale en-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
    ! Error: iPhone (60) is busy: Fetching debug symbols for iPhone (60). Xcode will continue when iPhone (60) is finished. (code -10)
[✓] HTTP Host Availability
```

Error Report
[error_report.txt](https://github.com/livekit/client-sdk-flutter/files/10320155/error_report.txt)

**Comment by jascodes** [comment]
Might be releated to this
https://github.com/flutter-webrtc/flutter-webrtc/issues/1016

**Comment by cloudwebrtc** [comment]
From the log, you are using 5K resolution, but it seems that the crashed thread is related to Camera, the crash comes from ` 1 Dispatch queue: org.webrtc.RTCDispatcherCaptureSession`, and it is related to setting the minimum frame rate.

This is a tricky issue, I can't reproduce this error on my computer, there is an idea, if you try to use https://github.com/webrtc-sdk/webrtc@m104_release to compile the debug framework of m1 mac in Native, you should be able to locate the code and line number in libwebrtc at the time of the crash

**Comment by jascodes** [comment]
@cloudwebrtc Thanks for the prompt reply. 
> it is related to setting the minimum frame rate.
I was using OBS, finecam virtual cams on the machine and I also had continuity camera from my iphone hooked in to this M1 machine. I will further inspect to see I can further debug.

I might be also Compiling framework at some point when have more time.

**Comment by davidzhao** [comment]
As discussed in Slack, this issue may be related to virtual cameras

**Comment by jascodes** [comment]
Guys, I test on my mac studio with physical camera. Its still cause the crash. Here I am making sure before connnecting I use physical camera.

Please find below logs.
[glu.txt](https://github.com/livekit/client-sdk-flutter/files/10335663/glu.txt)

@cloudwebrtc

**Comment by cloudwebrtc** [comment]
AVCaptureDALDevice seems to lack a frameRate setting method, the fps of the virtual camera may depend on the OBS output, so I created this PR to skip the setting and it works fine

https://github.com/webrtc-sdk/webrtc/pull/62


<img width="1678" alt="image" src="https://user-images.githubusercontent.com/17733746/218356397-eb8a4339-5811-4a90-8249-e2e1e8d66c10.png">

**Comment by jascodes** [comment]
@cloudwebrtc Awesome mate!! I will tryp and report back.

**Comment by cloudwebrtc** [comment]
I'm recompiling .xframework and publishing new one to cocoapods, and in about an hour I can create a PR to fix this issue.

**Comment by cloudwebrtc** [comment]
@jascodes PR created, https://github.com/livekit/client-sdk-flutter/pull/240
