### ISSUE TITLE
[feature] enable camera and microphone in a single method call

### ISSUE THREAD

**Issue by stefanodefilippo** [livekit/client-sdk-flutter#233]
**Is your feature request related to a problem? Please describe.**
Right now to enable camera and microphone I need to call two different methods: setCameraEnabled and setMicrophoneEnabled. In web browsers (and in mobile app I imagine) this causes a bad user experience because the user sees two different popup one asking camera permission and one asking microphone permission.

**Describe the solution you'd like**
Is it possibile to implement a method that creates audio and video tracks at the same time causing a single permission popup to be shown?

**Comment by hiroshihorie** [comment]
I think the OS will still show 2 permission dialogs separately.
