### ISSUE TITLE
[Question]: Why we are not using `Helper.switchCamera` from flutter webrtc.

### ISSUE THREAD

**Issue by xsahil03x** [livekit/client-sdk-flutter#237]
In the current implementation, we restart the track when we want to [switch](https://github.com/livekit/client-sdk-flutter/blob/main/lib/src/track/local/video.dart#LL107-L117) the camera (front/back). Is there any particular reason we are not using the static helper method [Helper.switchCamera](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/helper.dart#L78-L117) from `flutter_webrtc`?

**Comment by xsahil03x** [comment]
@cloudwebrtc any idea?

**Comment by cloudwebrtc** [comment]
yeah, I think it's worth considering, `Helper.switchCamera` will switch much faster on mobile devices

**Comment by xsahil03x** [comment]
@cloudwebrtc shouldn't the above PR also update the capture options to notify the clients that a deviceId or camera position has been changed?

**Comment by cloudwebrtc** [comment]
hi @xsahil03x ,Do you mean like that?
``` dart
     if (fastSwitch) {
+       currentOptions = options. copyWith(deviceId: deviceId);
       await rtc.Helper.switchCamera(mediaStreamTrack, deviceId, mediaStream);
       return;
     }
 ```

**Comment by xsahil03x** [comment]
@cloudwebrtc yes, something like this. But I'm confused about how to determine the new `cameraPosition` in case the `switchCamera` is called on web with `deviceId`.

**Comment by cloudwebrtc** [comment]
Here is an example [getUserMedia,](https://codepen.io/apalshah/pen/XWdgPEw) to detect whether the web supports `facingMode`. If it supports, `cameraPosition` can be valid. If not, you need to enumerate `mediaDevices` and pass in deviceId to switch video source

**Comment by xsahil03x** [comment]
@cloudwebrtc So, the flow should be something like this

```
FastSwitch -> 
		if (web) -> 
			if (facingModeSupported) -> setFacingMode
			else -> pass the deviceId
		
		else -> Native Call
```

**Comment by xsahil03x** [comment]
Also, do you think we should use the [Helper.setMicrophoneMute](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/lib/src/helper.dart#L136-L152) similarly for the microphone tracks instead of restarting them?
