### ISSUE TITLE
[bug] - iOS only issue - output audio also changes while muting on setMicrophoneEnabled()

### ISSUE THREAD

**Issue by WillComesBack** [livekit/client-sdk-flutter#245]
**Describe the bug**
Using livekit_client: 1.2.0
I have code that will toggle the mute button
`
  Future<bool> toggleMute(bool canToggle) async {
    try {
      await room?.localParticipant?.setMicrophoneEnabled(canToggle);
    } catch (_) {}

    return room?.localParticipant?.isMuted == true;
  }
`
When toggling on iOS devices (physical device), the speaker audio suddenly changes to phone audio. This works fine on web and Android

**To Reproduce**
Use that code as reference to toggle mute/unmute

**Expected behavior**
Only mute my side (which it does)

**Platform information**

* **Flutter version**: 3.3.10
* **Plugin version**: 1.2.0
* **Flutter target OS**: 
* **Flutter target OS version**:
* **Flutter console log**:

**Comment by cloudwebrtc** [comment]
This is a side effect of fixing the mic indicator lighting up after mute, a related answer is here.
https://github.com/livekit/client-sdk-flutter/issues/227#issuecomment-1442047431

**Comment by papmodern** [comment]
@cloudwebrtc @hiroshihorie 
We released another update with the latest version which contains the merge you closed this issue for. But still we are facing the issue. It is mostly happened for the one who created the channel or joined first. I will share you more details after more tests
