### ISSUE TITLE
[bug]Switching mobile network will disconnect

### ISSUE THREAD

**Issue by hrxiang** [livekit/client-sdk-flutter#246]
Switching from wifi to mobile phone 4g or switching from 4g to wifi calls are directly interrupted and cannot be reconnected，
In the new version of sdk, the reconnection method is gone.

在通话的时候切换手机网络，从wifi到4g或从4g到wifi都会中断且直接丢失房间的连接，在1.2.0的sdk里重连方法不见了。

flutter 3.7.3
livekit_client 1.2.0
redmi note5 4g
android 8.1.0

**Comment by cloudwebrtc** [comment]
We may need to monitor current network type, and automatically trigger the re-connection when it changes

**Comment by hrxiang** [comment]
> We may need to monitor the current network type, and automatically trigger the re-connection when it changes

The reconnection method is gone in the new sdk

**Comment by hrxiang** [comment]
Harmonys os 4g  screen freezes


print log :org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full

**Comment by hrxiang** [comment]
Some mobile phones will automatically reconnect when switching networks in debug mode, but they are directly disconnected in release mode

在debug模式下切换网络会自动重连，但是在release模式下直接断开了

**Comment by davidzhao** [comment]
> The reconnection method is gone in the new sdk

What is the reconnection method?

**Comment by hrxiang** [comment]
> > The reconnection method is gone in the new sdk
> 
> What is the reconnection method?

```
 void _onTapReconnect() async {
    try {
      await room?.reconnect();
    } catch (error) {}
  }
```

**Comment by cloudwebrtc** [comment]
okay, I made it an internal method in the last PR, but I think we need to reconnect by monitoring network changes instead of manually reconnecting?
https://github.com/livekit/client-sdk-flutter/pull/238/files

**Comment by cloudwebrtc** [comment]
@hrxiang When calling you to switch networks, can you observe that the signaling ws connection is disconnected? or nothing will happen

**Comment by hrxiang** [comment]
> @hrxiang When you switch networks, can you observe that the signaling ws connection is disconnected? or nothing will happen

There will be reconnection in debug mode, and the release mode will be disconnected directly.


I used the 1.1.4 version to build the release package and it can be reconnected, but I used the 1.2.0 version to build the release package and disconnected directly.

I used the 1.2.0 version to build the debug package can be reconnected

**Comment by cloudwebrtc** [comment]
okay, let me test it

**Comment by cloudwebrtc** [comment]
Just tested, 1.2.0 uses the release mode, it can be reconnected after switching from WIFI to 5G, but the publisher successfully reconnects first, while the subscriber will lag behind for 3 to 5 seconds but will eventually reconnect, and the two-way video will return to normal.

**Comment by hrxiang** [comment]
> Just tested, 1.2.0 uses the release mode, it can be reconnected after switching from WIFI to 5G, but the publisher successfully reconnects first, while the subscriber will lag behind for 3 to 5 seconds but will eventually reconnect, and the two-way video will return to normal.

4g phone.

**Comment by cloudwebrtc** [comment]
same result on 4g network

**Comment by cloudwebrtc** [comment]
But I observed an interesting phenomenon, the disconnection/new connection of ws signaling seen on the livekit-server has the same delay of 3-5 seconds, so this should be related to the delay of iOS sending WS socket disconnection event.

**Comment by hrxiang** [comment]
> But I observed an interesting phenomenon, the disconnection/new connection of ws signaling seen on the livekit-server has the same delay of 3-5 seconds, so this should be related to the delay of iOS sending WS socket disconnection event.

Nova5 pro (Harmonys os 4g) mobile phone has this problem, but gt neo5 5g does not have this problem.

nova5 pro only supports 4G but not 5G

**Comment by cloudwebrtc** [comment]
The current version depends on the disconnection of the WSS signaling to trigger the `RESTARTCONNECT/ResumConnect`, This method relies on the system to report the timeout of the Socket disconnect.

maybe we can adopt a more positive way as the preferred network changes, and actively re-connect,

**Comment by hrxiang** [comment]
Nova5 pro (Harmonys os 4g) mobile phone on the 1.2.0 version, the screen will freeze, but it is normal on <=1.1.4

**Comment by cloudwebrtc** [comment]
Since I do not have a device that can reproduce the Issue,
Can you help REVERT the code in 1.2.0 SDK to test it?
https://github.com/livekit/client-sdk-flutter/commit/5c4761bc7ca2ec28269a49eca2dbe8f129dc4ab0#diff-3a92e05d440158fbb2bd9af33b72cc5aba22adf50ca82f4e824477109fc58f95L309-L313

**Comment by hrxiang** [comment]
So sorry! Our server code here has not been upgraded, we are still using a version from long ago. After updating the servers, we occasionally lose connection when switching networks, most of the time this is normal.

Now there is a problem that the Huawei 4G mobile phone will be stuck after a while, but the sound can be heard


Repeated console output：
```
org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full
org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full
org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full
org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full
org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full
org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full
org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full
org.webrtc.Logging(19744): HardwareVideoEncoder: Dropped frame, encoder queue full
```

Is it the same issue as this one? https://github.com/open-webrtc-toolkit/owt-deps-webrtc/issues/117

**Comment by cloudwebrtc** [comment]
This may be a bug on a specific device, if this issue recurs frequently, please reopen this issue
