### ISSUE TITLE
Microphone getting off in IOS Devices

### ISSUE THREAD

**Issue by sumitanaiya** [livekit/client-sdk-flutter#254]
Hello,
 Currently, I am working on video calling project in a flutter. I have used livekit for video calling. but I am facing one issue between android and IOS video calling if android and IOS users do the first call audio will be fine but if they do the second call android device user  cant get IOS  user’s audio.

recently i noticed that when audio is not coming through in android on IOS devices MICMODE is getting Turned off means microphone is getting turned off .and when audio is coming in IOS devices MICMODE is getting on. like below images
![micOff](https://user-images.githubusercontent.com/96715539/224030957-60dd60e6-59ab-4822-a8a4-f3647b1af84b.jpeg)
![micOn](https://user-images.githubusercontent.com/96715539/224030995-917b9c43-c3fb-4f46-a536-2810f1896a63.jpeg)
.

**Comment by davidzhao** [comment]
@sumitanaiya which version of the flutter SDK are you using?

**Comment by sumitanaiya** [comment]
flutter SDK : Channel stable, 3.7.6.
livekit_client: ^1.2.1
![Screenshot 2023-03-21 at 10 35 48 AM](https://user-images.githubusercontent.com/97216569/226523404-e66de052-945d-4011-a0b6-5f6ec70da5df.png)

**Comment by sumitanaiya** [comment]
flutter SDK : Channel stable, 3.7.6.
livekit_client: ^1.2.1
![IMG_20230321_104159](https://user-images.githubusercontent.com/96715539/226524041-ba7af007-d2af-44a6-a006-3316367387d9.png)

**Comment by tanlongsheng** [comment]
+1
If one of the phones calls
room.localParticipant?.setMicrophoneEnabled(true);
// ......
room.localParticipant?.setMicrophoneEnabled(false);

The other phone calls
room.localParticipant?.setMicrophoneEnabled(true);
Unable to turn on microphone

**Comment by cloudwebrtc** [comment]
No new reports, so close this one
