### ISSUE TITLE
app quit button does'nt work from version 1.1.9 onwards

### ISSUE THREAD

**Issue by AmirhosseinShk** [livekit/client-sdk-flutter#261]
**Describe the bug**
when adding livekit-client as a dependency to our project quit button doesn't work anymore!!!

**To Reproduce**
you can reproduce it with an example project go on pubspec,yaml and change the version of livekit-client from 1.1.7 to 1.1.12 and your exit button for the flutter application doesn't work!

**Expected behavior**
when pressing exit button on the flutter windows application should close app without any problem!

**Platform information**
this issue occurred on Widows, MacOs and Linux

* **Flutter version**:
[√] Flutter (Channel stable, 3.7.5, on Microsoft Windows [Version 10.0.22623.730], locale en-US)
    • Flutter version 3.7.5 on channel stable at D:\Work\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (4 weeks ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = C:/Users/ASUS/AppData/Local/Android/Sdk
    • ANDROID_SDK_ROOT = C:\Users\ASUS\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.1.2
    • Flutter plugin version 70.0.4
    • Dart plugin version 221.5787.37

[√] VS Code, 64-bit edition (version 1.75.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22623.730]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 110.0.5481.178
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.44

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
* **Plugin version**: 1.1.12 to 1.2.1
* **Flutter target OS**: 
* **Flutter target OS version**: windows 11, MacOs 10.15.7 , Ubuntu20
* **Flutter console log**:

**Comment by cloudwebrtc** [comment]
It is related to the working mechanism of this plugin. When we do not set `FlutterWindowClose.setWindowShouldCloseHandler`, the close event will be intercepted by the flutter_window_close plugin, but after the first room is created, the close event interception will be responded to, and the app will be closed after returning true.
https://github.com/livekit/client-sdk-flutter/blob/main/lib/src/support/app_state.dart#L7

related issue.
https://github.com/zonble/flutter_window_close/issues/6

A temporary solution is to add the main function

`FlutterWindowClose.setWindowShouldCloseHandler(() async { return true});`
