### ISSUE TITLE
[iOS only] get the list of output devices in iOS only return speaker and not the earpiece also

### ISSUE THREAD

**Issue by DavidGomezOv** [livekit/client-sdk-flutter#273]
I'm making an app with IP calls, so I'm using the method '**Hardware.instance.enumerateDevices()**' to get all the input/output devices of the phone, then I filter the result with '**outputDevices = devices.where((devices) => devices.kind == 'audiooutput') .toList();**' to only get the output devices, but in iOS this methods only return me the speaker and not the earpiece also.
I'm implementing in this way like the example inside the library. If someone can help me I really appreciate it.
Thank you so much.

**Comment by cloudwebrtc** [comment]
Due to the particularity of iOS audio management, the speaker and earpiece can only be displayed when publish and subscription are enabled at the same time. This is because the iOS audio route allows the selection of audio route when WebRTC native starts AudioUnit.

**Comment by DavidGomezOv** [comment]
How can I enable those parameters?
