### ISSUE TITLE
[bug] deliverDecodedFrame failed

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#274]
**Describe the bug**
A "deliverDecodedFrame failed" error occurs in the logs of the viewer when the broadcaster closes the broadcast. There are no errors in the publisher's logs, this error only occurs in the viewer.

**To Reproduce**
Broadcaster's close codes:
```
await room?.localParticipant?.unpublishAllTracks();
await room?.disconnect();
room?.dispose();
```
**Platform information**

* **Flutter version**: Flutter 3.7.12
* **Plugin version**: Tested livekit_client: ^1.3.0 and 1.2.2
* **Flutter target OS**: Android real device

![1 3 0](https://user-images.githubusercontent.com/92918781/235176703-b7cc26ab-d6ed-44b0-8ff6-8af4e4b87c7b.PNG)

**Comment by cloudwebrtc** [comment]
I'm not sure if it has something to do with empty frames being injected by the server, will investigate

**Comment by cloudwebrtc** [comment]
@furkanKotic Will this issue reproduces on specific devices? I don't reproduce this glitch on android emulator as well as on my Samsung s20u

**Comment by furkanKotic** [comment]
@cloudwebrtc I just tested it with the devices I have.

Oppo CPH2179 : No error appeared
Android emulator : No error appeared
Sony Xperia XA Ultra : No error appeared
Samsung A51 : Error appeared
Samsung S10+ : Error appeared

It's not a serious error, I just wanted to report it because I saw it in the logs.

**Comment by cloudwebrtc** [comment]
I did several tests and couldn't reproduce it on Samsung s20u, xiaomi k40, and huawei pad 5, this may be a device-related bug that we may not be able to fix for now
