### ISSUE TITLE
Facing random  Legging in videocall

### ISSUE THREAD

**Issue by sumitanaiya** [livekit/client-sdk-flutter#275]
Hello all,
  I am using livekit_client flutter SDK for video calling. Livekit_client version is livekit_client: 1.2.1 and livekit_server: 0.15.0. before sometimes it was working fine but from tomorrow we are facing random legging in video calling for 10 to 15 seconds does anybody now why I am facing this legging in video call in android devices.

**Comment by davidzhao** [comment]
please update to the latest version of livekit-server. this version is over a year old.
