### ISSUE TITLE
Local Video Recording

### ISSUE THREAD

**Issue by jtkeyva** [livekit/client-sdk-flutter#276]
**Is your feature request related to a problem? Please describe.**
There is no way to record video locally.

**Describe the solution you'd like**
While on a live stream, ability to record your own camera and store on device. This is useful for live events etc in which you want to be able to manually record at certain times.

**Describe alternatives you've considered**
None

**Additional context**
The camera package allows you to use MLKit etc. A feature is "Add access to the image stream from Dart."
Does this mean video can pass-thru? Could i be integrated with LiveKit?

**Comment by cloudwebrtc** [comment]
related issue https://github.com/livekit/client-sdk-flutter/issues/201

**Comment by davidzhao** [comment]
closed in favor of #201
