### ISSUE TITLE
[bug] Mac OS exception AVCaptureDevice_Tundra setActiveVideoMinFrameDuration:

### ISSUE THREAD

**Issue by statsss** [livekit/client-sdk-flutter#279]
target format 1280x720, fps 30
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureDevice_Tundra setActiveVideoMinFrameDuration:] Not supported - Supported ranges: (
    "<AVFrameRateRange: 0x600003245ee0 30.00 - 30.00 (1000000 / 30000030 - 1000000 / 30000030)>"
), tried to set maxFrameRate to 30.000000 (1 / 30)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff803f857c3 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff803ce5bc3 objc_exception_throw + 48
	2   AVFCapture                          0x00007ff81dd08743 -[AVCaptureDALDevice activeVideoMaxFrameDuration] + 0
	3   flutter_webrtc                      0x0000000106c365e7 -[FlutterWebRTCPlugin(RTCMediaStream) getUserVideo:successCallback:errorCallback:mediaStream:] + 3575
	4   flutter_webrtc                      0x0000000106c37e53 __119-[FlutterWebRTCPlugin(RTCMediaStream) requestAccessForMediaType:constraints:successCallback:errorCallback:mediaStream:]_block_invoke_2 + 355
	5   libdispatch.dylib                   0x00007ff803c8b0cc _dispatch_call_block_and_release + 12
	6   libdispatch.dylib                   0x00007ff803c8c317 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00007ff803c98c78 _dispatch_main_queue_drain + 943
	8   libdispatch.dylib                   0x00007ff803c988bb _dispatch_main_queue_callback_4CF + 31
	9   CoreFoundation                      0x00007ff803f47f17 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	10  CoreFoundation                      0x00007ff803f08fff __CFRunLoopRun + 2771
	11  CoreFoundation                      0x00007ff803f07e6c CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff80cbb65e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff80cbb634a ReceiveNextEventCommon + 594
	14  HIToolbox                           0x00007ff80cbb60e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff806941fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff80694066a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  AppKit                              0x00007ff806932d19 -[NSApplication run] + 586
	18  AppKit                              0x00007ff806906c97 NSApplicationMain + 817
	19  ***.                                  0x00000001064be0a9 main + 9
	20  dyld                                0x000000010cdd052e start + 462
livekit_client: 1.3.0

**Comment by cloudwebrtc** [comment]
ah, Are you using a virtual camera or an external USB camera? This seems to be an issue that has been fixed

**Comment by statsss** [comment]
> ah, Are you using a virtual camera or an external USB camera? This seems to be an issue that has been fixed

integrated camera laptop

**Comment by cloudwebrtc** [comment]
okay, Are there any steps that can reproduce?
