### ISSUE TITLE
[bug] Some broadcasters have no sound

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#280]
**Describe the bug**
Recently, some broadcasters started to have no sound problem. It's like their microphones are turned off but it's not. Viewers do not hear the broadcaster's voice.

Downgrading the livekit_client library from v1.2.2 to v1.2.1 solves the problem.

This issue seems to occur with publishers using Android. Could the fix marked in the image have triggered another problem?
![aa](https://github.com/livekit/client-sdk-flutter/assets/92918781/3f79fe77-e9c3-4af9-8ced-a50dcf5b76d3)

**Platform information**

* **Flutter version**: livekit: 1.4.1
* **Plugin version**: livekit_client : v1.2.2

**Comment by furkanKotic** [comment]
@cloudwebrtc  No need to do anything. When they broadcast, the sound is always muted.

**Comment by cloudwebrtc** [comment]
can you try the last commit of the main branch? And compile again after running `flutter clean`, I did some tests, and this issue did not appear.

**Comment by furkanKotic** [comment]
It didn't change. The sound problem appeared when the user started using v1.3.1.

**Comment by cse9009** [comment]
Broadcasting sound is OK when I used v1.1.12. But when I try to used greater than v1.1.12 some of my broadcasting devices has no output audio sound. I followed the config for Android. My tested two android devices has both Api Level 30 (Redmi and Infinix brand) (Issue found in Redmi mobile). I am unable to find out solution for this yet.

**Comment by cloudwebrtc** [comment]
@cse9009 so the problem is only on some devices right？ not all devices can't broadcast,  because on my Samsung and Xiaomi k40 it seems to work

**Comment by furkanKotic** [comment]
> @cse9009 so the problem is only on some devices right？ not all devices can't broadcast, because on my Samsung and Xiaomi k40 it seems to work

Yes. It's an issue on some devices of some users, not all devices.

**Comment by cse9009** [comment]
How to solve that issue?

**Comment by cloudwebrtc** [comment]
@furkanKotic I just added `Wired Headset` to the label, I don't think it will cause this issue
 https://github.com/flutter-webrtc/flutter-webrtc/pull/1305/files

**Comment by furkanKotic** [comment]
@cloudwebrtc Since the user got this error in versions after v1.2.1, I thought that an Android-related change must have made this, so I suspected the label commit, of course it might not be related to it.

Could another change in flutter-webrtc version 0.9.25 have caused this issue?

**Comment by cloudwebrtc** [comment]
This is the difference 0.9.24 vs 0.9.25, I am also looking for the fault in it
https://github.com/flutter-webrtc/flutter-webrtc/compare/0.9.24...0.9.25

**Comment by cloudwebrtc** [comment]
@cse9009 @furkanKotic, Can you guys try to collect some logs with logcat connected? When the issue reappears, or try to report the model with the problem, I can try to find the same model for testing.

**Comment by cloudwebrtc** [comment]
It looks like getUserMedia failed and failed to open the microphone,  Let me see the relevant modification in our codebase, also, you can check your code, is there any special deviceId set when turning on the microphone? I suspect that the deviceId does not match. When the device list changes, the correct microphone cannot be opened.

**Comment by furkanKotic** [comment]
> It looks like getUserMedia failed and failed to open the microphone

I think so.

I am not specifying any special deviceId. I just use setMicrophoneEnabled function or this parameters in connect : 
```
fastConnectOptions: FastConnectOptions(
        microphone: const TrackOption(enabled: true),
        camera: const TrackOption(enabled: true),
      ),
```

**Comment by cloudwebrtc** [comment]
hey @furkanKotic, I created a fix in this [PR](https://github.com/flutter-webrtc/flutter-webrtc/pull/1363/files), 
can you try to add this override dependency to your flutter project, and do a new round of testing?

```yaml

dependency_overrides:
  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc.git
      ref: fix/issue-for-get-user-audio

```

**Comment by furkanKotic** [comment]
I sent it to one of the users who had the problem. It says the problem is fixed. I found the following log in the previous livekit version of the same user, this log looks like the above log.

```
LiveKit Exception: [TrackPublishException] Failed to publish track
       at Engine.addTrack.<fn>(engine.dart:223)
```

**Comment by cloudwebrtc** [comment]
This may be an issue with the signaling, Waiting for `lk_rtc.SignalResponse_Message.trackPublished` is timed out
https://github.com/livekit/client-sdk-flutter/blob/main/lib/src/core/engine.dart#L223

**Comment by furkanKotic** [comment]
**Xiaomi Redmi Note 11 Pro** The user of this device reported that the problem was not fixed. I think the problem still persists on some devices.

```
LiveKit Exception: [TrackPublishException] Failed to publish track
       at Engine.addTrack.<fn>(engine.dart:223)

```
Below are the device lists that get this log:

![image](https://github.com/livekit/client-sdk-flutter/assets/92918781/7f0e07f3-e2f9-448a-aed1-4a0cfcac2915)
![image](https://github.com/livekit/client-sdk-flutter/assets/92918781/943deaca-5f07-4845-9805-85667a9a043f)

**Comment by furkanKotic** [comment]
> hey @furkanKotic, I created a fix in this [PR](https://github.com/flutter-webrtc/flutter-webrtc/pull/1363/files), can you try to add this override dependency to your flutter project, and do a new round of testing?
> 
> ```yaml
> dependency_overrides:
>   flutter_webrtc:
>     git:
>       url: https://github.com/flutter-webrtc/flutter-webrtc.git
>       ref: fix/issue-for-get-user-audio
> ```

This fix seems to have had a good effect, but it hasn't fully fixed.

**Comment by cloudwebrtc** [comment]
Thanks for the test, I'll check again, can you get some more log context? around

```
LiveKit Exception: [TrackPublishException] Failed to publish track
        at Engine.addTrack.<fn>(engine.dart:223)
```

**Comment by furkanKotic** [comment]
All logs related to livekit in Firebase logs are below. Even though there are logs, some of which are once in 1 person, I wanted to write.

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: LiveKit Exception: [TrackPublishException] Failed to publish track
       at Engine.addTrack.<fn>(engine.dart:223)
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: LiveKit Exception: [ConnectException] Timed out waiting for EnginePeerStateUpdatedEvent
       at Engine.connect.<fn>(engine.dart:152)
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unable to RTCPeerConnection::addTransceiver: addTransceiver(): track is null
       at RTCPeerConnectionNative.addTransceiver(rtc_peerconnection_impl.dart:547)
       at LocalParticipant.publishAudioTrack(local.dart:76)
       at LocalParticipant.rePublishAllTracks(local.dart:302)
       at Room._handlePostReconnect(room.dart:621)
       at Room._setUpEngineListeners.<fn>(room.dart:343)
       at EventsListenable.on.<fn>(event.dart:157)

```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unable to RTCPeerConnection::setRemoteDescription: peerConnectionSetRemoteDescription(): WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: Failed to set remote answer sdp: Called in wrong state: stable
       at RTCPeerConnectionNative.setRemoteDescription(rtc_peerconnection_impl.dart:325)
       at Transport.setRemoteDescription(transport.dart:85)
       at Engine._setUpSignalListeners.<fn>(engine.dart:807)
       at EventsListenable.on.<fn>(event.dart:157)
       at EventsListenable.listen.<fn>.<fn>(event.dart:128)
       at BasicLock.synchronized(basic_lock.dart:33)
       at EventsListenable.listen.<fn>(event.dart:127)
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unable to RTCPeerConnection::getLocalDescription: getLocalDescription(): peerConnection is null
       at RTCPeerConnectionNative.getLocalDescription(rtc_peerconnection_impl.dart:338)
       at Engine.sendSyncState(engine.dart:677)
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unable to getUserMedia: getUserMedia(): DOMException, NotAllowedError
       at MediaDeviceNative.getUserMedia(mediadevices_impl.dart:48)
       at LocalTrack.createStream(local.dart:138)
       at LocalAudioTrack.create(audio.dart:49)
       at LocalParticipant.setSourceEnabled(local.dart:422)
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'Null' is not a subtype of type 'Map<dynamic, dynamic>'
       at RTCDataChannelNative.eventListener(rtc_data_channel_impl.dart:63)
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unable to RTCPeerConnection::addTransceiver: addTransceiver(): track is null
       at RTCPeerConnectionNative.addTransceiver(rtc_peerconnection_impl.dart:547)
       at LocalParticipant.publishVideoTrack(local.dart:181)
       at LocalParticipant.rePublishAllTracks(local.dart:304)
       at Room._handlePostReconnect(room.dart:621)
       at Room._setUpEngineListeners.<fn>(room.dart:343)
       at EventsListenable.on.<fn>(event.dart:157)
```

**Comment by cse9009** [comment]
> > hey @furkanKotic, I created a fix in this [PR](https://github.com/flutter-webrtc/flutter-webrtc/pull/1363/files), can you try to add this override dependency to your flutter project, and do a new round of testing?
> > ```yaml
> > dependency_overrides:
> >   flutter_webrtc:
> >     git:
> >       url: https://github.com/flutter-webrtc/flutter-webrtc.git
> >       ref: fix/issue-for-get-user-audio
> > ```
> 
> This fix seems to have had a good effect, but it hasn't fully fixed.

May be. But it's working on my device now.

**Comment by cloudwebrtc** [comment]
fixed https://github.com/livekit/client-sdk-flutter/releases/tag/v1.3.3

**Comment by std-s** [comment]
Hi, I had the same problem on macOS.  livekit_client: 2.2.0
