### ISSUE TITLE
[bug] no sound on ios browser

### ISSUE THREAD

**Issue by develocode777** [livekit/client-sdk-flutter#282]
**Describe the bug**
There is no sound if using a browser on ios. This doesn't happen with an ios build.
**To Reproduce**
This is reproducible with the example app.
**Expected behavior**
Sound should work in browser too.

**Comment by davidzhao** [comment]
This is due to Safari requirement of requiring user interaction before audio could be played back. A workaround is to require user to click on some UI element first (like a button), before attempting to connect to the Room.

**Comment by develocode777** [comment]
This seems to be the case, but interactions in flutter don't count, how can i get a valid user interaction without dart:html package?

**Comment by develocode777** [comment]
Thanks for fixing this! Will this also work in Safari desktop? Sometimes there is the same problem on this platform too.

**Comment by cloudwebrtc** [comment]
I think the same applies to desktop safari
