### ISSUE TITLE
[bug] GeneratedPluginRegistrant cannot find symbol

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#283]
**Describe the bug**
After upgrading to Flutter 3.10.0, I can't compile to emulator. It extracts apk file but build run doesn't work.

![qq](https://github.com/livekit/client-sdk-flutter/assets/92918781/fdd29ac9-1071-4bd1-bf87-25992cbe9f28)

**Platform information**

* **Flutter version**: Flutter 3.10.0
* **Plugin version**: livekit_client: ^1.3.0
* **Flutter target OS**: Android simulator

**Comment by cloudwebrtc** [comment]
Have you tried running `flutter clean`, it seems to compile correctly on macOS.

<img width="1173" alt="image" src="https://github.com/livekit/client-sdk-flutter/assets/17733746/e78f5247-2223-4952-b2b0-77f688fded0e">

**Comment by furkanKotic** [comment]
flutter clean helped. thanks
