### ISSUE TITLE
[bug] could not publish video: Unable to RTCRtpTransceiver::setCodecPreferences: setCodecPreferences() rtpTransceiverId is null or empty

### ISSUE THREAD

**Issue by AmirhosseinShk** [livekit/client-sdk-flutter#284]
**Describe the bug**
can't publish local video on run example code on Windows.

**To Reproduce**
just download the example code from GitHub and try run it on Windows.

**Expected behavior**
I expected can publish video and work fine and stream my video.

**Platform information**
Window 11

* **Flutter version**: 
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22623.730], locale en-US)
    • Flutter version 3.10.0 on channel stable at D:\Work\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (5 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\ASUS\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_SDK_ROOT = C:\Users\ASUS\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.1.2
    • Flutter plugin version 73.0.1
    • Dart plugin version 221.6103.1

[√] VS Code, 64-bit edition (version 1.75.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM G781B (mobile) • 172.16.121.28:5555 • android-arm64  • Android 13 (API 33)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.22623.730]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 113.0.5672.92
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 113.0.1774.42

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Plugin version**:
1.3.0

**Flutter target OS**: 
Windows 11 [real device]

**Flutter target OS version**:
Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 84a1e904f4 (5 days ago) • 2023-05-09 07:41:44 -0700
Engine • revision d44b5a94c9
Tools • Dart 3.0.0 • DevTools 2.23.1

**Flutter console log**: 
flutter: 10:49:52: LocalVideoTrack#566989920.start()
flutter: 10:49:52: publishVideoTrack publisher: Instance of 'Transport'
flutter: could not publish video: Unable to RTCRtpTransceiver::setCodecPreferences: setCodecPreferences() rtpTransceiverId is null or empty
flutter: 10:49:53: [SignalEvent] Instance of 'SignalParticipantUpdateEvent'
flutter: 10:49:53: [ParticipantEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_F3PQSwyrPBih, identity: userTest), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
flutter: 10:49:53: [RoomEvent] ParticipantPermissionsUpdatedEvent(participant: LocalParticipant(sid: PA_F3PQSwyrPBih, identity: userTest), permissions: Instance of 'ParticipantPermissions'), will notifyListeners()
flutter: 10:49:55: [SignalEvent] Instance of 'SignalConnectionQualityUpdateEvent'
flutter: 10:49:55: [SignalEvent] Instance of 'SignalRoomUpdateEvent'
flutter: 10:49:55: [ParticipantEvent] ParticipantConnectionQualityUpdatedEvent(participant: LocalParticipant(sid: PA_F3PQSwyrPBih, identity: userTest), connectionQuality: ConnectionQuality.excellent), will notifyListeners()
flutter: 10:49:55: [RoomEvent] ParticipantConnectionQualityUpdatedEvent(participant: LocalParticipant(sid: PA_F3PQSwyrPBih, identity: userTest), connectionQuality: ConnectionQuality.excellent), will notifyListeners()
flutter: 10:49:55: [RoomEvent] RoomMetadataChangedEvent(), will notifyListeners()
flutter: 10:50:18: setSourceEnabled(source: TrackSource.microphone, enabled: true)
flutter: 10:50:18: [SignalEvent] Instance of 'SignalLocalTrackPublishedEvent'
flutter: 10:50:18: EventsListener<SignalEvent>#737425783 event was cancelled by func
flutter: 10:50:18: LocalAudioTrack#706506354.start()
flutter: 10:50:18: LocalAudioTrack#706506354.publish()
flutter: 10:50:18: onAudioTrackCountDidChange: local: 1, remote: 0
flutter: 10:50:18: didUpdateSate: AudioTrackState.localOnly
flutter: 10:50:18: [ParticipantEvent] LocalTrackPublishedEvent(participant: LocalParticipant(sid: PA_F3PQSwyrPBih, identity: userTest), publication: LocalTrackPublication<LocalAudioTrack>(sid: TR_AMGWamAiDvyP7u, source: TrackSource.microphone)), will notifyListeners()
flutter: 10:50:18: [RoomEvent] LocalTrackPublishedEvent(participant: LocalParticipant(sid: PA_F3PQSwyrPBih, identity: userTest), publication: LocalTrackPublication<LocalAudioTrack>(sid: TR_AMGWamAiDvyP7u, source: TrackSource.microphone)), will notifyListeners()

**Comment by cloudwebrtc** [comment]
hey @AmirhosseinShk 
If you use a separate example directory and depend on 1.3.0, this issue should appear, but it has been fixed in https://github.com/livekit/client-sdk-flutter/pull/278, you can try to refer to pub Change to git repo
```yaml
   livekit_client:
      git:
        url: https://github.com/livekit/client-sdk-flutter.git
        ref: main
```
we will release 1.3.1 ASAP to fix this bug
