### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Gagandeep1408** [livekit/client-sdk-flutter#288]
Because every version of flutter_web_plugins from sdk depends on js 0.6.4 and connectivity_plus >=4.0.0 depends on js ^0.6.5, flutter_web_plugins from sdk is incompatible with connectivity_plus >=4.0.0.
And because livekit_client >=1.3.1 depends on connectivity_plus ^4.0.0, flutter_web_plugins from sdk is incompatible with livekit_client >=1.3.1.
So, because fadechat depends on livekit_client ^1.3.1 which depends on flutter_web_plugins from sdk, version solving failed.
pub get failed (1; So, because fadechat depends on livekit_client ^1.3.1 which depends on flutter_web_plugins from sdk, version solving failed.)

**Comment by cloudwebrtc** [comment]
Fixed in v1.5.1
