### ISSUE TITLE
Example failed to run on ios simulator

### ISSUE THREAD

**Issue by ichiroadris** [livekit/client-sdk-flutter#29]
Hi there, I am trying to run the example app from the latest main branch but there is an error while compiling for ios simulator. I search the github issues previously and found something almost similar reported before #22 .

The error received was:
```
[!] CocoaPods could not find compatible versions for pod "WebRTC-SDK":
  In snapshot (Podfile.lock):
    WebRTC-SDK (= 92.4515.11)

  In Podfile:
    flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`) was resolved to 0.7.1, which depends on
      WebRTC-SDK (= 92.4515.11)

    livekit_client (from `.symlinks/plugins/livekit_client/ios`) was resolved to 0.5.2, which depends on
      WebRTC-SDK (= 92.4515.10)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `WebRTC-SDK` inside your development pod `livekit_client`.
   You should run `pod update WebRTC-SDK` to apply changes you've made.
```

I have run every command suggested by the error and the same error is still popping up.

Thank you :)

**Comment by ichiroadris** [comment]
Seems like changing the dependency for WebRTC-SDK inside livekit_client podspec to the latest (92.4515.11) allow me to run it properly now.

**Comment by hiroshihorie** [comment]
Hi @ichiroadris thanks for the report, future releases will have more loose constraints to the WebRTC-SDK spec so i think there won't be issues 😁

**Comment by hiroshihorie** [comment]
Hi @ichiroadris I just released 0.5.3 I think there won't be any more issues regarding the podspec. 🙂

**Comment by ichiroadris** [comment]
Hi, great and thank you for the release!

**Comment by davidliu** [comment]
@BenCherif open up a new issue, and copy the error logs.

**Comment by BenCherif** [comment]
@davidliu  thanks for your response  i've resolved by run Flutter clean .
