### ISSUE TITLE
Unable to find Bluetooth output device

### ISSUE THREAD

**Issue by tanlongsheng** [livekit/client-sdk-flutter#292]
Only the input device can be found, not the output device. BLE Bluetooth Headset

![20230529-101759](https://github.com/livekit/client-sdk-flutter/assets/33618734/8d8d7fc4-daa5-4abc-b4d2-a2ea146b09e5)
![20230529-101803](https://github.com/livekit/client-sdk-flutter/assets/33618734/15f439dc-508a-467f-95c9-ca52dfeffca8)

The download is the client-sdk-flutter demo

Platform information

Flutter version: Flutter 3.10.2
Plugin version: livekit_client : 1.3.2
Android version: 12

**Comment by cloudwebrtc** [comment]
hey, you need to make sure you added this permission. And use the latest version of flutter client sdk, this issue has been fixed in 1.3.1.
```xml
 <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```
