### ISSUE TITLE
Crash MacOS  (v.1.3.3)

### ISSUE THREAD

**Issue by afl-dev** [livekit/client-sdk-flutter#296]
Process:               **** [3430]
Path:                  /Users/USER/*/****.app/Contents/MacOS/****
Identifier:           ****
Version:               1.0.0 (1)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-06-06 17:57:45.4604 +0300
OS Version:            macOS 12.5.1 (21G83)
Report Version:        12
Anonymous UUID:        91AC4C8D-5E8F-29DF-6E34-5CE48B6444E7

Time Awake Since Boot: 1600 seconds

System Integrity Protection: disabled

Crashed Thread:        29  Dispatch queue: IncomingVideoStream

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000007fbe33ddce8
Exception Codes:       0x0000000000000001, 0x000007fbe33ddce8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [3430]

VM Region Info: 0x7fbe33ddce8 is not in any region.  Bytes after previous region: 8773087649001  Bytes before following region: 114366969811736
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      VM_ALLOCATE                 13e700000-13e780000    [  512K] rw-/rwx SM=PRV  
--->  GAP OF 0x6ffec761f000 BYTES
      Stack Guard              700005d9f000-700005da0000 [    4K] ---/rwx SM=NUL  

livekit 
release: 1.3.3

Flutter (Channel stable, 3.10.3, on macOS 12.5.1 21G83)
 Xcode - develop for iOS and macOS (Xcode 14.2)

**Comment by statsss** [comment]
Playback technique, the interlocutor turns the camera on/off (multiple times), changes the usb ports of the webcam

**Comment by cloudwebrtc** [comment]
hey @statsss, The crash was changing the usb ports while the camera was still capturing. Or when you turn on the USB camera again after changing the USB ports

**Comment by cloudwebrtc** [comment]
No more reports found, anyone can reproduce, please feel free to re-open
