### ISSUE TITLE
[Question] Share screen with client-sdk-flutter

### ISSUE THREAD

**Issue by jack2992** [livekit/client-sdk-flutter#3]
Hi, master,
I am sharing the screen from using client-sdk-flutter. However, I can't see the screen share from the web client. Can you help me to find the solution to solve it?
Thanks !

**Comment by davidzhao** [comment]
hi @jack2992 we don't currently support this yet. it's on our roadmap though!

**Comment by jack2992** [comment]
> hi @jack2992 we don't currently support this yet. it's on our roadmap though!
Thank you so much. Beside that i also have problem that when i share screen from web client. On mobile i  can't see the screen shared. 

Thanks

**Comment by hiroshihorie** [comment]
@jack2992 Hopefully will get this working soon!

**Comment by hiroshihorie** [comment]
Implemented! Stay tuned for the SDK update! In about a week.

**Comment by jack2992** [comment]
> Implemented! Stay tuned for the SDK update! In about a week.

Great! Thank bro @hiroshihorie

**Comment by hiroshihorie** [comment]
Now screen share should work as expected with **Web** and **Android**, for iOS currently only in-app screen share is possible. (Apple's limitation that a Broadcast Upload Extension is required)

**Comment by jack2992** [comment]
> Now screen share should work as expected with **Web** and **Android**, for iOS currently only in-app screen share is possible. (Apple's limitation that a Broadcast Upload Extension is required)

Awesome! Thanks Bro support
