### ISSUE TITLE
muted mismatch between TrackPublication and its track

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/client-sdk-flutter#30]
When a TrackPublication is muted, I expect it's track to be muted as well

instead I get:
TrackPublication.muted  [true]
TrackPublication.track.muted [false]

if that's a normal behaviour, we would need a better documentation on the purpose of track's muted attribute.

tested on v.0.5.3

**Comment by hiroshihorie** [comment]
Hi @alex-bluetrain , I am planning to match this behavior with our JS SDK 🙂

**Comment by hiroshihorie** [comment]
Hi @alex-bluetrain, changes have been made in the master. Thanks for the report. 🙂
