### ISSUE TITLE
Cannot switch speaker and earpiece mode on iOS

### ISSUE THREAD

**Issue by ly410726** [livekit/client-sdk-flutter#300]
livekit_client: ^1.3.4

@override
  void initState() {
    super.initState();

    Hardware.instance.enumerateDevices().then(_loadDevices);
  }

void _loadDevices(List<MediaDevice> devices) async {
    _audioInputs = devices.where((d) => d.kind == 'audioinput').toList();
    _audioOutputs = devices.where((d) => d.kind == 'audiooutput').toList();
    _videoInputs = devices.where((d) => d.kind == 'videoinput').toList();

    _audioInputs?.forEach((element) {
      LogUtil.v(element.label + '/' +element.deviceId,tag: '_audioInputs');
    });
    _audioOutputs?.forEach((element) {
      LogUtil.v(element.label + '/' +element.deviceId,tag: '_audioOutputs');
    });
    _videoInputs?.forEach((element) {
      LogUtil.v(element.label + '/' +element.deviceId,tag: '_videoInputs');
    });
  }

flutter: _audioInputs v  iPhone 麦克风/Built-In Microphone
flutter: _audioOutputs v  扬声器/Speaker
flutter: _videoInputs v  后置相机/com.apple.avfoundation.avcapturedevice.built-in_video:0
flutter: _videoInputs v  前置相机/com.apple.avfoundation.avcapturedevice.built-in_video:1

In the audio output on the iOS side, only the speaker and no earpiece are found. How can I switch between the speaker and earpiece mode on the iOS side? It is normal on the Android side.

**Comment by cloudwebrtc** [comment]
This is due to the limitations of iOS audio itself. Only when the AudioUnit is in playAndRecord mode (usually during a call), the earpiece and speaker can be switched, otherwise only the earpiece and external audio output can be selected by default

**Comment by ly410726** [comment]
Is it impossible to switch the earpiece on the iOS device, can only use the speaker?

**Comment by ly410726** [comment]
> 这是由于iOS音频本身的限制造成的。只有当AudioUnit在playAndRecord模式时（一般是通话过程中），才能切换听筒和扬声器，否则默认只能选择听筒和外部音频输出

Is it impossible to switch the earpiece on the iOS device, can only use the speaker?

**Comment by cloudwebrtc** [comment]
can you try this branch https://github.com/livekit/client-sdk-flutter/pull/312?
