### ISSUE TITLE
Windows 10 Crash when toggle camera the app another participant

### ISSUE THREAD

**Issue by statsss** [livekit/client-sdk-flutter#304]
Unhandled exception at address 0x00007FFEBDEA41D0 (igd10iumd64.dll) в singledesk.exe: 0xC0000005: access violation while reading at address 0x00000227B4FB3810.

igd10iumd64.dll!00007ffebdea41d0()
igd10iumd64.dll!00007ffebdfdb69a()
igd10iumd64.dll!00007ffebe048ff4()
d3d11.dll!00007ffec58b9db1()
flutter_windows.dll!00007ffe83207970()
flutter_windows.dll!00007ffe8323f2f5()
flutter_windows.dll!00007ffe83240eaf()
flutter_windows.dll!00007ffe8314ed03()
flutter_windows.dll!00007ffe830ed30a()
flutter_windows.dll!00007ffe833a381a()
flutter_windows.dll!00007ffe827cb42c()
flutter_windows.dll!00007ffe827cb295()
flutter_windows.dll!00007ffe827d56e0()
flutter_windows.dll!00007ffe82866ffd()
flutter_windows.dll!00007ffe828716aa()
flutter_windows.dll!00007ffe828714a4()
flutter_windows.dll!00007ffe828712f2()
flutter_windows.dll!00007ffe82cdf3e9()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cdf8a9()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cdf8a9()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cd44bf()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cd44bf()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cd4da0()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cdf8a9()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cdf8a9()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cdf8a9()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cd44bf()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cdf8a9()
flutter_windows.dll!00007ffe82cd5dda()
flutter_windows.dll!00007ffe82cdbf98()
flutter_windows.dll!00007ffe82cd057d()
flutter_windows.dll!00007ffe82ce97b5()
flutter_windows.dll!00007ffe82ce7f36()
flutter_windows.dll!00007ffe82ce7e6a()
flutter_windows.dll!00007ffe82cfc059()
flutter_windows.dll!00007ffe827fa060()
flutter_windows.dll!00007ffe8280340e()
flutter_windows.dll!00007ffe827f9f77()
flutter_windows.dll!00007ffe827fe3b8()
flutter_windows.dll!00007ffe834e000a()
kernel32.dll!00007ffecee67614()
ntdll.dll!00007ffed02e26a1()

Windows 10 x64

livekit
release: 1.3.4

**Comment by cloudwebrtc** [comment]
related issue https://github.com/livekit/client-sdk-flutter/issues/334
