### ISSUE TITLE
linux arm64 crash

### ISSUE THREAD

**Issue by 1056824847** [livekit/client-sdk-flutter#308]
当我运行room.dispose()的时候程序会闪退，有时测试两三次就闪退，有时就十几次才闪退一次
报错代码如下
```sh
corrupted  size vs. prev_size
已放弃  (核心已转储）
 ```

**Comment by cloudwebrtc** [comment]
Do you mean `room.disconnect()`?  `room.onDispose()` is a passive function that is only executed the last time the room is destroyed?

**Comment by 1056824847** [comment]
Sorry, this seems to be the cause of my code problems
