### ISSUE TITLE
[bug]Do not to switch earphone/peakers on IOS

### ISSUE THREAD

**Issue by coder-xb** [livekit/client-sdk-flutter#311]
**Describe the bug**
Hi，I am developing an audio and video call application，but It cannot switch the earpiece/speaker  on IOS
**To Reproduce**
Add a button to control the earpiece/speaker switch in the example，Calling methods ``room.setSpeakerOn(bool)`` and ``Hardware.instance.setSpeakerphoneOn``，but is not working on IOS
**Expected behavior**
Can switch earphones/speakers normally
**Platform information**

* **Flutter version**: Channel stable，3.10.5
* **Plugin version**:  livekit_client: ^1.3.4
* **Flutter target OS**: iOS[real device]
* **Flutter target OS version**: ios 16.5.1

**Comment by cloudwebrtc** [comment]
please try this branch https://github.com/livekit/client-sdk-flutter/pull/312

**Comment by coder-xb** [comment]
Okay，I will try later

**Comment by coder-xb** [comment]
The brance #312 is working for me，Thanks！
