### ISSUE TITLE
audio of screen sharing is not published

### ISSUE THREAD

**Issue by wasif2mehmood** [livekit/client-sdk-flutter#316]
why i cant share the screen share audio just video track is been shared while i have set the parameter of screenshare audio to true

i want to share the audio of video i am screensharing 

flutter

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.22621.1848], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.6.2)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.80.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

pubspec
is same as example

code for screeenshare
    if (lkPlatformIs(PlatformType.iOS)) {
      var track = await LocalVideoTrack.createScreenShareTrack(
        const ScreenShareCaptureOptions(
          useiOSBroadcastExtension: true,
          maxFrameRate: 15.0,
          captureScreenAudio: true,
        ),
      );
      await participant.publishVideoTrack(track);
      return;
    }
    await participant.setScreenShareEnabled(true, captureScreenAudio: true);
  }
same code for windows and other platforms

**Comment by cloudwebrtc** [comment]
Capture screen audio currently only supports chrome desktop browser, it seems not very easy for native especially mobile, we are still looking for a way

**Comment by moham96** [comment]
My project is very much dependant on this, what can we do to help?

**Comment by moham96** [comment]
> Capture screen audio currently only supports chrome desktop browser, it seems not very easy for native/desktop especially mobile, we are still looking for a way

How can I enable it for chrome browser?
I'm not getting an audio track when running `createScreenShareTracksWithAudio`

**Comment by cloudwebrtc** [comment]
You can try to capture a tab with music playing on Chrome instead of the entire Chrome window, for example, open a YouTube page in Chrome.
In addition, Chrome’s screen sharing cannot capture the sound of apps other than Chrome.

**Comment by cloudwebrtc** [comment]
ScreenSelectDialog is only used for desktop, mac/win/linux, and does not support selecting chrome tabs. You can use flutter to build the web app, use chrome to load the web app, and you can select chrome tabs. 

<img width="1039" alt="image" src="https://github.com/livekit/client-sdk-flutter/assets/17733746/2b472786-18fc-4800-a55a-dbca65109fab">

**Comment by anishnag** [comment]
@cloudwebrtc Any update on getting the audio and video track from `createScreenShareTracksWithAudio` for native iOS?
