### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by srnerturk** [livekit/client-sdk-flutter#326]
I'm doing screen broadcasting on an iOS device. I used the sample files below.
https://github.com/livekit/client-sdk-flutter/tree/main/example/ios/LiveKit%20Broadcast%20Extension

 After running for a while, I get an error saying "Domain=RBSAssertionErrorDomain Code=2 "Assertion's invalidation time is in the past" and the application stops. Any idea about this?

**Comment by cloudwebrtc** [comment]
hey @srnerturk, Are there any steps can reproduce this issue?

**Comment by cloudwebrtc** [comment]
No new reports, so close this one
