### ISSUE TITLE
[bug] setSpeakerphoneOn not working

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#327]
**Describe the bug**
Sound output works fine in version 1.3.5, Sound comes from Speaker, it seems to be earpiece by default in version 1.4.0. Sound comes from earpiece.
`Hardware.instance.setSpeakerphoneOn(true);` not working. 
`Hardware.instance.canSwitchSpeakerphone` always returns false.

The example project has the same problem. I think it's a problem with https://github.com/livekit/client-sdk-flutter/pull/312.

**Expected behavior**

The way I want it to work is as follows: If there is a bluetooth headset, the sound should come from here, if not, the should come from the speaker.

**Platform information**

* **Flutter version**: Flutter 3.10.6
* **Plugin version**: livekit_client: ^1.4.0
* **Flutter target OS**: Android

**Comment by furkanKotic** [comment]
@cloudwebrtc 
The `setSpeakerphoneOn `function works now, this problem is solved, but the audio output order is completely messed up.

Previously, when there were wireless headphones, the sound was coming from there, otherwise it was coming from the speaker, if it was not there, the sound was coming from the earpiecer.

Now, if I don't call `setSpeakerphoneOn(true)`, there is never any sound from the speaker, if I set it to true, the bluetooth headset is disabled.

**Comment by cloudwebrtc** [comment]
okay, When you call `setSpeakerphoneOn(false)`, does the sound switch between the earpiece or bluetooth or wired headset correctly? Headphones usually take precedence over earpieces.

**Comment by furkanKotic** [comment]
When I call `setSpeakerphoneOn(false)` it switches to wireless headset.
But if the user doesn't have a headset, it must come from the speaker, so it looks like you need to call` setSpeakerphoneOn(true)` .

Do we call `setSpeakerphoneOn(true)` only when he has no headset? If so, how do we detect that it doesn't have a headset?

**Comment by davidzhao** [comment]
@furkanKotic what if you don't call `setSpeakerphoneOn` ? what is the default behavior in the following cases:

* With headset
* Without headset

**Comment by furkanKotic** [comment]
@davidzhao 

- With headset
The sound is coming from the headset.

- Without headset
The sound is coming from the earphone. not speaker.


1.3.5 version does not have this problem.

**Comment by cloudwebrtc** [comment]
@furkanKotic Can you try this branch?

https://github.com/livekit/client-sdk-flutter/pull/333

**Comment by furkanKotic** [comment]
@cloudwebrtc 
When I try with no headphones plugged in Although `Hardware.instance.canSwitchSpeakerphone` is `true` `Hardware.instance.setSpeakerphoneOn(true);` does not work, the sound continues to come from the earpiece. I couldn't turn on speaker mode. In the previous version, `Hardware.instance.setSpeakerphoneOn(true)` turned on speaker mode.

When I connected and removed the bluetooth headset in the room, the sound started to come from the speaker.

**Comment by cloudwebrtc** [comment]
hey @furkanKotic Let's confirm the perfect switching mode:

Default mode:
speakerPhoneOn = off

Sound output from earpiece (Without headset/Bluetooth)  by default

when Inserting the wired headset or connecting the Bluetooth headset, the sound is output from the headset/Bluetooth

when a wired headset or Bluetooth headset is disconnected sound output from the earpiece

Speaker Mode:
speakerPhoneOn = on

Sound output from SpeakerPhone (Without headset/Bluetooth)  by default

when Inserting the wired headset or connecting the Bluetooth headset, the sound is output from the headset/Bluetooth

when The wired headset or Bluetooth headset is disconnected, and the sound is output from the SpeakerPhone

**Comment by furkanKotic** [comment]
I am trying this branch https://github.com/livekit/client-sdk-flutter/pull/333

Default mode:
speakerPhoneOn = off  (`Hardware.instance.setSpeakerphoneOn(false);`)

Sound output from earpiece (Without headset/Bluetooth) by default  ✓

when Inserting the wired headset or connecting the Bluetooth headset, the sound is output from the headset/Bluetooth ✓

when a wired headset or Bluetooth headset is disconnected sound output from the earpiece **X** (sound output from the speaker)


Speaker Mode:
speakerPhoneOn = on (`Hardware.instance.setSpeakerphoneOn(true);`)

Sound output from SpeakerPhone (Without headset/Bluetooth) by default **X** (sound output from the earpiece)

when Inserting the wired headset or connecting the Bluetooth headset, the sound is output from the headset/Bluetooth ✓

when The wired headset or Bluetooth headset is disconnected, and the sound is output from the SpeakerPhone ✓

**Comment by furkanKotic** [comment]
The way I want it to work is as follows: If there is a bluetooth headset, the sound should come from here, if not, the should come from the speaker. It worked this way until version 1.4.0.

**Comment by cloudwebrtc** [comment]
thanks for testing, Let me check again, it should fix perfectly

**Comment by davidliu** [comment]
@cloudwebrtc the issue stems from this change on flutter-webrtc:

https://github.com/flutter-webrtc/flutter-webrtc/commit/df450267f35b1c4166e6f386c70316d07499992c

The manual `audioManager.setSpeakerphoneOn(_speakerphoneOn);` overrides AudioSwitch's handling. This should be changed to use `audioSwitch.selectDevice` so we don't interfere with AudioSwitch's internal state.

**Comment by cloudwebrtc** [comment]
@davidliu Thanks for finding it, if I change the setSpeakerphoneOn to the following code, Is this code handled properly?

or don't need to expose the setSpeakerphoneOn interface for Android, which way do you prefer? @furkanKotic 

<img width="865" alt="image" src="https://github.com/livekit/client-sdk-flutter/assets/17733746/9f83ac1d-e2ff-4a37-a20e-64eb6b338ea4">

**Comment by furkanKotic** [comment]
@cloudwebrtc I don't understand the question but using setSpeakerphoneOn is not important to me. it works the previous way is enough for me.

**Comment by cloudwebrtc** [comment]
okay, this may be a mistake I made, I want to align setSpeakerphoneOn with the iOS api, maybe in the actual application, only getAvailableAudioDevices, selectedAudioDevice, and selectAudioDevice are needed, right? @furkanKotic

**Comment by furkanKotic** [comment]
We may need it, yes. @cloudwebrtc

**Comment by davidliu** [comment]
@cloudwebrtc to clear the audio output preference, `audioSwitch.selectDevice(null)` should be used to return back to the default preferences. But yeah, removing the `setSpeakerPhoneOn` method for Android and making it iOS only is probably the most clean.

**Comment by cloudwebrtc** [comment]
@furkanKotic Can you please test the latest commit? https://github.com/livekit/client-sdk-flutter/pull/333, It should now revert to the 1.3.5 state.

**Comment by furkanKotic** [comment]
@cloudwebrtc 
my pubspec file
```
  livekit_client:
    git:
      url: https://github.com/livekit/client-sdk-flutter.git
      ref: fix/set-speakerphone-on-but-prefer-bluetooth
```

Error:
![image](https://github.com/livekit/client-sdk-flutter/assets/92918781/4cab901a-3a16-4955-8a7c-d50e7ed2af9b)

**Comment by cloudwebrtc** [comment]
Can you try adding dependency_overrides under pubspec.yaml?

```yaml
  livekit_client:
    git:
      url: https://github.com/livekit/client-sdk-flutter.git
      ref: fix/set-speakerphone-on-but-prefer-bluetooth

dependency_overrides:
   flutter_webrtc:
     git:
       URL: https://github.com/flutter-webrtc/flutter-webrtc.git
       ref: fix/issue-for-audio-device-switch

```

**Comment by furkanKotic** [comment]
@cloudwebrtc I tried that too, it didn't work.

```
Because project depends on flutter_webrtc from git which doesn't exist (Could not find git ref 'fix/issue-for-audio-device-switch' (fatal: ambiguous argument 'fix/issue-for-audio-device-switch': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]')), version solving failed.
```

**Comment by cloudwebrtc** [comment]
okay, this is strange, maybe you can try to clone to local,
```bash
git clone https://github.com/flutter-webrtc/flutter-webrtc.git -b fix/issue-for-audio-device-switch --depth=1
```
```yaml
dependency_overrides:
   flutter_webrtc:
     path: ../flutter-webrtc
```
Or wait for my release 0.9.38, within a day
