### ISSUE TITLE
Facing video freeze issue with latest flutter livekit sdk 

### ISSUE THREAD

**Issue by vishalCelloip** [livekit/client-sdk-flutter#328]
Facing video freeze issue with latest flutter livekit sdk (and lower versions also ), trying to call from some mobile devices (iphones and android) to samsung tablet (galaxy a8) (1 v 1 video call), when mobile devices are in landscape orientation, the video call works perfect but when rotate mobile device to portrait mode then the video(mobile view) on tab is frozen. first i experienced this issue on my app then i tried to test the sdk but the issue persist on sdk too.
Getting below logs sometime only

Steps to reproduce

- In tab a8, Stay in landscape mode only,
- now initiate call from any of this devices while in portrait mode
- when pick up the call from tab, the video is frozen already
-  when rotate mobile device to landscape then video will resume and play properly
- now when rotate mobile device back to portrait then again video is freezing on tab a8

[](https://drive.google.com/file/d/1mSTV3sNy4LjAu97QilwWYKG4jnyCaXaX/view?usp=sharing)

**Comment by cloudwebrtc** [comment]
This can be fixed in the future by disabling the HW codec on specific devices
