### ISSUE TITLE
[bug] Echo problem

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#345]
**Describe the bug**
In version 1.4.3, the speaker hears her own voice again after her voice goes to the other side. This problem occurs on some phones, only the speaker can hear their own voice again.

**To Reproduce**
The example project has the same problem

**Platform information**
* **Flutter version**: Flutter 3.13.1
* **Plugin version**: livekit_client: ^1.4.3
* **Flutter target OS**: Android

**Comment by davidzhao** [comment]
This happens due to the audio mode being set to Media instead of Communication by default. Echo cancellation is not enabled in Media mode.

We'll fix this in the next release (1.5.0)
