### ISSUE TITLE
[bug] Audio output becomes silent after setMicrophoneEnabled(false) on iOS

### ISSUE THREAD

**Issue by davidzhao** [livekit/client-sdk-flutter#351]
**Describe the bug**

Reported in Slack community:

User reports that when setMicrophoneEnabled(false) runs for a participant, they are unable to receive incoming audio and video for a short duration.

**To Reproduce**

1. Connect to room with two clients, both publishing
2. one of the clients (on iOS) calls setMicrophoneEnabled(false)

all audio in the video call is turned off for the user who mutes/unmutes and then when the process is finished everything is back to normal.

**Expected behavior**

Their microphone gets muted, but they are able to receive incoming audio/video in the mean time.

**Platform information**

* **Plugin version**: 1.4.3
* **Flutter target OS**: iOS

**Comment by ibunnybrin** [comment]
Hi, I have a similar problem, perhaps you managed to find a solution?
