### ISSUE TITLE
[bug] SDK: Flutter : Example application automatically disconnects after 5 mins

### ISSUE THREAD

**Issue by umeshmg27** [livekit/client-sdk-flutter#356]
**Describe the bug**
Fluuter SDK example application closes automatically after 5 mins consistently, with disconnect reason being Unknown.

** Flutter Client Logs**
flutter: 15:35:45: [RoomEvent] RoomDisconnectedEvent(DisconnectReason.unknown), will notifyListeners()
flutter: Room disconnected: reason => DisconnectReason.unknown
flutter: res success
flutter: 15:35:45: [SignalClient#493985978] cleanUp()
flutter: 15:35:45: onDisconnected state:ConnectionState.disconnected reason:signal
flutter: 15:35:45: [Engine#709692974] Already disconnected... ClientDisconnectReason.signal
flutter: 15:35:45: [Room#60609780] cleanUp()
flutter: 15:35:45: [Engine#709692974] cleanUp()
flutter: 15:35:45: [SignalClient#493985978] cleanUp()
flutter: 15:35:45: [Engine#709692974] cleanUp()
flutter: 15:35:45: [SignalClient#493985978] cleanUp()

** Server Logs**
Sep 07 10:05:34 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:34.305Z        INFO        livekit        buffer/rtpstats.go:810        received sender report, time warp        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_AMBzLcoBhK3Nbr", "relayed": false, "mime": "audio/red", "layer": 0, "ntp": "2023-09-07 10:05:35.122 +0000 UTC", "rtp": 1120328534, "arrival": "2023-09-07 10:05:34.305158263 +0000 UTC m=+71947.992204687", "ntpDiffSinceLast": 2.865, "rtpDiffSinceLast": 22920, "arrivalDiffSinceLast": 2.866694168, "expectedTimeDiffSinceLast": 0.4775, "packetDrift": "time: 3.261524388s, rtp: 154560, driftSamples: -1993, driftMs: -41.52, sampleRate: 47388.88", "reportDrift": "time: 4m47.993s, rtp: 2348752, driftSamples: -11474912, driftMs: -239060.67, sampleRate: 8155.59", "highestTS": 1118033478, "highestTime": "2023-09-07 10:00:47.488715453 +0000 UTC m=+71661.175761859"}
Sep 07 10:05:37 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:37.656Z        INFO        livekit        buffer/rtpstats.go:810        received sender report, time warp        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_AMBzLcoBhK3Nbr", "relayed": false, "mime": "audio/red", "layer": 0, "ntp": "2023-09-07 10:05:38.475 +0000 UTC", "rtp": 1120355358, "arrival": "2023-09-07 10:05:37.656594841 +0000 UTC m=+71951.343641258", "ntpDiffSinceLast": 3.3529999999999998, "rtpDiffSinceLast": 26824, "arrivalDiffSinceLast": 3.351436571, "expectedTimeDiffSinceLast": 0.5588333333333333, "packetDrift": "time: 3.261524388s, rtp: 154560, driftSamples: -1993, driftMs: -41.52, sampleRate: 47388.88", "reportDrift": "time: 4m51.346s, rtp: 2375576, driftSamples: -11609032, driftMs: -241854.83, sampleRate: 8153.80", "highestTS": 1118033478, "highestTime": "2023-09-07 10:00:47.488715453 +0000 UTC m=+71661.175761859"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.706Z        INFO        livekit        rtc/room.go:663        closing room        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.707Z        INFO        livekit        rtc/participant.go:675        participant closing        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "sendLeave": true, "reason": "ROOM_CLOSE", "isExpectedToResume": false}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.708Z        INFO        livekit        rtc/mediatrackreceiver.go:502        removing all subscribers for mime        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_VCeRaFiFLg2in7", "relayed": false, "mime": "video/H264"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.708Z        INFO        livekit        rtc/mediatrackreceiver.go:502        removing all subscribers for mime        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_AMBzLcoBhK3Nbr", "relayed": false, "mime": "audio/red"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.708Z        INFO        livekit        rtc/participant_signal.go:291        closing signal connection        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "reason": "PARTICIPANT_CLOSE", "connID": "CO_YncyHZsvAEa9"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.709Z        INFO        livekit        service/roommanager.go:114        deleting room state        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.710Z        INFO        livekit        rtc/room.go:265        participant state changed        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "state": "DISCONNECTED", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "oldState": "ACTIVE"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.710Z        INFO        livekit        buffer/buffer.go:330        rtp stats        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_AMBzLcoBhK3Nbr", "relayed": false, "mime": "audio/red", "layer": 0, "direction": "upstream", "stats": "t: Thu Sep  7 10:00:44 UTC 2023|Thu Sep  7 10:05:43 UTC 2023|299.47s, sn: 8529|8690, ep: 162|0.54/s, p: 162|0.54/s, l: 0|0.0/s|0.00%, b: 32686|873.2bps|3240, f: 1|0.0/s / 0|Mon Jan  1 00:00:00 UTC 0001, d: 0|0.00/s, bd: 0|0.0bps|0, pp: 0|0.00/s, bp: 0|0.0bps|0, o: 0, c: 48000, j: 1075(22415.4us)|1128(23507.8us), n:0|0|0|0, pli:0|Mon Jan  1 00:00:00 UTC 0001 / 0|Mon Jan  1 00:00:00 UTC 0001, fir:0|Mon Jan  1 00:00:00 UTC 0001, rtt(ms):0|0, drift(ms):-41.52, sr(Hz):47388.88"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.711Z        INFO        livekit        buffer/buffer.go:330        rtp stats        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_VCeRaFiFLg2in7", "relayed": false, "mime": "video/h264", "layer": 2, "direction": "upstream", "stats": "t: Thu Sep  7 10:00:44 UTC 2023|Thu Sep  7 10:05:43 UTC 2023|299.09s, sn: 25413|191852, ep: 166440|556.50/s, p: 4247|14.20/s, l: 1123|3.8/s|0.67%, b: 331192|8858.8bps|85036, f: 4175|14.0/s / 17|Thu Sep  7 10:05:41 UTC 2023, d: 0|0.00/s, bd: 0|0.0bps|0, pp: 161070|538.54/s, bp: 39301080|1051233.5bps|3221400, o: 69, c: 90000, j: 112(1250.3us)|3782(42025.9us), gh:[5:3, 7:1, 57:1, 4:3, 71:5, 72:1, 1:1, 3:1, 29:1, 69:2, 67:1, 6:2, 68:1, 80:1, 66:1, 70:3], n:5645|0|0|0, pli:0|Mon Jan  1 00:00:00 UTC 0001 / 0|Mon Jan  1 00:00:00 UTC 0001, fir:0|Mon Jan  1 00:00:00 UTC 0001, rtt(ms):0|0, drift(ms):117.02, sr(Hz):90035.21"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.711Z        INFO        livekit        buffer/buffer.go:330        rtp stats        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_VCeRaFiFLg2in7", "relayed": false, "mime": "video/h264", "layer": 0, "direction": "upstream", "stats": "t: Thu Sep  7 10:00:44 UTC 2023|Thu Sep  7 10:05:43 UTC 2023|299.51s, sn: 25413|29962, ep: 4550|15.19/s, p: 4524|15.10/s, l: 0|0.0/s|0.00%, b: 346300|9249.7bps|90588, f: 4495|15.0/s / 19|Thu Sep  7 10:05:41 UTC 2023, d: 3|0.01/s, bd: 1774|47.4bps|68, pp: 26|0.09/s, bp: 6344|169.4bps|520, o: 18, c: 90000, j: 111(1238.1us)|4767(52974.4us), gh:[2:1, 1:13], n:2|0|0|0, pli:0|Mon Jan  1 00:00:00 UTC 0001 / 0|Mon Jan  1 00:00:00 UTC 0001, fir:0|Mon Jan  1 00:00:00 UTC 0001, rtt(ms):0|0, drift(ms):2.47, sr(Hz):90000.74"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.711Z        INFO        livekit        buffer/buffer.go:330        rtp stats        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_VCeRaFiFLg2in7", "relayed": false, "mime": "video/h264", "layer": 1, "direction": "upstream", "stats": "t: Thu Sep  7 10:00:44 UTC 2023|Thu Sep  7 10:05:43 UTC 2023|299.09s, sn: 25413|30610, ep: 5198|17.38/s, p: 5198|17.38/s, l: 0|0.0/s|0.00%, b: 413954|11072.4bps|104068, f: 5161|17.3/s / 18|Thu Sep  7 10:05:41 UTC 2023, d: 2|0.01/s, bd: 122|3.3bps|40, pp: 0|0.00/s, bp: 0|0.0bps|0, o: 18, c: 90000, j: 125(1394.4us)|4403(48927.3us), gh:[1:11, 2:3], n:7|0|0|0, pli:0|Mon Jan  1 00:00:00 UTC 0001 / 0|Mon Jan  1 00:00:00 UTC 0001, fir:0|Mon Jan  1 00:00:00 UTC 0001, rtt(ms):0|0, drift(ms):116.03, sr(Hz):90034.92"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.712Z        INFO        livekit        service/roommanager.go:481        room closed        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.713Z        INFO        livekit        service/rtcservice.go:309        nothing to read from response source        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "connID": "CO_YncyHZsvAEa9"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.713Z        INFO        livekit        rtc/mediatrackreceiver.go:502        removing all subscribers for mime        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_VCeRaFiFLg2in7", "relayed": false, "mime": "video/h264"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.714Z        INFO        livekit        service/rtcservice.go:352        exit ws read loop for closed connection        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "connID": "CO_YncyHZsvAEa9", "wsError": "read tcp 142.93.208.63:7880->117.242.162.77:49897: use of closed network connection"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.714Z        INFO        livekit        service/rtcservice.go:247        finishing WS connection        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "connID": "CO_YncyHZsvAEa9"}
Sep 07 10:05:43 ubuntu-s-1vcpu-1gb-blr1-01 livekit-server[1929]: 2023-09-07T10:05:43.714Z        INFO        livekit        rtc/mediatrackreceiver.go:502        removing all subscribers for mime        {"room": "3df249bd-d3a5-4cae-86af-10eb22ae8a54", "roomID": "RM_EUJH68cDVKHG", "participant": "babaf131-02a0-470e-a088-c3141fce5c9d", "pID": "PA_CkQ9nWJ7kag6", "remote": false, "trackID": "TR_AMBzLcoBhK3Nbr", "relayed": false, "mime": "audio/red"}

**Comment by cloudwebrtc** [comment]
Will it be disconnected if livekit-server is deployed locally?

**Comment by cloudwebrtc** [comment]
This may be a network related issue as I couldn't reproduce it locally, if you know the steps to reproduce please feel free to re-open this issue
