### ISSUE TITLE
CocoaPods could not find compatible versions for pod "livekit_client"

### ISSUE THREAD

**Issue by gettoknowdavid** [livekit/client-sdk-flutter#362]
**Description**
Livekit implementation on Android works well, but when I try to run it on iOS, we run into this error:
```
[!] CocoaPods could not find compatible versions for pod "livekit_client":
  In Podfile:
   livekit_client (from '.symlinks/plugins/livekit_client/ios')

Specs satisfying the 'livekit_client (from '.symlinks/plugins/livekit_client/ios')' dependency were found, but they required a higher minimum deployment target.
```

**Steps To Reproduce**
- Implement Livekit
- Run pod install
- See error

**Additional Context**
I tried changing the minimum deployment target (12.1, 13.6 and even 16.1) but it did not resolve the issue.
How can I solve this?

**Comment by davidzhao** [comment]
try running `pod update`

**Comment by cloudwebrtc** [comment]
This usually requires clearing the pod cache,
Please refer to the steps below

1) Make sure `platform :ios, '12.1'` is in `ios/Podfile`

2) Run the following commands
```
flutter clean
cd ios && rm -rf Pods Podfile.lock && pod cache clean -all && pod deintegrate
cd .. && flutter pub get 
cd ios && pod install --repo-update
cd .. && flutter build ios
```

**Comment by Khanhdtr** [comment]
pod "livekit_client" will conflict with library "livekit_client" from flutter. 
Change "spec.name" in  LiveKitClient.podspec to other name it will work
