### ISSUE TITLE
[bug] App crashes silently on windows when trying to leave only one participant visible

### ISSUE THREAD

**Issue by mateuszfilipek2000** [livekit/client-sdk-flutter#365]
**Describe the bug**
App crashes when trying to leave only one participant visible on the screen (by clicking on the participant). The only OS we've experienced the issue on is Windows, macOS and web work fine.
The crashes are silent, no error is thrown in the console, crashes are not picked up by sentry, the app just closes without any error message.

**To Reproduce**
Open: https://github.com/mateuszfilipek2000/livekit-crash-test/tree/main (which is just a slightly modified example from your repo, with grid and on tap action added on participants, everything else is the same) with few participants in the room (I've tested with the amount of participants ranging from 6 to 40), click on one of the participants name labels to leave only one participant visible on the screen. The app should crash. Sometimes it takes few tries to crash the app, sometimes it crashes on the first try.

**Expected behavior**
The app should not crash, if the app crashes it should throw an error message or at least be picked up by sentry or other error tracking software.

**Platform information**
The crash happens on Windows 10 and Windows 11, I've tested it on multiple windows machines and it always crashes. Specs of machine on video: Lenovo ThinkPad t14, i7-10510U, 16GB RAM, Windows 10 Pro 21H2

* **Flutter version**: 
Crashes happened on 3.10.5, 3.13.3, haven't tested on other versions.
```
[√] Flutter (Channel stable, 3.13.3, on Microsoft Windows [Version 10.0.19044.3086], locale pl-PL)
    • Flutter version 3.13.3 on channel stable at C:\Users\Mateusz Filipek\fvm\versions\3.13.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (11 days ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Mateusz Filipek\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.29)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.33927.289
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code, 64-bit edition (version 1.80.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.3086]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.188
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.31

[√] Network resources
    • All expected network resources are available.

• No issues found!
```
* **Plugin version**:
1.4.3
* **Flutter target OS**: 
Windows 10, Windows 11 (tested on both)
* **Flutter target OS version**:
Windows 10 Pro 21H2
* **Flutter console log**: 
No error is thrown in the console, the app just closes without any error message.

https://github.com/livekit/client-sdk-flutter/assets/43029034/aecde790-d480-4969-a12d-420b1d04a4d0

**Comment by cloudwebrtc** [comment]
hey @mateuszfilipek2000 , can you try this branch https://github.com/livekit/client-sdk-flutter/pull/370?

**Comment by mateuszfilipek2000** [comment]
Hi, thank you for your quick response. I've checked out the version you have provided, and after a quick bit of testing it both on Windows 11 and Windows 10, it seems like the problem is solved; the app no longer crashes. We will be testing it more thoroughly after the new version is released; if anything comes up, I will let you know. Thank you for your help and for the great package!
