### ISSUE TITLE
在新版本中iOS 上无法切换扬声器和听筒模式

### ISSUE THREAD

**Issue by ly410726** [livekit/client-sdk-flutter#366]
livekit_client：^1.3.5

@OverRide
无效 initState() {
super.initState();

Hardware.instance.enumerateDevices().then(_loadDevices);
}

void _loadDevices(列出设备) async {
_audioInputs = devices.where((d) => d.kind == 'audioinput').toList();
_audioOutputs = devices.where((d) => d.kind == 'audiooutput').toList();
_videoInputs = devices.where((d) => d.kind == 'videoinput').toList();

_audioInputs?.forEach((element) {
  LogUtil.v(element.label + '/' +element.deviceId,tag: '_audioInputs');
});
_audioOutputs?.forEach((element) {
  LogUtil.v(element.label + '/' +element.deviceId,tag: '_audioOutputs');
});
_videoInputs?.forEach((element) {
  LogUtil.v(element.label + '/' +element.deviceId,tag: '_videoInputs');
});
}

flutter: _audioInputs v iPhone 麦克风/内置麦克风
flutter: _audioOutputs v 扬声器/扬声器
flutter: _videoInputs v 后置相机/com.apple.avfoundation.avcapturedevice.built-in_video:0
flutter: _videoInputs v 前置相机/com.apple .avfoundation.avcapturedevice.built-in_video:1

iOS端的音频输出中，只有扬声器，没有耳机。iOS端如何切换扬声器和听筒模式？Android端是正常的。

我在3.1.4标签提了这个问题，你们让我切换321分支，但是没有找到312分支，在后来的315版本还是有这个问题

**Comment by cloudwebrtc** [comment]
新版中已经移除了iOS 手动设置input/output 音频设备的功能，最佳方案是让系统自动接管和路由音频输出，而用户仅可以设置是否优先从扬声器输出声音。免提模式或默认设备
