### ISSUE TITLE
Upgrade the versions of pubspec dependent libraries such as http and uuid

### ISSUE THREAD

**Issue by fuxianwei** [livekit/client-sdk-flutter#369]
**Describe the bug**
Please upgrade pubspec dependent libraries such as http and uuid versions, such as http upgrade 1.1 or above, uuid upgrade 4.0.0 or above, because other libraries also rely on their latest versions

**Platform information**

* **Flutter version**: 3.13.3
* **Plugin version**: 1.5.0

**Comment by cloudwebrtc** [comment]
Dependency versions that are too high or too low are a double-edged sword, so the easiest way is to try it in your pubspec.yaml
```yaml
dependency_overrides:
      uuid: any
```
To automatically match the downgrade or upgrade of the pub version

**Comment by cloudwebrtc** [comment]
okay, I just tested it and changed it to `http: '>=0.13.0'`, which is compatible with both versions (0.13.x and 1.x.x).
