### ISSUE TITLE
[feature]Enable audio play at background and lockscreen.

### ISSUE THREAD

**Issue by mhan8796** [livekit/client-sdk-flutter#373]
**Is your feature request related to a problem? Please describe.**

Enable audio play at background when screen is locked and show lock screen widget.

**Describe the solution you'd like**

when screen is locked or app moved to back ground, the room should still be connected and audio should still play. If possible, video should also minimize to a picture in picture video. If screen is locked, then room should still connect and audio should still play. There also should be a lock screen widget.

**Describe alternatives you've considered**

There doesn't need to be audio play pause option on the lock screen widget. Just to make sure it is showing there, reminding users of connecting to the room and playing audio.

**Additional context**

**Comment by cloudwebrtc** [comment]
duplicated https://github.com/livekit/client-sdk-flutter/issues/534
