### ISSUE TITLE
incompatible  web_rtc and collection on version livekit_client: ^1.5.2

### ISSUE THREAD

**Issue by bagusandrewijaya** [livekit/client-sdk-flutter#375]
**Describe the bug**
Because every version of flutter from sdk depends on collection 1.17.0 and flutter_webrtc >=0.9.35 depends on collection ^1.17.1, flutter from sdk is incompatible with flutter_webrtc >=0.9.35.
And because livekit_client >=1.5.1 depends on flutter_webrtc 0.9.45, flutter from sdk is incompatible with livekit_client >=1.5.1.
So, because rsummi depends on both flutter from sdk and livekit_client ^1.5.1, version solving failed.

**Comment by cloudwebrtc** [comment]
I guess you have already solved this issue in Slack community. by deleting the old pub cache and updating flutter SDK to the latest, hope this info can help others

**Comment by bagusandrewijaya** [comment]
i already solve it 

if someone have same issues you can upgrade flutter version to lates version and clean your pub cache

 thanks for helping @cloudwebrtc
