### ISSUE TITLE
[bug] iOS AirPods disconnection

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#376]
**Describe the bug**
When a new participant turns their microphone on or off in the room, all participants are disconnected from their AirPods.
fastConnectOptions values when the participant joins the room:

```
fastConnectOptions: FastConnectOptions(
    microphone: const TrackOption(enabled: false),
    camera: const TrackOption(enabled: false),
),
```

Participant microphone on code:
`room!.localParticipant?.setMicrophoneEnabled(true);`

Participant microphone off code:
`room!.localParticipant?.setMicrophoneEnabled(false);`
or
`room!.localParticipant?.unpublishAllTracks();`

When the participant turns the microphone on, off, or stops broadcasting all tracks, everyone's AirPods connection is disconnected.

**Platform information**

* **Flutter version**: Flutter 3.13.6
* **Plugin version**: livekit_client: ^1.5.2
* **Flutter target OS**: iOS real device

**Comment by furkanKotic** [comment]
This problem started to be reported when I upgraded the livekit_client library from v1.3.5 to v1.5.2. So I think it may be caused by the following commits:
https://github.com/flutter-webrtc/flutter-webrtc/pull/1381

**Comment by davidzhao** [comment]
I'm unable to reproduce this. tried with our example app on iOS 17.

**Comment by damonique-dev** [comment]
Our users are able to reproduce this in our TestFlight app in iOS 16.6.1

**Platform information**
  Flutter version: Flutter 3.13.0
  Plugin version: livekit_client: ^1.5.2

**Comment by afl-dev** [comment]
Additionally, when you turn on the microphone (AirPods), the same thing happens and the sound is played from the speaker

**Comment by furkanKotic** [comment]
@davidzhao @cloudwebrtc This problem is also present in your sample project. While there are users in the room, when a new person enters the room, all people already in the room are disconnected from their AirPods.

**Comment by afl-dev** [comment]
up
