### ISSUE TITLE
[Question] Capturing external screen-share cancel event

### ISSUE THREAD

**Issue by kNoAPP** [livekit/client-sdk-flutter#379]
During screen-share, many browsers (including Chrome) open a secondary dialog box that includes a "Stop sharing" button. When this button is pressed, how do I capture the stop-share event so that I can update the UI accordingly and/or invoke LiveKit's unpublish/dispose operations? My "Stop sharing" button inside the Flutter app that invokes LiveKit's SDK is working great. When I trigger a stop-share from the Flutter app (and LiveKit SDK), it works just fine.

However, stop-sharing triggered from this external Chrome button doesn't unpublish the video/audio track automatically. I am left with a black box local to the sharer and remote-participants see the share-screen freeze. The `TrackUnsubscribedEvent` and `TrackUnpublishedEvent` are NOT called for remote participants even when `ConnectOptions(autoSubscribe: true)`. So how do I handle this button?

![http___localhost_3000 is sharing your screen and audio  10_7_2023 6_44_13 PM](https://github.com/livekit/client-sdk-flutter/assets/23529044/8521ade1-8fc9-48b9-a002-abe94107de24)

**Comment by cloudwebrtc** [comment]
good find, we may need to emit a `ScreenCaptureStopedEvent` by listening to [screenVideoTrack.ended](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event)

**Comment by kNoAPP** [comment]
Your fix works perfectly in my app, thank you!
