### ISSUE TITLE
Screen sharing results in infinite nesting of images.

### ISSUE THREAD

**Issue by std-s** [livekit/client-sdk-flutter#394]
hi,How should this situation be resolved?

Screen sharing results in infinite nesting of images.

![Snipaste_2023-11-01_15-14-25](https://github.com/livekit/client-sdk-flutter/assets/99468005/93b4c48b-b51b-4acc-9914-4b0cbce827cd)

**Comment by wanjm** [comment]
don't show local track, will solve this problem, otherwise it can't be resolved

**Comment by davidzhao** [comment]
@wanjm is right. the mirror effect is caused by your application rendering the screen share itself.
