### ISSUE TITLE
flutter: Could not connect LiveKit Exception: [ConnectException] Timed out waiting for EnginePeerStateUpdatedEvent

### ISSUE THREAD

**Issue by rishu2004** [livekit/client-sdk-flutter#409]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**show in window**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3570], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.8.1)
[√] Android Studio (version 3.6)
[!] Android Studio (version 2021.2)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.84.2)
[√] Connected device (3 available)
[√] Network resources
* **Flutter version**:  3.10.6 
* **Plugin version**:  livekit_client: ^1.2.1
* **Flutter console log**:(flutter: Could not connect LiveKit Exception: [ConnectException] Timed out waiting for EnginePeerStateUpdatedEvent)
![image](https://github.com/livekit/client-sdk-flutter/assets/67889538/fb1db9c5-f137-421c-9495-310e6dbfe960)

**Comment by kapilsharma-gts** [comment]
But this error comes on desktop every time I connect the room and only desktop.

**Comment by cloudwebrtc** [comment]
When encountering this failure, it means that ICE cannot connect normally. Please use the following test page to verify the server connection.

https://livekit.io/connection-test

This exception has been renamed MediaConnectException
https://github.com/livekit/client-sdk-flutter/pull/422
