### ISSUE TITLE
[bug] sourceId not working on window level

### ISSUE THREAD

**Issue by DennisBroennimann** [livekit/client-sdk-flutter#411]
**Describe the bug**
When adding the sourceId of a window to the ScreenShareCaptureOptions, still the full screen is being recorded on MacOS build.

**To Reproduce**

1. List all sources through rtc.desktopCapturer.getSources
2. Get id of any of the listed entries (In the example the id of the first window will be taken)
3. Check published recording

```
final List<rtc.DesktopCapturerSource> desktopSources = await rtc.desktopCapturer.getSources(types: [rtc.SourceType.Window]);

final room = Room(roomOptions: roomOptions);
try {
await room.connect(_endpointUrl, _accessToken);
await room.localParticipant?.setScreenShareEnabled(true);
var track = await LocalVideoTrack.createScreenShareTrack(
  ScreenShareCaptureOptions(
    maxFrameRate: 15.0,
    sourceId: desktopSources.first.id
  ),
);

await room.localParticipant?.publishVideoTrack(track);
```

**Expected behavior**
Only the window of the defined sourceId should be recorded.

**Platform information**
MacOs Sonoma 14.1.1

* **Flutter version**: Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64
* **Plugin version**: livekit_client: ^1.5.3
* **Flutter target OS**: MacOs (Desktop)
* **Flutter target OS version**: 14.0
* **Flutter console log**: 
As to be noted bellow, the correct sourceId is being logged with type window, but still the full screen is being targeted
`2023-11-26 04:53:28.375 digitalsignagereceiverapp[81838:920002] start desktop capture: sourceId: 5026, type: window, fps: 15`

**Comment by cloudwebrtc** [comment]
Just tested it and it works correctly,
Your code seems to have duplicate parts

If you use
```
var track = await LocalVideoTrack.createScreenShareTrack(
   ScreenShareCaptureOptions(
     maxFrameRate: 15.0,
     sourceId: desktopSources.first.id
   ),
);

await room.localParticipant?.publishVideoTrack(track);
```
To publish screen share track, you do not need to run this line
```
await room.localParticipant?.setScreenShareEnabled(true);
```

**Comment by DennisBroennimann** [comment]
Removing setScreenShareEnabled(true) worked. Thanks!
