### ISSUE TITLE
Microphone not working on iOS - On/Off issue

### ISSUE THREAD

**Issue by kapilsharma-gts** [livekit/client-sdk-flutter#414]
Mention that the microphone functionality (specifically on/off) is not functioning as expected on iOS.
Anyone else errors are also not showing If anyone has any reference

livekit_client: ^1.5.3

flutter sdk 3.10.6

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.6 22G120 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.75.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by cloudwebrtc** [comment]
No new reports, so close this one
