### ISSUE TITLE
[bug] [iOS only] When call setMicrophoneEnabled, audio output switched from Headphones to Speaker

### ISSUE THREAD

**Issue by UserJah** [livekit/client-sdk-flutter#424]
**Describe the bug**

1. When I connecting to room with headphones (bluetooth) I hear participants from headphones. But when I call setMicrophoneEnabled(true) audio output automatically switched to speakerphone.
Also, Hardware.instanse.enumerateDevices() return only one audio Input - (speaker)

**To Reproduce**
1. connect to room with headphones (bluetooth)
2. enable microphone

**Expected behavior**

Enable microphone should not switch audio output automatically.

P.S: I'm guessing this may be related to AppleAudioMode. Is there any way to change it?

**Platform information**

* **Flutter version**: 
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.4 22F66 darwin-arm64, locale ru-AE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
* **Plugin version**: 1.5.3
* **Flutter target OS**: iOS
* **Flutter target OS version**:12.1
* **Flutter console log**:

**Comment by cloudwebrtc** [comment]
hey @UserJah, I saw you made some changes in your fork, is it effective?

**Comment by cloudwebrtc** [comment]
What model of Bluetooth headset are you using?
I test air pods pro on iOS and it seems to work as expected
1. Connect air pods
2. Turn off fast connect and connect to the room
3. Sound output from air pods
4. Enable micphone on iOS
5. The sound is not output from the speaker.

**Comment by furkanKotic** [comment]
A similar bug is also present in my users. I'm still waiting for a solution. https://github.com/livekit/client-sdk-flutter/issues/376

**Comment by std-s** [comment]
hi, any solution ?

**Comment by cloudwebrtc** [comment]
fixed https://github.com/livekit/client-sdk-flutter/pull/518
