### ISSUE TITLE
Unable to send data with Flutter SDK

### ISSUE THREAD

**Issue by icxldd** [livekit/client-sdk-flutter#44]
The sent data cannot be received
![image](https://user-images.githubusercontent.com/16592001/144214343-a1428b2f-5436-494f-a9b1-a2b1b95f25c1.png)
![image](https://user-images.githubusercontent.com/16592001/144214583-7a537777-a356-4614-968b-72ac1b64c013.png)

backend log
![image](https://user-images.githubusercontent.com/16592001/144214952-ad206f38-5544-4e0c-be79-bbbca5ef99e5.png)

**Comment by hiroshihorie** [comment]
Hi @icxldd , I will take a look 🙂

**Comment by icxldd** [comment]
> Hi @icxldd , I will take a look 🙂

Thank you. Currently, I am using the server SDK to send data, but the FLUTTER client SDK cannot send and receive data

**Comment by hiroshihorie** [comment]
@icxldd Does other SDK work ? and what platform of Flutter are you trying this on ?

**Comment by icxldd** [comment]
> 

Using only the Flutter SDK , I ran into this problem with Android client and the Web client

**Comment by icxldd** [comment]
The flutter SDK receives data normally,  can't be send。Because the server SDK sends data that can be received

**Comment by davidzhao** [comment]
a user from community is also seeing this issue with Flutter. reopening.
