### ISSUE TITLE
#469 is still occurring on Pixel 7 series

### ISSUE THREAD

**Issue by acgacgacgacg** [livekit/client-sdk-flutter#485]
The original issue #469 solved most android devices except Pixel 7 series.

As I mentioned [here](https://github.com/livekit/client-sdk-flutter/issues/469#issuecomment-1985757535),
we still detected the following crash through crash report.

Google Pixel7, Pixel7a, Pixel7 Pro had this issue.
The crash log is the same as the one I reported here.

 ```
Fatal Exception: java.lang.RuntimeException
Unable to start service de.julianassmann.flutter_background.IsolateHolderService@8212701 with Intent { act=START cmp=com.example.app/de.julianassmann.flutter_background.IsolateHolderService }: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{28e5a1d 21645:com.example.app/u0a129} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media]
```
We do not have a Pixel7 device to reproduce this problem. Can you help us identify the problem?

**Comment by acgacgacgacg** [comment]
We still don't understand why this happened. Other devices like Xperia V encountered the same issue. 
All these devices are Android 14 and our app is compiled with sdk 34.
Temporarily we downgrade the compile sdk to 33.

**Comment by cloudwebrtc** [comment]
Just tested it, Not reproduced on Pixel 7, close the issue now If it happens again, please feel free to open it.
