### ISSUE TITLE
Timed out waiting for PeerConnection to connect, please check your network for ice connectivity

### ISSUE THREAD

**Issue by md-rifatkhan** [livekit/client-sdk-flutter#504]
Every time i try to connect from Chrome Web and Androd `Timed out waiting for PeerConnection to connect, please check your network for ice connectivity`,

even when already connected from Android, and tried to connect with other device got the error in both side,

**Comment by cloudwebrtc** [comment]
Can you try using Chrome desktop to connect to your Android Chrome and capture some console logs?
Open `chrome://inspect/#devices` in Chrome desktop and open your web app by clicking inspect.

Also please provide `flutter doctor` information and the `livekit sdk` version you are using
