### ISSUE TITLE
[bug] Livekit does not work on Firefox browsers anymore

### ISSUE THREAD

**Issue by Arthurius** [livekit/client-sdk-flutter#507]
**Describe the bug**
On Firefox, `await Room.connect` is never finished. It just hangs forever without throwing an exception. On every other browser I've tested it works fine (Chrome, Brave, Safari)
This code was working fine on production before

**To Reproduce**
Try to call `await Room.connect(url, token)` running on a Firefox browser (on a Mac M1)

**Expected behavior**
Room connects and everything works as expected

**Platform information**
Running on a Macbook Pro, M1 Pro. Firefox 125.0.1 (64-bit)

* **Flutter version**:  Flutter version 3.19.6 on channel stable 
* **Plugin version**: livekit_client: ^2.1.3
* **Flutter target OS**: Web - Firefox
* **Flutter target OS version**:  Firefox 125.0.1

**Comment by cloudwebrtc** [comment]
After investigating the issue, it is related to the migration to `package:web`. This is a fix https://github.com/flutter-webrtc/dart-webrtc/releases/tag/1.4.4. You can try to delete `pubspec.lock` under your project and re-run `flutter pub get` to ensure that you have upgraded to `dart-webrtc 1.4.4`.
