### ISSUE TITLE
How to set RTCDegradationPreference ?

### ISSUE THREAD

**Issue by kendo6666** [livekit/client-sdk-flutter#512]
I need to set RTCDegradationPreference to DISABLED。Can it be done in my own APP instead of modifying the SDK code? 

Just like in publishVideoTrack：

```
    if (track.source == TrackSource.screenShareVideo) {
      var sender = track.transceiver!.sender;
      var parameters = sender.parameters;
      parameters.degradationPreference =
          rtc.RTCDegradationPreference.MAINTAIN_RESOLUTION;
      await sender.setParameters(parameters);
    }
```

**Comment by davidzhao** [comment]
disabled is not a valid setting. It's not possible to prevent webrtc from adapting to network conditions. reference: https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/setParameters#degradationpreference
