### ISSUE TITLE
video mute/unmute no longer notifies remote participants

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/client-sdk-flutter#52]
On v0.5.4 when a participant mutes his video, the remote participants don't get the notification event for it.

the last time I've tested, it was working fine, that was on commit 79a2d2070260ea5bbe1d127bfd6d9f1899c1e982 
it broke somewhere between that commit and 0.5.4

**Comment by hiroshihorie** [comment]
Hi @alex-bluetrain ! Thanks for the report I will take a look 🙂

**Comment by hiroshihorie** [comment]
Should be fixed in https://github.com/livekit/client-sdk-flutter/pull/54

**Comment by alex-bluetrain** [comment]
thanks @hiroshihorie but I couldn't test it, [it throws an exception](https://github.com/livekit/client-sdk-flutter/issues/56)
I've tested it with that commit that is supposed to fix it, and also the latest main commit.

**Comment by hiroshihorie** [comment]
There was a issue with web, thanks for the report !
https://github.com/livekit/client-sdk-flutter/commit/b24fad0f3b6ae610ced1b44108d7fa32ca759dd9

**Comment by alex-bluetrain** [comment]
thanks, now that the exception is fixed, I stepped into another issue: no remote video can be seen on android peers, I opened this issue for it https://github.com/livekit/client-sdk-flutter/issues/57

I can't seem to find a stable version of the client-sdk-flutter, the fixes I needed also includes lots of changes from the last few weeks that break the stability from previous versions. I hope we reach a stable version soon 👍

**Comment by davidzhao** [comment]
Thanks Alex, apologies for the recent breakage. We are focused on ensuring stability this week and will cut the next build then.

closing this issue.
