### ISSUE TITLE
[bug] Screen Share on Android target API 34+ crashes with security warning

### ISSUE THREAD

**Issue by kNoAPP** [livekit/client-sdk-flutter#524]
**Describe the bug**
After Android API level 34 ([impacting Android 14](https://apilevels.com/)), screen-share functionality according to the LiveKit documentation results in an app crash event.

```
E/AndroidRuntime(16537): java.lang.RuntimeException: Unable to start service de.julianassmann.flutter_background.IsolateHolderService@ceb8b4b with Intent { act=START cmp=com.remotelegal.astra/de.julianassmann.flutter_background.IsolateHolderService }: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{5ba1ad5 16537:com.remotelegal.astra/u0a549} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media] 
E/AndroidRuntime(16537): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5053)
E/AndroidRuntime(16537): 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
E/AndroidRuntime(16537): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2390)
E/AndroidRuntime(16537): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(16537): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(16537): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(16537): 	at android.app.ActivityThread.main(ActivityThread.java:8501)
E/AndroidRuntime(16537): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16537): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(16537): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
E/AndroidRuntime(16537): Caused by: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{5ba1ad5 16537:com.remotelegal.astra/u0a549} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media] 
```

**To Reproduce**
Set the example app's [build.gradle](https://github.com/livekit/client-sdk-flutter/blob/main/example/android/app/build.gradle#L44) target SDK to 34 or higher (currently 31). This _is reproducible_ despite the changes in https://github.com/livekit/client-sdk-flutter/pull/470.

**Expected behavior**
Android API level 34+ should have instructions documented to fix this issue. Otherwise, a general warning about targeting API 34+ should be added to the documentation.

**Platform information**

* **Flutter version**: 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3593], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.29)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.89.1)
[√] Connected device (4 available)
[√] Network resources

No issues found!
* **Plugin version**: v2.1.5
* **Flutter target OS**: 
Android
* **Flutter target OS version**:
Android API 34+ (equivalent to Android 14)
* **Flutter console log**:

**Comment by kNoAPP** [comment]
Please note, you can work around this issue by using a target of Android API 33.

**Comment by zerowu49** [comment]
To do screenshare on Android, you need [flutter_background](https://pub.dev/packages/flutter_background) package, then you also need to make sure in the AndroidManifest.xml that:
- Add `<service
        android:name="de.julianassmann.flutter_background.IsolateHolderService"
        android:enabled="true"
        android:exported="false"
        android:foregroundServiceType="mediaProjection" /> ` inside of `<application>` and before `<activity>`

- Add `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />`

More detail you could check the code [in this file](https://github.com/livekit/client-sdk-flutter/blob/main/example/android/app/src/main/AndroidManifest.xml)

Hope this helps!

**Comment by kNoAPP** [comment]
> To do screenshare on Android, you need [flutter_background](https://pub.dev/packages/flutter_background) package, then you also need to make sure in the AndroidManifest.xml that:
> 
> * Add `<service android:name="de.julianassmann.flutter_background.IsolateHolderService" android:enabled="true" android:exported="false" android:foregroundServiceType="mediaProjection" /> ` inside of `<application>` and before `<activity>`
> * Add `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" /> <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION" /> <uses-permission android:name="android.permission.WAKE_LOCK" /> <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />`
> 
> More detail you could check the code [in this file](https://github.com/livekit/client-sdk-flutter/blob/main/example/android/app/src/main/AndroidManifest.xml)
> 
> I've tried change the `targetSdkVersion` to 34 and it still works correctly! Hope this helps!

Hi @zerowu49, thanks for the response. I am still able to reproduce this issue in LiveKit's example app as well as my own. I've confirmed that both these bullet points have been followed. I can take video if you'd like.

Please confirm your target device is running Android 14. If you have not updated to 14+, the API level change to 34 won't impact you, and you won't see the broken behavior.

**Comment by kNoAPP** [comment]
Issue still present, but under a different error. Opening a new issue with video.

**Comment by kNoAPP** [comment]
See: https://github.com/livekit/client-sdk-flutter/issues/542
