### ISSUE TITLE
[Question] When can we expect transcription handling in this SDK?

### ISSUE THREAD

**Issue by bmmseven** [livekit/client-sdk-flutter#529]
Hi there,

I noticed the new feature to transcribe audio using Deepgram and other suppliers in conjunction with workers on the server and I would like to use it with Flutter as a client.
Unfortunately, I can't see any implementation of the transcription handling in this SDK.
Are you currently implementing this? When can we expect a release with it?

PS: I could try to implement it myself, but I don't have any experience with protobuf.

**Comment by davidzhao** [comment]
We are working on this. it should be here in a couple of weeks

**Comment by UserJah** [comment]
> We are working on this. it should be here in a couple of weeks

Hello! Do you mean support insertable streams?
