### ISSUE TITLE
[bug] Screen Share on Android target API 34+ crashes (Media projections require a foreground service)

### ISSUE THREAD

**Issue by kNoAPP** [livekit/client-sdk-flutter#542]
**Describe the bug**
After Android API level 34 ([impacting Android 14](https://apilevels.com/)), screen-share functionality according to the LiveKit documentation results in an app crash event. 

**Crash at 3:29 in video.**

https://github.com/livekit/client-sdk-flutter/assets/23529044/2f86b067-45a1-4d89-817e-25cd6692728e

**To Reproduce**
Set the example app's [build.gradle](https://github.com/livekit/client-sdk-flutter/blob/main/example/android/app/build.gradle#L44) target SDK version to 34 or higher (currently 31).

**Expected behavior**
Android API level 34+ should have instructions documented to fix this issue. Otherwise, a general warning about targeting API 34+ should be added to the documentation.

**Platform information**

* **Flutter version**: 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22631.3737], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.29)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.90.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```
* **Plugin version**: v2.2.0
* **Flutter target OS**: 
Android
* **Flutter target OS version**:
Android API 34+ (equivalent to Android 14)
* **Flutter console log**:

**Comment by kNoAPP** [comment]
Related: https://github.com/JulianAssmann/flutter_background/issues/85

**Comment by kNoAPP** [comment]
## Media projection

**Foreground service type to declare in manifest under
android:foregroundServiceType**
mediaProjection

**Permission to declare in your manifest**
[FOREGROUND_SERVICE_MEDIA_PROJECTION](https://developer.android.com/reference/android/Manifest.permission#FOREGROUND_SERVICE_MEDIA_PROJECTION)

**Constant to pass to startForeground()**
[FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION](https://developer.android.com/reference/android/content/pm/ServiceInfo#FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION)

**Runtime prerequisites**
Call the [createScreenCaptureIntent()](https://developer.android.com/reference/android/media/projection/MediaProjectionManager#createScreenCaptureIntent(android.media.projection.MediaProjectionConfig)) method before starting the foreground service. Doing so shows a permission notification to the user; the user must grant the permission before you can create the service.

After you have created the foreground service, you can call [MediaProjectionManager.getMediaProjection()](https://developer.android.com/reference/android/media/projection/MediaProjectionManager#getMediaProjection(int,%20android.content.Intent)).

**Description**
Project content to non-primary display or external device using the [MediaProjection](https://developer.android.com/reference/android/media/projection/MediaProjection) APIs. This content doesn't have to be exclusively media content.

**Alternatives**
To stream media to another device, use the [Google Cast SDK](https://developers.google.com/cast/docs/android_sender).

### See: https://developer.android.com/about/versions/14/changes/fgs-types-required

**Comment by kNoAPP** [comment]
https://github.com/JulianAssmann/flutter_background/blob/master/android/src/main/kotlin/de/julianassmann/flutter_background/IsolateHolderService.kt#L128C9-L128C41

**Comment by iAbdulaziz93** [comment]
Hi, all!

I have the same issue too. I'm using the latest livekit_client package version, and I added the required Android configurations, permissions and service.

flutter_webrtc version is 0.10.8.
**Android 13 and 14.**

**Comment by davidliu** [comment]
Have you followed the [screen sharing instructions](https://github.com/livekit/client-sdk-flutter/tree/f03e0c2cbf42bc2cf17a8f2174e62a577bd3877a?tab=readme-ov-file#android-1), including adding the foreground service type in the service declaration? Calling startForeground without declaring the type will fallback to the service type declared in the manifest, meaning no change is needed in the `flutter_background` package.

**Comment by iAbdulaziz93** [comment]
@davidliu Yeah, I did add the permissions and service to the manifest file.

**Comment by kNoAPP** [comment]
@davidliu I'll give this a quick test here this morning and write back results. Looks promising! Thanks for taking a look at all this!

**Comment by kNoAPP** [comment]
@davidliu 
cc. @cloudwebrtc 

Working amazingly both in the example app and my own. Thank you guys so much. I am super grateful! 🙌
