### ISSUE TITLE
[feature] pinch-to-zoom

### ISSUE THREAD

**Issue by joeriddles** [livekit/client-sdk-flutter#543]
**Is your feature request related to a problem? Please describe.**
The June LiveKit newsletter update announced pinch-to-zoom:
![image](https://github.com/livekit/client-sdk-flutter/assets/19392916/42b0b681-5c54-49e2-b1bd-4312cc203f1a)

**Describe the solution you'd like**
pinch-to-zoom support added to `VideoTrackRenderer`

**Describe alternatives you've considered**

**Additional context**

**Comment by heshheshsiin** [comment]
We really need this feature in the Flutter SDK version.
Basically "Camera Control", ability to zoom in (pinch to zoom) from the streamer.

**Comment by EvertonMJunior** [comment]
A workaround for this is using the [InteractiveViewer widget](https://api.flutter.dev/flutter/widgets/InteractiveViewer-class.html)

**Comment by cloudwebrtc** [comment]
fixed https://github.com/livekit/client-sdk-flutter/pull/658
