### ISSUE TITLE
[feature] Add attributes to Participant class

### ISSUE THREAD

**Issue by ivalkenburg** [livekit/client-sdk-flutter#547]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When issuing a room grant to a participant you can define attributes to the participant (map<string, string>). These attributes are visible on the participant in the web hook participant payload, but do not exist in the flutter participant class, only metadata (string). Is it possible to have these attributes available in participant class as map<string, string>?

**Describe alternatives you've considered**

**Additional context**

**Comment by davidzhao** [comment]
yes, participant attributes is a new feature and it'll be available across all of our SDKs soon

**Comment by bcherry** [comment]
@ivalkenburg this was released in [2.2.2](https://github.com/livekit/client-sdk-flutter/releases/tag/v2.2.2) - let us know if you have any feedback on it
