### ISSUE TITLE
[bug] Actions stop working after second connect attempt to same room flutter livekit client

### ISSUE THREAD

**Issue by RoyMatipa** [livekit/client-sdk-flutter#553]
**Describe the bug**

Hello! When I try to disconnect from a room in my Flutter app, I've noticed that it works the first time, but if you connect again and then try to disconnect a second time, it doesn't do anything and no error is returned. Additionally, other actions like `setCameraEnabled` and `setMicrophoneEnabled` also stop working after the second connection to the same room.

**To Reproduce**

1. Connect to a room.
2. Disconnect from the room.
3. Connect to the same room.
4. Disconnect from the room (This step doesn't work for some reason).
5. Try to use `setCameraEnabled` or `setMicrophoneEnabled` (These actions also stop working SOMETIMES).

**Expected behaviour**

The app should successfully disconnect from the room on the second attempt as it does on the first attempt, and actions like `setCameraEnabled` and `setMicrophoneEnabled` should continue to work.

**Platform information**

* **Flutter version**: 3.22.1
* **Plugin version**: livekit_client: ^2.2.0
* **Flutter target OS**: Android/iOS/Web (Only tested on Android Emulator running android 14 & Samsung Galaxy S22+ running Android 14)
* **Flutter target OS version**: Android 14
* **Flutter console log**:

**Comment by DumbDev168** [comment]
I have the same issue in version 2.2.0. 
In version 2.1.6 it's working fine.
