### ISSUE TITLE
[bug] Audio playback not working on Windows, but works fine in Chrome

### ISSUE THREAD

**Issue by Unbreathable** [livekit/client-sdk-flutter#562]
**Describe the bug**

When I try to use the example app on Windows to play back audio from another example app running in the browser I can not hear anything. I've tested it the other way around and that way it works perfectly fine. The only thing that doesn't work is audio playback in the Windows version of the example app, no matter if that's from a browser or another machine entirely.

The weirdest thing is that it shows audio packets and all that kind of stuff. Even the talking indicator. The only thing it doesn't do is actually play the audio.

**To Reproduce**

1. Download the example app
2. Connect with 2 clients (one in a browser, one on desktop)
3. Turn on the microphone in the browser
4. You will not hear audio on the desktop version

**Expected behavior**

The audio should be played back.

**Platform information**

* **Flutter version**:  3.22.2
* **Plugin version**: 2.2.2
* **Flutter target OS**: Windows
* **Flutter target OS version**: 11

**Comment by cloudwebrtc** [comment]
Hey, I seem to have reproduced the issue when I tried to test it, but I found that the default ouput device of Windows seems to be `steam streaming speakers`, and I can hear the sound when I change it to the real device.

<img width="375" alt="image" src="https://github.com/user-attachments/assets/40fc801f-3259-4c46-b1fe-b9e935aa12e5">

This seems to be related to the Windows default output device policy.

**Comment by Unbreathable** [comment]
Hey, sorry for wasting your time and thanks for always helping me! I'm closing this issue as it was something to do with my PC.

As it turns out there was just an issue with my headphones for whatever reason that prevented them from playing audio. In case anyone ever has these issues and is reading this right now, if you are on Windows 11, go to Settings -> System -> Sound and in the Advanced category you'll find a button for troubleshooting output devices. That's what solved my problem.
