### ISSUE TITLE
[bug] Echo Cancellation does not work

### ISSUE THREAD

**Issue by willsmanley** [livekit/client-sdk-flutter#565]
**Describe the bug**
Echo cancellation does not work

**To Reproduce**
1) clone https://github.com/willsmanley/echo-repro
2) flutter run. it will connect to kitt, but it will feed the output audio back into the mic. kitt will talk to itself.
3) dont use headphones.

**Expected behavior**
Audio output should not backfeed into the mic.

**Platform information**

* **Flutter version**: 3.22.2
* **Plugin version**: 2.2.3
* **Flutter target OS**: ios
* **Flutter target OS version**: 17.4
* **Flutter console log**: n/a

**Comment by willsmanley** [comment]
@davidzhao is this a known issue? any help would be appreciated :)

**Comment by willsmanley** [comment]
@cloudwebrtc just wanted to check if you have seen this before? i think you probably don't work with the agents stuff as much, but i do believe this is still a flutter-side echo cancellation issue since the echo does not occur with JS client.

im happy to help investigate if you are able to point me to where the underlying logic lives. should i be looking in pion?

**Comment by davidzhao** [comment]
are you testing on a physical device? if so which iPhone model?

**Comment by willsmanley** [comment]
i was on a simulator which turns out to be a problem. works totally fine on physical device. closing now, thanks!

**Comment by willsmanley** [comment]
it would be cool if echo cancellation worked on the simulator but headphones are no problem for development

**Comment by APPXOTICA** [comment]
Echo cancellation does not work on Android devices - Samsung Galaxy S22, Redmi Note 12. But it works great on iOS devices. 
Is there any way to enable WebRTC’s software AEC?

```
  Future<void> _prepareRoom() async {
    final devices = await rtc.navigator.mediaDevices.enumerateDevices();
    final mic = devices.firstWhere((device) => device.kind == _audioInput);

    _room = Room(
      roomOptions: RoomOptions(
        defaultAudioCaptureOptions: AudioCaptureOptions(
          deviceId: mic.deviceId,
          noiseSuppression: true,
          echoCancellation: true,
          autoGainControl: true,
          highPassFilter: true,
          typingNoiseDetection: false,
        ),
      ),
    );
  }

  Future<void> connect() async {
    ...
    await _room?.connect(
      livekitUrl,
      _token!,
    );
    _room?.localParticipant?.setMicrophoneEnabled(true);
    ....
  }
```
