### ISSUE TITLE
[bug] Flutter v3.24.0 Android build failure (android:attr/lStar not found)

### ISSUE THREAD

**Issue by kNoAPP** [livekit/client-sdk-flutter#569]
**Describe the bug**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':livekit_client:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/client-sdk-flutter/example/build/livekit_client/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

**To Reproduce**
Upgrade to Flutter v3.24.0. Build the example app on Android on release mode.

**Expected behavior**
Android should build.

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **Flutter target OS**: 
* **Flutter target OS version**:
* **Flutter console log**:

**Comment by sayasong** [comment]
how to reslove this? thanks

**Comment by flavio20002** [comment]
Same here!

**Comment by rambozzang** [comment]
Same here! other package!

**Comment by erdemyerebasmaz** [comment]
Same here, different package. 

Forking and upgrading Kotlin to latest on the problematic package didn't fix the issue.

`flutter run` works as expected but `flutter build` fails.

**Comment by cloudwebrtc** [comment]
After several hours of investigation, the issue is still not solved. It is recommended to roll back the flutter sdk to the previous version.

**Comment by erdemyerebasmaz** [comment]
Adding this workaround on my `android/build.gradle` has resolved the issue for me.

```gradle
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
}
```

**Comment by lucasjinreal** [comment]
Tempory solved by this:

```
subprojects {
     afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}
```

**Comment by mahmoud25081983** [comment]
> Adding this workaround on our `android/build.gradle` has resolved the issue for us.
> 
> ```groovy-gradle
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>                 buildToolsVersion "34.0.0"
>             }
>         }
>     }
> }
> ```
> 
> but we're holding off on upgrading to Flutter 3.24 and sticking with 3.22.3 until there's an official update on the issue, as we're not confident that this workaround is generally applicable.
> 
> Use at your own discretion and don't forget to remove it when the issue is officially resolved.

where ti add the above code plz???

**Comment by dickverweij** [comment]
> Adding this workaround on our `android/build.gradle` has resolved the issue for us.
> 
> ```groovy-gradle
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>                 buildToolsVersion "34.0.0"
>             }
>         }
>     }
> }
> ```
> 
> but we're holding off on upgrading to Flutter 3.24 and sticking with 3.22.3 until there's an official update on the issue, as we're not confident that this workaround is generally applicable.
> 
> Use at your own discretion and don't forget to remove it when the issue is officially resolved.
Then we get  this error:

Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.

![image](https://github.com/user-attachments/assets/48ab1b49-e76c-4024-8d33-50086da9be39)

**Comment by erdemyerebasmaz** [comment]
> > Adding this workaround on our `android/build.gradle` has resolved the issue for us.
> > ```
> > subprojects {
> >     afterEvaluate { project ->
> >         if (project.plugins.hasPlugin("com.android.application") ||
> >                 project.plugins.hasPlugin("com.android.library")) {
> >             project.android {
> >                 compileSdkVersion 34
> >                 buildToolsVersion "34.0.0"
> >             }
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but we're holding off on upgrading to Flutter 3.24 and sticking with 3.22.3 until there's an official update on the issue, as we're not confident that this workaround is generally applicable.
> > Use at your own discretion and don't forget to remove it when the issue is officially resolved.
> 
> after adding this, then we get this error:
> 
> Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.
> 
> ![image](https://private-user-images.githubusercontent.com/8133838/357084519-48ab1b49-e76c-4024-8d33-50086da9be39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzQ0OTYsIm5iZiI6MTcyMzQ3NDE5NiwicGF0aCI6Ii84MTMzODM4LzM1NzA4NDUxOS00OGFiMWI0OS1lNzZjLTQwMjQtOGQzMy01MDA4NmRhOWJlMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMTQ0OTU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA1ZmIyMjQ0Y2JlMzBlYjg3MTBhMzE2NWQ5NWQzZmY4ZDNlZGU2OTZiZjAwZTU4ZTM2ZjM2NTIwYjczZTllNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.drfxPqBLsB_PBu6Qq4E7r9obbSaLBBxN_eWQIU7poMo)

See https://github.com/livekit/client-sdk-flutter/issues/569#issuecomment-2278271902

**Comment by makstheimba** [comment]
Same issue. Experiencing this only with apk release build. appbundle release build and debug builds work fine.

Have tried all suggestions from this stackoverflow thread to no success - https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found

**Comment by viveeeeeek** [comment]
> Adding this workaround on our `android/build.gradle` has resolved the issue for us.
> 
> ```groovy-gradle
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>                 buildToolsVersion "34.0.0"
>             }
>         }
>     }
> }
> ```
> 
> but we're holding off on upgrading to Flutter 3.24 and sticking with 3.22.3 until there's an official update on the issue, as we're not confident that this workaround is generally applicable.
> 
> Use at your own discretion and don't forget to remove it when the issue is officially resolved.

temporarily solved using this. Thanks!

**Comment by CodeDeveloper19** [comment]
> Adding this workaround on our `android/build.gradle` has resolved the issue for us.
> 
> ```groovy-gradle
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>                 buildToolsVersion "34.0.0"
>             }
>         }
>     }
> }
> ```
> 
> but we're holding off on upgrading to Flutter 3.24 and sticking with 3.22.3 until there's an official update on the issue, as we're not confident that this workaround is generally applicable.
> 
> Use at your own discretion and don't forget to remove it when the issue is officially resolved.

Thanks!!! You made my day

**Comment by abtpltd** [comment]
#Works for me
#android/gradle file code

buildscript { 
    ext {
        kotlin_version = '1.9.0'
        compileSdkVersion = 34
        targetSdkVersion = 34
        minSdkVersion = 21
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        // classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
![image](https://github.com/user-attachments/assets/9ed5d791-9aa2-40a0-a18b-741b61c54eb6)

**Comment by ps6067966** [comment]
Facing same issue.

**Comment by ALouTAYssF** [comment]
This is work for me
on android/build.gradle
buildscript {
    ext {
        kotlin_version = '2.0.10'
        compileSdkVersion = 34
        targetSdkVersion = 34
        minSdkVersion = 21
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

**Comment by The-Funk** [comment]
For all those still facing this issue, make sure to do a flutter clean after making the requisite change to the build.gradle file

**Comment by davidliu** [comment]
I'm going to close this issue, since we don't use this attribute, and we don't force using 3.24.0 in this library or flutter-webrtc. There's not really anything actionable for us to do here, since it seems like a flutter issue.

If you're still running into this, check out the main flutter repo issues here:

https://github.com/flutter/flutter/issues/153668

https://github.com/flutter/flutter/issues/153281

**Comment by kNoAPP** [comment]
@davidliu I kindly request that you'd reopen this issue since there's an actionable item on LiveKit's part that resolves the issue:

Response from Flutter Team regarding this issue: https://github.com/flutter/flutter/issues/153281#issuecomment-2292201697

After applying this solution, my builds are working and this warning log is generated:
```
Warning: Overriding compileSdk version in Flutter plugin: livekit_client from 30 to 31 (to work around https://issuetracker.google.com/issues/199180389).
If there is not a new version of livekit_client, consider filing an issue against livekit_client to increase their compileSdk to the latest (otherwise try updating to the latest version).
```

It would then seem https://github.com/livekit/client-sdk-flutter/blob/main/android/build.gradle#L28 needs to be updated from `30` to `31`.

**Comment by Richard-Van-Intania** [comment]
3.24.3 still here

**Comment by jesdav18** [comment]
> Adding this workaround on our `android/build.gradle` has resolved the issue for us.
> 
> ```groovy-gradle
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>                 buildToolsVersion "34.0.0"
>             }
>         }
>     }
> }
> ```
> 
> but we're holding off on upgrading to Flutter 3.24 and sticking with 3.22.3 until there's an official update on the issue, as we're not confident that this workaround is generally applicable.
> 
> Use at your own discretion and don't forget to remove it when the issue is officially resolved.


I confirm that it worked for me, I will be waiting to delete it as soon as it is solved in a future version

**Comment by MajdSallora** [comment]
@erdemyerebasmaz you  saved my life

**Comment by OnClickListener2048** [comment]
same here

**Comment by kazimasum07** [comment]
i have faced the same issue. then i solved it by adding 
`subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
                buildToolsVersion "34.0.0"
            }
        }
    }
}`
at the middle on **android/build.gradle** .
if there is any update or solutions to this issue please leave a comment

**Comment by Monday1908** [comment]
> Adding this workaround on our `android/build.gradle` has resolved the issue for us.
> 
> ```groovy-gradle
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>                 buildToolsVersion "34.0.0"
>             }
>         }
>     }
> }
> ```
> 
> but we're holding off on upgrading to Flutter 3.24 and sticking with 3.22.3 until there's an official update on the issue, as we're not confident that this workaround is generally applicable.
> 
> Use at your own discretion and don't forget to remove it when the issue is officially resolved.

**Comment by pamafe1976** [comment]
Hi.
Why was this issue closed?
Is the workaround the final solution?

**Comment by ibrahim135** [comment]
Hi
Any update on the official update on the fix?

**Comment by thorizer** [comment]
> Adding this workaround on our `android/build.gradle` has resolved the issue for us.
> 
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>                 buildToolsVersion "34.0.0"
>             }
>         }
>     }
> }


* What went wrong:
Cannot run Project.afterEvaluate(Action) when the project is already evaluated.

**Comment by edilson14** [comment]
> if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>                 buildToolsVersion "34.0.0"
>             }

save my life 😄

**Comment by lvqibin123** [comment]
Should the build.gradle.kts file be configured?
