### ISSUE TITLE
android: example app doesn't show remote participants video track

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/client-sdk-flutter#57]
when running the example app in android, the remote participants can be heard but not seen.
the remote video track appears as if it was muted.

even if the remote participant mutes/unmutes his video or switches camera, it's never seen on the android app.

btw, the chrome version of the app can see the android video stream without problem.

this was tested on 
client-sdk-flutter commit 28e7091325f6a692948037940065d02187a1dbb1
livekit-server commit c00d799ac6ebcfbdf32b48c886801f968a4e62c6

**Comment by hiroshihorie** [comment]
I found why this is happening, thinking what's the best solution now.
