### ISSUE TITLE
[Docs] - Remember the framework/language selection across examples and pages

### ISSUE THREAD

**Issue by matthew-carroll** [livekit/client-sdk-flutter#575]
The Livekit docs include many code examples - sometimes multiple examples per page. Each example includes tabs to select between different languages (server), or application toolkits (client). 

<img width="817" alt="Screenshot 2024-08-15 at 10 29 38 PM" src="https://github.com/user-attachments/assets/9de6e9ed-a44f-4381-b5d1-841e2e63ea27">

It would make it easier to move through and use the documentation if these selections were global, instead of local.

I find myself repeatedly selecting the "Flutter" tab every time I come across a code sample. I'd prefer to select the language and/or application toolkit at a site-wide level. Furthermore, it seems unlikely that most developers are mixing and matching languages and application toolkits during the same session of reading the Livekit docs.

**Comment by bcherry** [comment]
@matthew-carroll thanks for the suggestion - you're absolutely right and this is a great idea. We're discussing adding this with a URL hash parameter (e.g. `#lang=flutter`) but don't have a specific timeline for rolling it out on the docs site yet.

**Comment by matthew-carroll** [comment]
Thanks @bcherry - BTW, a tangent, if you'd like any help with your Flutter integration, please let me know. I run the Flutter Bounty Hunters where we work exclusively on OSS for Flutter and Dart: flutterbountyhunters.com 

And before I file some additional tickets, are you guys already aware that your code to get started with Go on the server has some references that don't compile, and some other similar issues when trying to follow the example code? If so, I won't worry about it. If not, I'll file some additional tickets for that.

**Comment by bcherry** [comment]
@matthew-carroll thank you! A week or two ago we found and corrected some issues in one our Go samples but haven't done a thorough review - can you link me to the ones you've found? We definitely want to fix them!

**Comment by bcherry** [comment]
(I'm also closing this issue on the code tabs - it's on the list for our docs team across the board)
