### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Rioland** [livekit/client-sdk-flutter#579]
**
Failed to build iOS app
Swift Compiler Error (Xcode): Value of optional type '(any StorageProvider)?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider'
/Users/cleaques_sys1/Documents/cleaques/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:72:11

Swift Compiler Error (Xcode): Value of optional type '(any StorageProvider)?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider'
/Users/cleaques_sys1/Documents/cleaques/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:87:11

Swift Compiler Error (Xcode): Cannot assign value of type '(any AuthInterop)?' to type 'any AuthInterop'
/Users/cleaques_sys1/Documents/cleaques/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:290:38

Swift Compiler Error (Xcode): Cannot assign value of type '(any AppCheckInterop)?' to type 'any AppCheckInterop'
/Users/cleaques_sys1/Documents/cleaques/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:292:46

**

**
FirebaseStorage
**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **Flutter target OS**: 
* *
* ios
* Android
* *:
* **Flutter console log**:

**Comment by davidzhao** [comment]
This is Firebase, unrelated to livekit
