### ISSUE TITLE
[bug]How to obtain local and remote audio raw data？Or is there a way to directly get the Fourier transform data of the audio？

### ISSUE THREAD

**Issue by yue001** [livekit/client-sdk-flutter#581]
We are developing an AI voice app. This client SDK is so great and also a good choice for integration into our project. Our project has some cool sound effects, but I found that this SDK does not support any interface that I can get local and remote audio data with. I wonder if I have not found a way works out on this? If this feature is not available now, is there any chance  to schedule it?

Thanks.

**Comment by cloudwebrtc** [comment]
duplicate https://github.com/livekit/client-sdk-flutter/issues/201
