### ISSUE TITLE
Exiting from Room often causes an exception

### ISSUE THREAD

**Issue by hiroshihorie** [livekit/client-sdk-flutter#6]

**Comment by hiroshihorie** [comment]
Should be fixed with f463ffd14ea7f41da9afdfe203ae9590c6a99c28 but needs more testing.

**Comment by jack2992** [comment]
> Should be fixed with [f463ffd](https://github.com/livekit/client-sdk-flutter/commit/f463ffd14ea7f41da9afdfe203ae9590c6a99c28) but needs more testing.

Nice, The same issue. I'well support you testing on this case

**Comment by hiroshihorie** [comment]
@jack2992 fixing a whole bunch of issues!

**Comment by jack2992** [comment]
> @jack2992 fixing a whole bunch of issues!

hi @hiroshihorie 
I have try commit [f463ffd](https://github.com/livekit/client-sdk-flutter/commit/f463ffd14ea7f41da9afdfe203ae9590c6a99c28) . Bug fixed

Thanks !

**Comment by hiroshihorie** [comment]
@jack2992 Thanks for trying it out but there might will be more changes before the official release.

**Comment by jack2992** [comment]
> @jack2992 Thanks for trying it out but there might will be more changes before the official release!

Great, hope it work smoothly
Thank Bro @hiroshihorie
