### ISSUE TITLE
Permission Doesn't work in macOS 

### ISSUE THREAD

**Issue by aryan1107** [livekit/client-sdk-flutter#600]
I don't think `setMicrophoneEnabled(true); `  works for macOS.
When using the above to connect to room I get error:
`Unable to getUserMedia: NotAllowedError `

**Comment by davidzhao** [comment]
Are you compiling for Mac or Web ?  If Web, which browser are you using?

**Comment by aryan1107** [comment]
Compliling for Mac. And I found problem is with Xcode 16 after few hours I had to redownload Xcode 15 and it worked.
