### ISSUE TITLE
[bug] Unable to switch between earpiece & speaker

### ISSUE THREAD

**Issue by rahulraj-idt** [livekit/client-sdk-flutter#603]
There is a **critical** issue where the audio is only coming through the speaker. Additionally, `Hardware.instance.canSwitchSpeakerphone` is always `false`, and `Hardware.instance.setSpeakerphoneOn(false)` has no effect on iOS.
Similarly, On Android, setting `room.setAudioOutputDevice('earpiece')` also has no effect.
This functionality used to work in version 2.1.3

**To Reproduce**
This issue is easy to reproduce by running the example app and attempting to switch to the earpiece on Android. On iOS, the button to switch to the speaker is disabled.

**Expected behavior**
Should be able to switch between earpiece & speaker. 

**Platform information**
iOS - 17.6.1, Android - 13

* **Flutter version**: 
Flutter  3.24.3
* **Plugin version**:
livekit_client: ^2.2.6

**Comment by nexowa** [comment]
We are also having same issue with flutter version 3.22.0 and livekit_client: ^2.2.6

**Comment by rahulraj-idt** [comment]
Hi @cloudwebrtc Are there any plans to fix this, as it's such a critical issue?

**Comment by cloudwebrtc** [comment]
Sorry, I just saw this, trying to fix it.

**Comment by cloudwebrtc** [comment]
@rahulraj-idt fixed it, tested and can switch the handset and speaker correctly.

**Comment by rahulraj-idt** [comment]
@cloudwebrtc It fixes the issue on android. But this still doesn't work on iOS.

**Comment by cloudwebrtc** [comment]
ah, okay, let me check it.

**Comment by rahulraj-idt** [comment]
Hello @cloudwebrtc 
I'm curious to know whether you had an opportunity to check this iOS speaker issue.

**Comment by cloudwebrtc** [comment]
fixed https://github.com/livekit/client-sdk-flutter/pull/617

**Comment by cloudwebrtc** [comment]
Yes, you are right, so I guess this is the final solution.

```
  void setSpeakerphoneOn(bool speakerOn) async {
    if (lkPlatformIs(PlatformType.iOS)) {
      if (!Hardware.instance.speakerOn && Hardware.instance.preferSpeakerOutput) {
        await Hardware.instance.setPreferSpeakerOutput(false);
      }
    }
    await Hardware.instance.setSpeakerphoneOn(speakerOn);
  }
```

https://github.com/livekit/components-flutter/blob/main/lib/src/context/media_device_context.dart#L285-L290

**Comment by std-s** [comment]
Hi, your demo still has this problem on iOS.

**Comment by cloudwebrtc** [comment]
hi @std-s, please try v2.3.4+hotfix.1, I believe the issue has been fixed
