### ISSUE TITLE
container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled

### ISSUE THREAD

**Issue by yashjasoli** [livekit/client-sdk-flutter#611]
flutter: enable screen share
[unspecified] container_create_or_lookup_app_group_path_by_app_group_identifier: client is not entitled
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001dbf97e90 libsystem_platform.dylib`_platform_strnlen + 16
libsystem_platform.dylib`:
->  0x1dbf97e90 <+16>: ldr    q0, [x2]
    0x1dbf97e94 <+20>: adr    x3, #-0x34                ; ___lldb_unnamed_symbol474
    0x1dbf97e98 <+24>: ldr    q2, [x3], #0x10
    0x1dbf97e9c <+28>: and    x4, x0, #0xf
Target 0: (Runner) stopped.
Lost connection to device.

ios app crash when screen share

**Comment by bcherry** [comment]
This happens if you don't have your app group listed in your app entitlements for your iOS project.
