### ISSUE TITLE
random video freeze when participant disconnects

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/client-sdk-flutter#63]
## description

when a participant leaves the room, some of the remaining participant may randomly experience a freeze on the video track from a remote participant or from his own stream.

## how to reproduce

run the client-sdk-flutter/example on three devices (I tried iOS, Android and chrome)
join the same room, then make one participant leave. Then check if all video streams are updating on the remaining participants

if it doesn't occur, rejoin the room on the participant that left, and try again... it will eventually happen.

btw, the audio is still alive, but the video is frozen, it gets fixed if the "frozen" participant mutes/unmutes his video

I think it's related to the visibility events being fired

tested on commit 2b375033e9cb2cd1b7eba2e547248b3b35d3c9d7
livekit-server 0.15.1

**Comment by alex-bluetrain** [comment]
oh, I forgot to mention, sometimes I get the freeze without even leaving the room, but I couldn't find a repro for that scenario, it's probably the same bug.

**Comment by alex-bluetrain** [comment]
as @davidzhao  suggested, I tried disabling the optimizeVideo option on the room, and I could no longer reproduce the issue, it must be something related to it

**Comment by alex-bluetrain** [comment]
I've been testing it for a while without the optimizeVideo, and it's much better, not only the freezing, but also there was some lag induced by the optimizeVideo feature, I had like 1 second video lag when it kicked in, and unnecesary low resolution switching, now the video plays smoothly with no delays and no freezes.

maybe that feature it should be marked as experimental and disabled by default until it's fixed and tested throughly

**Comment by hiroshihorie** [comment]
Thanks alex for the report, I'm looking into this now.

**Comment by hiroshihorie** [comment]
Hi alex this should be fixed in https://github.com/livekit/client-sdk-flutter/pull/65 but I will do more testing to make sure.

**Comment by hiroshihorie** [comment]
This feature has been renamed to `adaptiveStream` in `RoomOptions` and now is **off** by default.
The logic has been re-written and after testing I believe it is much more stable compared to before so I will close this issue for now.
