### ISSUE TITLE
[bug]Modifying properties of a view's layer off the main thread is not allowed: view <FlutterView: 0x101752bc0> with associated view controller <FlutterViewController: 0x102e58600>; backtrace: 

### ISSUE THREAD

**Issue by 1084493818** [livekit/client-sdk-flutter#634]
Modifying properties of a view's layer off the main thread is not allowed: view <FlutterView: 0x101752bc0> with associated view controller <FlutterViewController: 0x102e58600>; backtrace: 
(
	0   UIKitCore                           0x00000001902076e8 575E5140-FA6A-37C2-B00B-A4EACEDFDA53 + 22509288
	1   UIKitCore                           0x000000018ecf594c 575E5140-FA6A-37C2-B00B-A4EACEDFDA53 + 416076
	2   QuartzCore                          0x000000018df65bd8 D8E8E86D-85AC-3C90-B2E1-940235ECAA18 + 43992
	3   QuartzCore                          0x000000018df65a4c D8E8E86D-85AC-3C90-B2E1-940235ECAA18 + 43596
	4   QuartzCore                          0x000000018df62d1c D8E8E86D-85AC-3C90-B2E1-940235ECAA18 + 32028
	5   QuartzCore                          0x000000018e0ad998 D8E8E86D-85AC-3C90-B2E1-940235ECAA18 + 1386904
	6   Flutter                             0x00000001058238bc _ZNK7flutter23IOSSurfaceMetalImpeller15GetCAMetalLayerERK7SkISize + 176
	7   Flutter                             0x0000000105dc42ec _ZN7flutter23GPUSurfaceMetalImpeller12AcquireFrameERK7SkISize + 372
	8   Flutter                             0x0000000105d764e8 _ZN7flutter10Rasterizer20DrawToSurfacesUnsafeERNS_20FrameTimingsRecorderENSt3_fl6vectorINS3_10unique_ptrINS_13LayerTreeTaskENS3_14default_deleteIS6_EEEENS3_9allocatorIS9_EEEE + 736
	9   Flutter                             0x0000000105d776d0 _ZNSt3_fl10__function6__funcIZN7flutter10Rasterizer14DrawToSurfacesERNS2_20FrameTimingsRecorderENS_6vectorINS_10unique_ptrINS2_13LayerTreeTaskENS_14default_deleteIS8_EEEENS_9allocatorISB_EEEEE3$_1NSC_ISF_EEFvvEEclEv + 64
	10  Flutter                             0x0000000105845e40 _ZNK3fml10SyncSwitch7ExecuteERKNS0_8HandlersE + 72
	11  Flutter                             0x0000000105d76048 _ZN7flutter10Rasterizer14DrawToSurfacesERNS_20FrameTimingsRecorderENSt3_fl6vectorINS3_10unique_ptrINS_13LayerTreeTaskENS3_14default_deleteIS6_EEEENS3_9allocatorIS9_EEEE + 364
	12  Flutter                             0x0000000105d78598 _ZNSt3_fl10__function6__funcIZN7flutter10Rasterizer4DrawERKNS_10shared_ptrINS2_8PipelineINS2_9FrameItemEEEEEE3$_0NS_9allocatorISB_EEFvNS_10unique_ptrIS6_NS_14default_deleteIS6_EEEEEEclEOSH_ + 208
	13  Flutter                             0x0000000105d77d80 _ZN7flutter10Rasterizer4DrawERKNSt3_fl10shared_ptrINS_8PipelineINS_9FrameItemEEEEE + 452
	14  Flutter                             0x0000000105d908f8 _ZNSt3_fl10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter5Shell14OnAnimatorDrawENS_10shared_ptrINS5_8PipelineINS5_9FrameItemEEEEEE3$_0EENS_9allocatorISD_EEFvvEEclEv + 168
	15  Flutter                             0x00000001058443f0 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 592
	16  Flutter                             0x00000001058485d4 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 32
	17  CoreFoundation                      0x000000018c55e894 1532D3D8-9B3B-3F2F-B35F-55A20DDF411B + 739476
	18  CoreFoundation                      0x000000018c55e538 1532D3D8-9B3B-3F2F-B35F-55A20DDF411B + 738616
	19  CoreFoundation                      0x000000018c55e08c 1532D3D8-9B3B-3F2F-B35F-55A20DDF411B + 737420
	20  CoreFoundation                      0x000000018c4fd3b4 1532D3D8-9B3B-3F2F-B35F-55A20DDF411B + 340916
	21  CoreFoundation                      0x000000018c4fc830 CFRunLoopRunSpecific + 588
	22  Flutter                             0x00000001058486c0 _ZN3fml17MessageLoopDarwin3RunEv + 88
	23  Flutter                             0x0000000105847728 _ZNSt3_fl10__function6__funcIZN3fml6ThreadC1ERKNS_8functionIFvRKNS3_12ThreadConfigEEEES7_E3$_0NS_9allocatorISC_EEFvvEEclEv + 180
	24  Flutter                             0x00000001058473b8 _ZZN3fml12ThreadHandleC1EONSt3_fl8functionIFvvEEEEN3$_08__invokeEPv + 36
	25  libsystem_pthread.dylib             0x0000000214a0d37c _pthread_start + 136
	26  libsystem_pthread.dylib             0x0000000214a08494 thread_start + 8
)

I am using your demo, which runs directly and occasionally reports errors on the iOS 18.1 system

**Comment by cloudwebrtc** [comment]
This seems to be in flutter engine itself rather than livekit or webrtc plugin.
