### ISSUE TITLE
[bug] bypassVoiceProcessing echo issue on iOS devices

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#636]
**Describe the bug**
When `bypassVoiceProcessing` is `true`, an echo begins to occur on the IOS device. The problem only occurred on IOS devices. The problem is not observed on Android.

**To Reproduce**
`LiveKitClient.initialize(bypassVoiceProcessing: true);`

**Platform information**

* **Flutter version**: latest
* **Plugin version**: 2.2.8
* **Flutter target OS**: iOS real device

**Comment by davidzhao** [comment]
this is expected. `bypassVoiceProcessing` bypasses echo cancellation processing
