### ISSUE TITLE
[bug] Error in E2EE setup in flutter web

### ISSUE THREAD

**Issue by scharalambous3** [livekit/client-sdk-flutter#640]
**Describe the bug**
Upon trying the steps included in the documentation to setup E2EE for flutter web:

I get an error

> Error: Error when reading '.webe2ee.worker.dart': Error reading '.webe2ee.worker.dart'  (No such file or directory)
Error: No 'main' method found.
Error: Compilation failed.

**To Reproduce**
```export YOU_PROJECT_DIR=your_project_dir
git clone https://github.com/livekit/client-sdk-flutter.git
cd client-sdk-flutter && flutter pub get
dart compile js .\web\e2ee.worker.dart -o ${YOU_PROJECT_DIR}\web\e2ee.worker.dart.js
```
**Expected behavior**
No error

**Platform information**
Ubuntu 24.04.1 LTS 6.8.0-45-generic

* **Flutter version**:  Flutter version 3.24.3 on channel stable
* **Plugin version**: N/A
* **Flutter target OS**:  web
* **Flutter target OS version**:  N/A
* **Flutter console log**:

**Comment by cloudwebrtc** [comment]
just replace `\` to `/` if you are using UNIX like system,

`dart compile js ./web/e2ee.worker.dart -o ${YOU_PROJECT_DIR}/web/e2ee.worker.dart.js`
