### ISSUE TITLE
[bug]Screen Sharing Unavailable on macOS

### ISSUE THREAD

**Issue by AoEiuV020** [livekit/client-sdk-flutter#647]
**Describe the bug**
Screen Sharing Only Shows the App Itself on macOS, Not the Real Screen or Windows

Is there a specific permission required on macOS or any steps to perform?
Should adjustments be made in livekit_client or the example app?
**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 3.24.5
* **Plugin version**: 2.2.8
* **Flutter target OS**: Mac
* **Flutter target OS version**: 15.1.1
* **Flutter console log**: 
![image](https://github.com/user-attachments/assets/75d861cd-1db7-4669-a1f3-d39abc3aafc9)

**Comment by cloudwebrtc** [comment]
hey,  this is related to the system privacy settings. If you are running `flutter run -d macos`, you can try to allow `Terminal` to access the screen. If you are running the `flutter app` directly, please confirm that your app has been added and allowed to access the screen. Sometimes the mac system will have bugs. You can try to remove your `flutter app` from this setting list and re-run the `flutter app`.

<img width="712" alt="image" src="https://github.com/user-attachments/assets/d757fca5-908f-4a7a-9f5d-3b66e9c16c8f">
