### ISSUE TITLE
livekit_client: ^2.3.1  CocoaPods could not find compatible versions for pod "WebRTC-SDK"

### ISSUE THREAD

**Issue by shibakar** [livekit/client-sdk-flutter#648]
```cmd[!] CocoaPods could not find compatible versions for pod "WebRTC-SDK":
  In Podfile:
    flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`) was resolved to 0.12.2, which depends on
      WebRTC-SDK (= 125.6422.06)

    livekit_client (from `.symlinks/plugins/livekit_client/ios`) was resolved to 2.3.1, which depends on
      WebRTC-SDK (= 125.6422.05)```

Done the below 

```cmd
rm -rf Pods Podfile.lock build .symlinks
flutter clean
flutter pub get
pod deintegrate
pod update
pod install
flutter build ios
```

**Comment by mminhlequang** [comment]
up

**Comment by LittleSheep2Code** [comment]
Add this in pubspec.yaml may help:

```yaml
flutter_webrtc: 0.12.2
```

Looks like livekit didn't handle the versioning of deps correctly and flutter_webrtc released a new version and make the CocoaPods find a conflict on dependency version.

**Comment by LittleSheep2Code** [comment]
> Hi @LittleSheep2Code ,
> 
> This but is not fixed. I am already using latest version of everything, also added `flutter_webrtc: ` to my `pubspec.yaml` file but still I am getting this error:
> 
> ```shell
> Analyzing dependencies
> [!] CocoaPods could not find compatible versions for pod "WebRTC-SDK":
>   In snapshot (Podfile.lock):
>     WebRTC-SDK (= 125.6422.05)
> 
>   In Podfile:
>     flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`) was resolved to 0.12.2, which depends on
>       WebRTC-SDK (= 125.6422.06)
> 
> 
> You have either:
>  * changed the constraints of dependency `WebRTC-SDK` inside your development pod `flutter_webrtc`.
>    You should run `pod update WebRTC-SDK` to apply changes you've made.
> ```

Try to cd to your ios directory and remove `Podfile.lock` then run `pod install` again. It should be work.

**Comment by ashifali3147** [comment]
Getting this

```shell
pod install
Analyzing dependencies
Downloading dependencies
Installing DTTJailbreakDetection (0.4.0)
Installing Flutter (1.0.0)
Installing Toast (4.1.1)
Installing WebRTC-SDK (125.6422.06)
Installing connectivity_plus (0.0.1)
Installing device_info_plus (0.0.1)
Installing flutter_webrtc (0.12.2)
Installing fluttertoast (0.0.2)
Installing livekit_client (2.3.2)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing permission_handler_apple (9.3.0)
Installing safe_device (1.0.0)
Installing wakelock_plus (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 14 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] The `Runner [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Runner [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Runner [Profile]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by LittleSheep2Code** [comment]
> Getting this
> 
> ```shell
> pod install
> Analyzing dependencies
> Downloading dependencies
> Installing DTTJailbreakDetection (0.4.0)
> Installing Flutter (1.0.0)
> Installing Toast (4.1.1)
> Installing WebRTC-SDK (125.6422.06)
> Installing connectivity_plus (0.0.1)
> Installing device_info_plus (0.0.1)
> Installing flutter_webrtc (0.12.2)
> Installing fluttertoast (0.0.2)
> Installing livekit_client (2.3.2)
> Installing package_info_plus (0.4.5)
> Installing path_provider_foundation (0.0.1)
> Installing permission_handler_apple (9.3.0)
> Installing safe_device (1.0.0)
> Installing wakelock_plus (0.0.1)
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 11 dependencies from the Podfile and 14 total pods installed.
> 
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
> 
> [!] The `Runner [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `Runner [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `Runner [Profile]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> ```

I didn't meet this error before, but I think this stackoverflow post may help: https://stackoverflow.com/questions/26287103/cocoapods-warning-cocoapods-did-not-set-the-base-configuration-of-your-project
