### ISSUE TITLE
CocoaPods could not find compatible versions for pod "WebRTC-SDK":

### ISSUE THREAD

**Issue by narenrana** [livekit/client-sdk-flutter#66]
Getting Below error with livekit latest version 0.5.5 in IOS simulator 
 
  [!] CocoaPods could not find compatible versions for pod "WebRTC-SDK":
  In Podfile:
    flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`) was resolved to 0.7.1, which depends on
      WebRTC-SDK (= 93.4577.01)

    livekit_client (from `.symlinks/plugins/livekit_client/ios`) was resolved to 0.5.5, which depends on
      WebRTC-SDK (~> 92.4515)
 
**Solution** - 
 
Works fine after upgrading flutter webrtc version and changing  client pod spec file as below. 

 pubspec.yml ->  flutter_webrtc: ^0.8.1 
 livekit_client.podspec->  s.dependency 'WebRTC-SDK', '~> 93.4577.01'

So please bump flutter webrtc version .

**Comment by hiroshihorie** [comment]
Hi I will release a new version soon but can you try for now:

```yaml
dependency_overrides:
  flutter_webrtc: 0.8.0
```

in your pubspec.yaml file.

**Comment by hiroshihorie** [comment]
Hi @narenrana I have just released `v0.5.6` and this issue should resolve, please upgrade your dependencies and try again. Please let me know if you have any more issues, I will close this for now.
