### ISSUE TITLE
[Bug] -  When I start example app and ToggleCamera the app crash

### ISSUE THREAD

**Issue by jack2992** [livekit/client-sdk-flutter#7]
Hi master,
Please follow the following instructions before filing a bug:
Step reproduce:
1. Run app -> Join a room
2. Touch button (Toggle Camera)
3. Result App crash
Expected: Function change font or back of the camera
Note: I think the problem may be related to policy and permissions for android version 10 and above.

Here the stack trace:
`D/FlutterWebRTCPlugin(23368): CameraEventsHandler.onCameraOpening: cameraName=0
D/FlutterWebRTCPlugin(23368): CameraEventsHandler.onCameraError: errorDescription=Camera device has encountered a fatal error.
D/FlutterWebRTCPlugin(23368): CameraEventsHandler.onFirstFrameAvailable
D/FlutterWebRTCPlugin(23368): CameraEventsHandler.onFirstFrameAvailable
E/AndroidRuntime(23368): FATAL EXCEPTION: main
E/AndroidRuntime(23368): Process: com.example.applive, PID: 23368
E/AndroidRuntime(23368): java.lang.IllegalArgumentException: supportsCameraApi:2341: Unknown camera ID 0
E/AndroidRuntime(23368):        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1004)
E/AndroidRuntime(23368):        at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:452)
E/AndroidRuntime(23368):        at org.webrtc.Camera2Session.start(Camera2Session.java:304)
E/AndroidRuntime(23368):        at org.webrtc.Camera2Session.<init>(Camera2Session.java:296)
E/AndroidRuntime(23368):        at org.webrtc.Camera2Session.create(Camera2Session.java:274)
E/AndroidRuntime(23368):        at org.webrtc.Camera2Capturer.createCameraSession(Camera2Capturer.java:35)
E/AndroidRuntime(23368):        at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:272)
E/AndroidRuntime(23368):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(23368):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23368):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(23368):        at android.os.HandlerThread.run(HandlerThread.java:67)
E/AndroidRuntime(23368): Caused by: android.os.ServiceSpecificException: supportsCameraApi:2341: Unknown camera ID 0 (code 3)
E/AndroidRuntime(23368):        at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
E/AndroidRuntime(23368):        at android.os.Parcel.createException(Parcel.java:2357)
E/AndroidRuntime(23368):        at android.os.Parcel.readException(Parcel.java:2340)
E/AndroidRuntime(23368):        at android.os.Parcel.readException(Parcel.java:2282)
E/AndroidRuntime(23368):        at android.hardware.ICameraService$Stub$Proxy.supportsCameraApi(ICameraService.java:906)
E/AndroidRuntime(23368):        at android.hardware.camera2.CameraManager.supportsCameraApiLocked(CameraManager.java:1057)
E/AndroidRuntime(23368):        at android.hardware.camera2.CameraManager.supportsCamera2ApiLocked(CameraManager.java:1033)
E/AndroidRuntime(23368):        at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:425)`

**Comment by hiroshihorie** [comment]
Will look into it! does the camera work before toggle?

**Comment by jack2992** [comment]
> Will look into it! does the camera work before toggle?

Hi @hiroshihorie 
Yes, Camera work ok, before touch toggle button.

**Comment by hiroshihorie** [comment]
Thanks for the info @jack2992 ! I'm still trying to figure it out, will let you know if it's fixed!

**Comment by AlexanderKozhevin** [comment]
@jack2992 Do you use your own server or demo server?

**Comment by hiroshihorie** [comment]
Hello, the latest SDK is using WebRTC M97 now, can you check if issues have been resolved now?

**Comment by davidzhao** [comment]
closing due to really old issue.
