### ISSUE TITLE
Missing lines of code in 0.5.6

### ISSUE THREAD

**Issue by khoonie** [livekit/client-sdk-flutter#76]
I include in pubspec.yaml for version 0.5.6 and found that some lines of code were missing when compared to what is in GitHub. (as of Jan 27)

For example, in lib>src>participant>local.dart, these lines (line 326 onwars) are missing:

 void setTrackSubscriptionPermissions({
    required bool allParticipantsAllowed,
    List<ParticipantTrackPermission> trackPermissions = const [],
  }) =>
      room.engine.signalClient.sendUpdateSubscriptionPermissions(
        allParticipants: allParticipantsAllowed,
        trackPermissions: trackPermissions.map((e) => e.toPBType()).toList(),
      );

**Comment by hiroshihorie** [comment]
Hello @khoonie !

The **Track Subscription Permissions API** has been implemented but not yet released. New version will released after further testing.

You can see the full differences with `0.5.6` and the `main` branch here https://github.com/livekit/client-sdk-flutter/compare/v0.5.6...main

You can either wait for the new release or use `main` directly if you would just like to try it now (but please note there will be more changes until release)

To use `main` directly update your pubspec.yaml to the following:
```dart
dependencies:
  // ...
  livekit_client:
    git:
      url: https://github.com/livekit/client-sdk-flutter
      ref: main
  //...
```

But please use `main` temporarily only and try to use a released version.
Feel free to join our Slack community if you need additional help https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg
