### ISSUE TITLE
App Crash on IOS 

### ISSUE THREAD

**Issue by lowkeyboard** [livekit/client-sdk-flutter#90]
The example flutter app works on Android but it crashes on IOS.  This is from debug terminal: 
```
2022-03-05 18:00:56.492630+0300 Runner[8965:4657915] flutter: Connecting with url: , token: ...
2022-03-05 18:02:37.624834+0300 Runner[8965:4657931] [VERBOSE-3:platform_message_handler_ios.mm(106)] Check failed: task_runners_.GetPlatformTaskRunner()->RunsTasksOnCurrentThread().
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
2022-03-05 18:02:45.051701+0300 Runner[8965:4657918] [VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

```

FlutterEventChannel setStreamHandler: 
```
->  0x10bee8338 <+140>: mov    x20, x0     signaling_thread 0x0x105c156e0 (24): signal SIGABRT
```

The breakpoint line in FlutterRTCPeerConnection
`    [eventChannel setStreamHandler:dataChannel];
`

Versions: 
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.11.0-0.1.pre, on macOS 11.4 20F71 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability`

  s.dependency 'WebRTC-SDK', '~> 97.4692.02'

From pubspecyaml : 
`version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  permission_handler: ^9.2.0
  livekit_client: ^0.5.6
`

from Podfile : 
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
      #
      # Make it compile with M1 macs
      #
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = 'arm64'`

Please help i couldn't understand what the problem is, at first i thought it was about giving permissions but my app has permissions for microphone and camera, so i don't know why it's crashing like this on ios.

**Comment by hiroshihorie** [comment]
Hi, could you try with the latest **stable** channel of Flutter ?

**Comment by lowkeyboard** [comment]
Thank you so much! I totally forgot i was on dev channel, it worked upon switching to stable channel.
