### ISSUE TITLE
[IOS] Screen sharing

### ISSUE THREAD

**Issue by dadagov125** [livekit/client-sdk-flutter#93]
why doesn't it support screen sharing on ios?
when will it be implemented?

**Comment by davidzhao** [comment]
iOS requires a separate extension in order to support screen sharing. It is on our roadmap, but we don't have a clear release date for it yet.

**Comment by davidzhao** [comment]
@no-1ne I believe that's for capturing the current application's screen share. We are putting in support for screen sharing for other applications very soon. Stay tuned.

**Comment by wer-mathurin** [comment]
@davidzhao this is now supported.  You can close this ticket

**Comment by davidzhao** [comment]
Screen sharing is now available in [v1.1.0](https://github.com/livekit/client-sdk-flutter/releases/tag/v1.1.0)!
