### ISSUE TITLE
Enable/Disable microphone 

### ISSUE THREAD

**Issue by BenCherif** [livekit/client-sdk-flutter#95]
for the LocalParticipant can't switch the microphone state (Enable/Disable ) it .

**Comment by BenCherif** [comment]
any updates ?

**Comment by jdde** [comment]
@BenCherif just a hint: use 
LocalParticipant.isMicrophoneEnabled()
LocalParticipant.setMicrophoneEnabled(bool enabled)

Best regards!

**Comment by BenCherif** [comment]
thanks @jdde  for your reply , i've already use it like that , the function setMicrophoneEnabled is executing but without result ,it doesn't disable or enable the state  so the isMicrophoneEnabled func is always true .
Kind regards

**Comment by jdde** [comment]
@BenCherif on which platform are you testing it?

**Comment by BenCherif** [comment]
for now on android 11

**Comment by davidliu** [comment]
@BenCherif tested on Android 11 using the example app, this seems to be working there. Can you try running the example app and see if the microphone icon properly changes according to microphone state?

**Comment by BenCherif** [comment]
@davidliu  Thanks for your reply , i've test the example and it works so i miss something with my code , i will check it thanks for  ur valuable helping. Kind regards
