### ISSUE TITLE
validate uri constructed wrongly

### ISSUE THREAD

**Issue by msackman** [livekit/client-sdk-flutter#96]
In logs on my livekit server, I just saw a GET request to `/validate`. The request was made by the flutter client. The bug is that there is no such handler for `/validate`. If you look in the server at https://github.com/livekit/livekit-server/blob/61655c6ff05625ecd86557711cec38a4a9f7167d/pkg/service/server.go#L91 you see it's `/rtc/validate`.

Looking at [buildUri](https://github.com/livekit/client-sdk-flutter/blob/7c16d2f3ecd5180fe95c8db9b3c578bc6c457482/lib/src/utils.dart#L141), the logic going on there seems far from obvious to me, but it looks to me like it could never construct `/rtc/validate`.

Unfortunately this sort of bug is very hard to spot because of the way Go's http mux works. What will be happening is that the mux finds the health check handler for `/` and passes the request to that. It would probably be preferable to remove any `/` handler and instead have a specific `/healthcheck` so that this sort of bug becomes more obvious.

For now, I've just hacked my local copy of the server to call the validation handler on both uris, because I don't know whether the correct uri should be `/rtc/validate` or `/validate` and I've not checked all the other clients.

**Comment by davidzhao** [comment]
@msackman thanks for noticing this! You are right this is a bug.. it should indeed be `/rtc/validate`. If you are up for submitting a PR for it, that'd be great.  No worries if you are busy, we can fix it too!

**Comment by msackman** [comment]
Thanks for the quick reply. Although I've many years experience with Go, I'm very new to flutter+dart, so I suspect if I did a PR, there'd then be a lot of back and forth to get it up to idiomatic standards and style. So if it's ok with you, I think it would just be more efficient for everyone to leave it to people with more flutter/dart experience.

**Comment by davidzhao** [comment]
No problem! we'll take care of it in the next release.
