### ISSUE TITLE
Is there a listener for video freezing?

### ISSUE THREAD

**Issue by litzbalane2017** [livekit/client-sdk-flutter#98]
Good Day.

Thank you for this plugin, best webrtc implementation yet so far. However, I am running issues of client video freezes due to lag. Is there any listener for video freezing? I have already used RoomReconnectingEvent and RoomReconnectedEvent. I even tried using ParticipantConnectionQualityUpdatedEvent for both publisher and local participant to show loading, whenever connection drops to poor. However, I am still seeing cases wherein connection is good, but video freezes due to lag.

Thank you.

**Comment by davidzhao** [comment]
You can listen to [StreamStateUpdated](https://docs.livekit.io/client-sdk-flutter/livekit_client/TrackStreamStateUpdatedEvent-class.html) to get notified if that participant's video track could not be shown due to congestion

**Comment by litzbalane2017** [comment]
Thank you will look at it. However, is there any way we can listen to frames received and frames dropped? For example from logs I can see:

I/org.webrtc.Logging(31284): EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Comment by davidzhao** [comment]
Yes, if it's paused, then it is due to congestion. In that case client stats would not have received those frames.

You can configure this to behave differently on the server side: https://github.com/livekit/livekit-server/blob/master/config-sample.yaml#L52
