### ISSUE TITLE
Please adapt webrtc_interface-1.0.3

### ISSUE THREAD

**Issue by hrxiang** [livekit/client-sdk-flutter#99]
non-abstract class 'RTCDataChannelNative' is missing implementations for these members:
 - RTCDataChannel.bufferedAmount
 - RTCDataChannel.id
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RTCDataChannelNative extends RTCDataChannel {
      ^^^^^^^^^^^^^^^^^^^^
../../fvm/versions/2.10.0/.pub-cache/hosted/pub.flutter-io.cn/webrtc_interface-1.0.3/lib/src/rtc_data_channel.dart:79:12: Context: 'RTCDataChannel.bufferedAmount' is defined here.
  int? get bufferedAmount;
           ^^^^^^^^^^^^^^
../../fvm/versions/2.10.0/.pub-cache/hosted/pub.flutter-io.cn/webrtc_interface-1.0.3/lib/src/rtc_data_channel.dart:74:12: Context: 'RTCDataChannel.id' is defined here.
  int? get id;
           ^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/lwj/fvm/versions/2.10.0/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/lwj/fvm/versions/2.10.0/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by hiroshihorie** [comment]
This should be fixed.
